turbot/steampipe-plugin-aws

aws/common_columns.go
aws/service.go
aws/table_aws_s3_bucket.go

```
➜  steampipe-plugin-gcp git:(main) unset SP_LOG 
➜  steampipe-plugin-gcp git:(main) aws configure list
Name                    Value             Type    Location
----                    -----             ----    --------
profile                <not set>             None    None
access_key     ******************** shared-credentials-file    
secret_key     ******************** shared-credentials-file    
region                <not set>             None    None
➜  steampipe-plugin-gcp git:(main) steampipe query   
Welcome to Steampipe v0.1.0
Type ".inspect" for more information.
> select * from aws.aws_s3_bucket;
+------------------------------------+---------------------+-------------------------+--------------------+-----------------------+-------------------+---------------------+---- …
```

Simple query results in error: `listS3Buckets failed with panic AWS_REGION must be set`. Fixes #17

---

aws-test/tests/aws_ec2_instance/test-hydrate-expected.json
aws-test/tests/aws_ec2_instance/test-hydrate-query.sql
aws-test/tests/aws_ec2_instance/variables.tf
aws/table_aws_ec2_instance.go

```
➜  aws-test git:(issue#11) ✗ ./tint.js aws_ec2_instance
data.aws_ami.ubuntu: Refreshing state...
aws_vpc.main: Creation complete after 14s [id=vpc-08cbf98ef2467da8b] …
```

Add instance status information to  table. Closes #11

---

aws-test/tests/aws_ec2_autoscaling_group/test-hydrate-expected.json
aws-test/tests/aws_ec2_autoscaling_group/test-hydrate-query.sql
aws-test/tests/aws_ec2_autoscaling_group/variables.tf
aws/table_aws_ec2_autoscaling_group.go

The following addition will provide the details of policies for the specified Auto Scaling group.

Update AutoScaling Group table to store policy details. Closes #8

---

aws-test/tests/aws_iam_user/test-hydrate-expected.json
aws-test/tests/aws_iam_user/test-hydrate-query.sql
aws/table_aws_iam_user.go
docs/tables/aws_iam_user.md

```
> select
name,
user_id,
mfa_enabled
from
aws.aws_iam_user
where
not mfa_enabled;
+----------------+-----------------------+-------------+
| NAME           | USER_ID               | MFA_ENABLED |
+----------------+-----------------------+-------------+
| abcd           | AIDAQGDRKHTKJHQNPAAAA | false       |
| efgh           | AIDAQGDRKHTKH5AV7AAAA | false       |
| ijkl           | AIDAQGDRKHTKLVK23AAAA | false       |
+----------------+-----------------------+-------------+
```

Add MFA details to the  `aws_iam_user` table. Closes #27

---

CHANGELOG.md
README.md

_What's new?_
- New tables added to plugin([#40](https://github.com/turbot/steampipe-plugin-aws/pull/40))
- [aws_iam_account_password_policy](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_iam_account_password_policy.md)
- [aws_iam_account_summary](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_iam_account_summary.md)
- [aws_iam_action](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_iam_action.md)
- [aws_iam_credential_report](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_iam_credential_report.md)
- [aws_iam_policy_simulator](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_iam_policy_simulator.md)
_Enhancements_
- Updated: `aws_ssm_parameter` table to have …

Add CHANGELOG for version 0.3.0 of plugin. Closes #39

---

CHANGELOG.md

_What's new?_
- New tables added to plugin
- [aws_iam_access_advisor](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_iam_access_advisor.md) ([#42](https://github.com/turbot/steampipe-plugin-aws/issues/42))
- [aws_route53_record](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_route53_record.md) ([#43](https://github.com/turbot/steampipe-plugin-aws/issues/43))
- [aws_route53_zone](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/tables/aws_route53_zone.md) ([#43](https://github.com/turbot/steampipe-plugin-aws/issues/43))
_Enhancements_
- Updated: `aws_iam_credential_report` table to have `password_status` column ([#48](https://github.com/turbot/steampipe-plugin-aws/issues/48))

Add CHANGELOG for v0.4.0 of plugin. Closes #52

---

CHANGELOG.md

_What's new?_
- Added support for [connection configuration](https://github.com/turbot/steampipe-plugin-aws/blob/main/docs/index.md#connection-configuration). You may specify aws profiles, credentials, and regions for each connection in a configuration file. You can have multiple aws connections, each configured for a different aws account.
- Added multi-region support. A single connection can query multiple AWS regions, via the `regions` connection argument.
_Enhancements_
- Updated: Updated `tag_list` columns to `tags_src` for below RDS service tables.
- aws_rds_db_cluster
- aws_rds_db_cluster_parameter_group
- aws_rds_db_cluster_snapshot
- aws_rds_db_instance
- aws_rds_db_option_group
- aws_rds_db_parameter_group
- aws_rds_db_snapshot
- aws_rds_db_subnet_group
- Updated: added …

Add CHANGELOG for v0.5.0 of plugin. Closes #67

---

CHANGELOG.md

_Bug fixes_
- Recompiled plugin with latest [steampipe-plugin-sdk](https://github.com/turbot/steampipe-plugin-sdk) to resolve issue:
- Fix tables failing with error similar to `Error: pq: rpc error: code = Internal desc = get hydrate function getS3Bucket failed with panic interface conversion: interface {} is nil, not *s3.Bucket`([#89](https://github.com/turbot/steampipe-plugin-aws/issues/89)).

Add CHANGELOG for v0.5.3 Closes #91

---

aws/table_aws_region.go

Output
```
+----------------+---------------------+----------------+------------------------------------------+-----------+----------------+--------------+
| name           | opt_in_status       | title          | akas                                     | partition | region         | account_id   |
+----------------+---------------------+----------------+------------------------------------------+-----------+----------------+--------------+
| us-west-2      | opt-in-not-required | us-west-2      | ["arn:aws::us-west-2:388460667113"]      | aws       | us-west-2      | 388460667113 |
| us-east-1      | opt-in-not-required | us-east-1      | ["arn:aws::us-east-1:388460667113"]      | aws       | us-east-1      | 388460667113 |
| ap-northeast-1 | opt-in-not-required | ap-northeast-1 | …
```

aws_region table region column always shows as global?. closes #121

---

aws/common_columns.go

Common columns are shared between tables - this causes issues when joining between 2 tables 
As part of the query execution, the sdk updates the column object. Because the common columns are shared global variables, when more than one query is in progress, the data is overwritten, leading to errors such as
```
Error: column 'region' requires hydrate data from listRoute53Records but none is available
```
The solution is to replace the global variables with global functions which return a copy of the column data

Update common columns to be returned by global functions, instead of using global variables. Closes #155

---

aws/table_aws_ec2_instance.go

<details>
```
data.aws_ami.ubuntu: Refreshing state...
aws_vpc.main: Creation complete after 12s [id=vpc-03509ffafee3fda69] …
```

Add a column or a property to any existing column in aws_ec2_instance table to store LaunchTime for an instance. Closes #221

---

aws/table_aws_vpc_flow_log.go

<details>
```
SETUP: tests/aws_vpc_flow_log []
PRETEST: tests/aws_vpc_flow_log
TEST: tests/aws_vpc_flow_log
aws_cloudwatch_log_group.example: Creating...
aws_iam_role.example: Creating...
aws_cloudwatch_log_group.example: Creation complete after 3s [id=turbottest39373]
aws_iam_role.example: …
```

Update aws_vpc_flow_log with status field. Closes #228

---

docs/index.md

changed link in index.md to be qualified from the root of the website 
`aws/tables` to `/plugins/turbot/aws/tables`

Fix browse tables link

---

CHANGELOG.md

I think there are some typos in the dates in the changelog, but feel free to deny this PR if I'm wrong.

fix typo - bad date in CHANGELOG.md

---

aws/table_aws_redshift_event_subscription.go

<details>
```
```
</details>
<details>
```
```
</details>

Fix same method name in `aws_redshift_event_subscription` and `aws_redshift_parameter_group` table. Closes #295

---

aws-test/tests/aws_iam_role/test-get-expected.json
aws-test/tests/aws_iam_role/test-hydrate-expected.json
aws/table_aws_iam_role.go

<details>
```
Codys-MacBook-Pro:aws-test cbruno$ node tint.js aws_iam_role
SETUP: tests/aws_iam_role []
PRETEST: tests/aws_iam_role
TEST: tests/aws_iam_role
aws_iam_policy.named_test_resource: Creating...
aws_iam_role.named_test_resource: Creating...
aws_iam_policy.named_test_resource: Creation complete after 0s [id=arn:aws:iam::828685001623:policy/turbottest30593]
aws_iam_role.named_test_resource: Creation complete after 0s [id=turbottest30593]
aws_iam_role_policy_attachment.test-attach: Creating...
aws_iam_role_policy_attachment.test-attach: Creation …
```

Fix incorrect instance profile ARN data in aws_iam_role table fixes #285

---

aws/table_aws_acm_certificate.go
docs/tables/aws_acm_certificate.md

<details>
```
SETUP: tests/aws_acm_certificate []
PRETEST: tests/aws_acm_certificate
TEST: tests/aws_acm_certificate
tls_private_key.example: Creating...
tls_private_key.example: Creation complete after 0s [id=4fe1c12dc73a6c275ca0db63cada3e17a2710c09]
tls_self_signed_cert.example: Creating...
tls_self_signed_cert.example: …
```

Add support to query CertificateTransparencyLoggingPreference status in aws_acm_certificate. Closes #258

---

aws/table_aws_ec2_instance.go

<details>
```
```
</details>
<details>
```sql
select
i.instance_id,
i.metadata_options_http_endpoint as imds_enabled,
i.metadata_options_http_tokens as imdsv2,
r.title as role_name
from
aws_ec2_instance as i,
aws_iam_role as r
where
r.instance_profile_arns::jsonb ? i.iam_instance_profile_arn;
+---------------------+--------------+----------+----------------------------------+
| instance_id         | imds_enabled | imdsv2   | role_name                        |
+---------------------+--------------+----------+----------------------------------+
| i-0dc60dd191cb86539 | enabled      | optional | turbot_default_ec2_instance_role |
| i-022a51a815773780d | enabled      | optional | …
```

Adds metadata columns to ec2_iam_instance table

---

docs/tables/aws_iam_server_certificate.md

<details>
```
N/A
```
</details>
<details>
```
> select now()::timestamp
+---------------------+
| now                 |
+---------------------+
| 2021-04-12 06:31:25 |
+---------------------+
> select
name,
arn,
expiration
from
aws_iam_server_certificate
where
expiration < now()::timestamp;
+------------------------------------+---------------------------------------------------------------------------------+---------------------+
| name                               | arn                                                                             | expiration          |
+------------------------------------+---------------------------------------------------------------------------------+---------------------+
| …
```

[FIX] Query example for aws_iam_server_certificate not working as expected. Closes #308

---

aws-test/tests/aws_s3_bucket/test-hydrate-expected.json
aws-test/tests/aws_s3_bucket/test-list-expected.json
aws/table_aws_ec2_instance_type.go
aws/table_aws_iam_policy.go
aws/table_aws_s3_bucket.go

<details>
```
SETUP: tests/aws_s3_bucket []
PRETEST: tests/aws_s3_bucket
TEST: tests/aws_s3_bucket
aws_kms_key.mykey: Creating...
aws_kms_key.mykey: Creation complete after 6s [id=6059c096-85a3-43ad-b473-9eb41f88bd39]
aws_s3_bucket.named_test_resource: Creating...
aws_s3_bucket.named_test_resource: Still creating... [10s elapsed]
aws_s3_bucket.named_test_resource: Still creating... [20s elapsed]
aws_s3_bucket.named_test_resource: Creation complete after 27s [id=turbottest44403]
aws_s3_bucket_policy.b: Creating...
aws_s3_bucket_policy.b: Creation complete after 2s [id=turbottest44403]
re-use elsewhere in configuration, the same can now be …
```

Update hardcoded 'aws' to dynamic reference to partition in akas and arns.  Closes #320

---

aws-test/tests/aws_ec2_instance/test-get-expected.json
aws-test/tests/aws_ec2_instance/test-get-query.sql
aws-test/tests/aws_ec2_instance/test-hydrate-expected.json
aws-test/tests/aws_ec2_instance/test-list-expected.json
aws/table_aws_ec2_instance.go

<details>
```
data.aws_ami.ubuntu: Refreshing state...
aws_vpc.main: Creation complete after 12s [id=vpc-0e7575cf94254b710]
aws_subnet.named_test_resource: …
```

Add 'arn' column to aws_ec2_instance table. Closes #366

---

aws-test/tests/aws_sns_topic_subscription/test-get-subscription-attributes-expected.json
aws/table_aws_sns_topic_subscription.go

<details>
```
vishalkumar@Vishals-MacBook-Air aws-test % TURBOT_PROFILE=shaktiman TF_VAR_aws_profile=shaktiman ./tint.js tests/aws_sns_topic_subscription
SETUP: tests/aws_sns_topic_subscription []
PRETEST: tests/aws_sns_topic_subscription
TEST: tests/aws_sns_topic_subscription
aws_sqs_queue.aws_sns_subscription: …
```

Getting an error as Error: NotFound: Topic does not exist, status code: 404 from aws_sns_topic_subscription table. Closes #335

---

aws-test/tests/aws_efs_file_system/test-list-expected.json
aws-test/tests/aws_efs_file_system/test-list-query.sql
aws/table_aws_efs_file_system.go
docs/tables/aws_efs_file_system.md

<details>
```
SETUP: tests/aws_efs_file_system []
PRETEST: tests/aws_efs_file_system
TEST: tests/aws_efs_file_system
aws_efs_file_system.named_test_resource: Creating...
aws_efs_file_system.named_test_resource: Creation complete after 8s [id=fs-078753b3]
data.template_file.resource_aka: Refreshing state... …
```

Add a column to store "Enable automatic backups" for EFS file system in 'aws_efs_file_system' table. Closes #303

---

aws-test/tests/aws_vpc_security_group/test-get-expected.json
aws-test/tests/aws_vpc_security_group/test-get-query.sql
aws/table_aws_vpc_security_group.go

<details>
```
SETUP: tests/aws_vpc_security_group []
PRETEST: tests/aws_vpc_security_group
TEST: tests/aws_vpc_security_group
aws_vpc.main: Creation complete after 14s [id=vpc-0c7b1c8e0e46254d7]
aws_security_group.named_test_resource: Creating... …
```

Add arn column to aws_vpc_security_group table. Closes #376

---

aws-test/tests/aws_config_configuration_recorder/test-get-expected.json
aws-test/tests/aws_config_configuration_recorder/test-get-query.sql
aws-test/tests/aws_config_configuration_recorder/test-hydrate-expected.json
aws-test/tests/aws_config_configuration_recorder/test-list-call-expected.json
aws-test/tests/aws_config_configuration_recorder/test-turbot-expected.json
aws-test/tests/aws_config_configuration_recorder/variables.tf
aws/table_aws_config_configuration_recorder.go

<details>
```
SETUP: tests/aws_config_configuration_recorder []
PRETEST: tests/aws_config_configuration_recorder
TEST: tests/aws_config_configuration_recorder
data.template_file.resource_aka: Refreshing state...
aws_iam_role.r: Creating...
aws_iam_role.r: Creation complete after 5s [id=turbottest91142]
aws_config_configuration_recorder.named_test_resource: Creating...
aws_config_configuration_recorder.named_test_resource: Creation complete after 2s [id=turbottest91142]
The …
```

Add 'arn' column to aws_config_configuration_recorder table closes #370

---

aws/table_aws_redshift_cluster.go
docs/tables/aws_redshift_cluster.md

<details>
```
SETUP: tests/aws_redshift_cluster []
PRETEST: tests/aws_redshift_cluster
TEST: tests/aws_redshift_cluster
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Creation complete after 19s [id=vpc-03469fa3c39de898d]
aws_internet_gateway.igw: Creating...
aws_internet_gateway.igw: Creation complete after 6s [id=igw-0c8027f1e6942a06d]
aws_subnet.my_subnet1: Creating...
aws_subnet.my_subnet2: Creating...
aws_subnet.my_subnet2: Creation complete after 4s [id=subnet-05121773bfed20728]
aws_subnet.my_subnet1: Creation complete after 5s [id=subnet-04320b80dd353904b]
aws_redshift_subnet_group.my_subnet_group: Creating...
aws_redshift_subnet_group.my_subnet_group: Creation complete after 3s …
```

Add a column in aws_redshift_cluster table to store audit logging information. Closes #333

---

aws-test/bin
aws/table_aws_kms_key.go

steampipe query "select key_rotation_enabled from aws_kms_key where origin = 'EXTERNAL'"
+----------------------+
| key_rotation_enabled |
+----------------------+
| <null>               |
| <null>               |
| <null>               |
+----------------------+
steampipe query "select origin, key_rotation_enabled from aws_kms_key"     
+----------+----------------------+
| origin   | key_rotation_enabled |
+----------+----------------------+
| AWS_KMS  | false                |
| AWS_KMS  | true                 |
| AWS_KMS  | true                 |
| AWS_KMS  | false                |
| AWS_KMS  | true                 |
| AWS_KMS  | true                 |
| EXTERNAL | <null>               |
| AWS_KMS  | false                |
| EXTERNAL | <null>               |
| EXTERNAL | <null> …

return null for key_rotation_enabled when origin=EXTERNAL

---

aws/table_aws_ebs_snapshot.go
docs/tables/aws_ebs_snapshot.md

<details>
```
aws_ebs_volume.test_volume: Creating...
aws_ebs_volume.test_volume: Still creating... [10s elapsed]
aws_ebs_volume.test_volume: Creation complete after 15s [id=vol-0e3ac6780e5445870]
aws_ebs_snapshot.named_test_resource: Creating...
aws_ebs_snapshot.named_test_resource: Creation complete after 4s [id=snap-0b466018061d8ae5e]
aws_snapshot_create_volume_permission.example_perm: Creating...
aws_snapshot_create_volume_permission.example_perm: Still creating... [10s elapsed]
aws_snapshot_create_volume_permission.example_perm: Creation complete after 14s [id=snap-0b466018061d8ae5e-388460667113]
The null_data_source was …
```

Add 'arn' column to aws_ebs_snapshot table. Closes #391

---

aws-test/tests/aws_vpc_eip/test-get-expected.json
aws-test/tests/aws_vpc_eip/test-get-query.sql
aws/table_aws_vpc_eip.go

<details>
```
SETUP: tests/aws_vpc_eip []
PRETEST: tests/aws_vpc_eip
TEST: tests/aws_vpc_eip
aws_eip.named_test_resource: Creating...
aws_eip.named_test_resource: Creation complete after 2s [id=eipalloc-00e3bae6a3908370b]
data.template_file.resource_aka: Reading...
data.template_file.resource_aka: Read complete after 0s [id=22fbdd015a523114439f60aebdf4643025b1f683ad324f448b5f5a5acdd9a8ea]
re-use elsewhere in configuration, the same can now be achieved using locals
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
Outputs:
public_ip = "35.171.125.28"
resource_aka = "arn:aws:ec2:us-east-1:013122550996:eip/eipalloc-00e3bae6a3908370b" …
```

Add 'arn' column to aws_vpc_eip table. Closes #393

---

docs/tables/aws_lambda_function.md

…
<details>
```
NA
```
</details>
<details>
```
Table: aws_lambda_function
> select
fn.name,
fn.region,
count (availability_zone) as zone_count
from
aws_lambda_function as fn
cross join jsonb_array_elements_text(vpc_subnet_ids) as vpc_subnet
join aws_vpc_subnet as sub on sub.subnet_id = vpc_subnet
group by
fn.name,
fn.region
order by
zone_count;
+---------+-----------+------------+
| name    | region    | zone_count |
+---------+-----------+------------+
| testing | us-east-2 | 1          |
| test5   | us-east-2 | 3          |
+---------+-----------+------------+
```
</details>

Improve / fix example: Availability zone count for each VPC lambda function. Closes #396

---

aws-test/tests/aws_guardduty_detector/test-list-expected.json
aws-test/tests/aws_guardduty_detector/test-list-query.sql
aws/table_aws_guardduty_detector.go
docs/tables/aws_guardduty_detector.md

<details>
```
SETUP: tests/aws_guardduty_detector []
PRETEST: tests/aws_guardduty_detector
TEST: tests/aws_guardduty_detector
aws_guardduty_detector.named_test_resource: Creating...
aws_guardduty_detector.named_test_resource: Creation complete after 3s [id=6c983ebd982a448492568221c6879275] …
```

Add 'arn' column to aws_guardduty_detector table. Closes #395

---

aws/plugin.go
aws/table aws_sagemaker_training_job.go
aws/table_aws_sagemaker_training_job.go
docs/tables/aws_sagemaker_training_job.md

<details>
```
Terraform not supported. Resource creation is failed through cli  and also this resource doesn't have any delete api call
```
</details>
<details>
```
select
name,
arn,
training_job_status,
creation_time,
last_modified_time
from
aws_sagemaker_training_job;
+-----------------------------+-----------------------------------------------------------------------------------+---------------------+---------------------+---------------------+
| name                        | arn                                                                               | training_job_status | creation_time       | last_modified_time  |
+-----------------------------+----------------------------------------------------------------------------------- …
```

Add table aws_sagemaker_training_job. Closes #348

---

aws/table_aws_ec2_instance.go
aws/table_aws_ec2_launch_configuration.go
aws/utils.go
docs/tables/aws_ec2_instance.md
docs/tables/aws_ec2_launch_configuration.md

<details>
```
SETUP: tests/aws_ec2_launch_configuration []
PRETEST: tests/aws_ec2_launch_configuration
TEST: tests/aws_ec2_launch_configuration
aws_ebs_volume.my_volume: Creating...
aws_ebs_volume.my_volume: Still creating... [10s elapsed]
aws_ebs_volume.my_volume: Creation complete after 14s [id=vol-0a2167ddb36ce908e]
aws_ebs_snapshot.my_snapshot: Creating...
aws_ebs_snapshot.my_snapshot: Creation complete after 3s [id=snap-09a75f883a51923ed]
aws_ami.named_test_resource: Creating...
aws_ami.named_test_resource: Still creating... [10s elapsed]
aws_ami.named_test_resource: Creation complete after 11s [id=ami-0ecf7b5ba1697e802]
aws_launch_configuration.named_test_resource: Creating...
aws_launch_configuration.named_test_resource: Creation complete …
```

Decoding of secrets rendered in the encoded user_data for EC2. Closes #261

---

aws-test/tests/aws_redshift_cluster/test-get-expected.json
aws-test/tests/aws_redshift_cluster/test-get-query.sql
aws-test/tests/aws_redshift_cluster/test-hydrate-expected.json
aws-test/tests/aws_redshift_cluster/test-hydrate-query.sql
aws/table_aws_redshift_cluster.go
docs/tables/aws_redshift_cluster.md

<details>
```
SETUP: tests/aws_redshift_cluster []
PRETEST: tests/aws_redshift_cluster
TEST: tests/aws_redshift_cluster
aws_vpc.my_vpc: Refreshing state... [id=vpc-0b1a0e5b13ad8c64a]
aws_internet_gateway.igw: Refreshing state... [id=igw-074e9de833bbd7bea]
aws_subnet.my_subnet1: Refreshing state... [id=subnet-0368deefa845c0cf6]
aws_subnet.my_subnet2: Refreshing state... [id=subnet-0b7a8ceb19eb982ee]
aws_redshift_subnet_group.my_subnet_group: Refreshing state... [id=turbottest88863]
aws_redshift_cluster.named_test_resource: Refreshing state... [id=turbottest88863]
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
~ resource "aws_internet_gateway" "igw" …
```

Add table aws_redshift_cluster arn. Closes #452

---

aws-test/tests/aws_vpc_network_acl/test-get-expected.json
aws-test/tests/aws_vpc_network_acl/test-get-query.sql
aws/table_aws_vpc_network_acl.go
docs/tables/aws_vpc_network_acl.md

<details>
```
vishalkumar@Vishals-MacBook-Air aws-test % TURBOT_PROFILE=shaktiman TF_VAR_aws_profile=shaktiman ./tint.js tests/aws_vpc_network_acl
SETUP: tests/aws_vpc_network_acl []
PRETEST: tests/aws_vpc_network_acl
TEST: tests/aws_vpc_network_acl
aws_vpc.main: Still creating... [10s …
```

Add column arn for the table aws_vpc_network_acl. Closes #451

---

aws-test/tests/aws_s3_bucket/test-hydrate-expected.json
aws-test/tests/aws_s3_bucket/test-hydrate-query.sql
aws-test/tests/aws_s3_bucket/variables.tf
aws/table_aws_s3_bucket.go
docs/tables/aws_s3_bucket.md

<details>
```
SETUP: tests/aws_s3_bucket []
PRETEST: tests/aws_s3_bucket
TEST: tests/aws_s3_bucket
+ create
+ resource "aws_kms_key" "mykey" {
+ arn                      = (known after apply)
+ customer_master_key_spec = "SYMMETRIC_DEFAULT"
+ deletion_window_in_days  = 10
+ description              = "This key is used to encrypt bucket objects"
+ enable_key_rotation      = false
+ id                       = (known after apply)
+ is_enabled               = true
+ key_id                   = (known after apply)
+ key_usage                = "ENCRYPT_DECRYPT"
+ policy …
```

Add a column to store bucket-default-lock-enabled property in aws_s3_bucket table. Closes#463

---

aws/table_aws_elasticache_cluster.go
docs/tables/aws_elasticache_cluster.md

<details>
```
SETUP: tests/aws_elasticache_cluster []
PRETEST: tests/aws_elasticache_cluster
TEST: tests/aws_elasticache_cluster
+ create
<= data "template_file" "resource_aka"  {
+ id       = (known after apply)
+ rendered = (known after apply)
+ template = "arn:${partition}:elasticache:${region}:${account_id}:cluster:turbottest40310"
+ vars     = {
+ "account_id" = "986325076436"
+ "partition"  = "aws"
+ "region"     = "us-east-1"
}
}
+ resource "aws_elasticache_cluster" "named_test_resource" {
+ apply_immediately      = (known after …
```

Add a column to store CacheCluster.SnapshotRetentionLimit property in table aws_elasticache_cluster. Closes #448

---

aws/table_aws_cloudtrail_trail.go
docs/tables/aws_cloudtrail_trail.md

<details>
```
SETUP: tests/aws_cloudtrail_trail []
PRETEST: tests/aws_cloudtrail_trail
TEST: tests/aws_cloudtrail_trail
aws_s3_bucket.named_test_resource: Creating...
aws_s3_bucket.named_test_resource: Still creating... [10s elapsed]
aws_s3_bucket.named_test_resource: Creation complete after 17s [id=turbottest66556]
aws_cloudtrail.named_test_resource: Creating...
aws_cloudtrail.named_test_resource: Creation complete after 8s [id=turbottest66556]
The null_data_source was …
```

Add shadow trails in table aws_cloudtrail_trail closes #438

---

aws-test/tests/aws_lambda_function/test-hydrate-expected.json
aws-test/tests/aws_lambda_function/test-hydrate-query.sql
aws-test/tests/aws_lambda_function/variables.tf
aws/table_aws_lambda_function.go
docs/tables/aws_lambda_function.md

<details>
```
+ create
+ output_md5          = (known after apply)
+ output_path         = "/private/var/folders/kp/kck5svs903955j7lj8t_tjx40000gp/T/tests/aws_lambda_function/terraform/test/../../test.zip"
+ output_sha          = (known after apply)
+ output_size         = (known after apply)
+ source_file         = …
```

Add column to store configuration details like dead-letter queue service and Concurrency Limit for function in aws_lambda_function table. Closes#460

---

aws-test/tests/aws_cloudwatch_alarm/test-get-expected.json
aws-test/tests/aws_cloudwatch_alarm/test-get-query.sql
aws-test/tests/aws_cloudwatch_alarm/test-hydrate-expected.json
aws-test/tests/aws_cloudwatch_alarm/test-hydrate-query.sql
aws-test/tests/aws_cloudwatch_alarm/test-list-call-expected.json
aws-test/tests/aws_cloudwatch_alarm/test-list-call-query.sql
aws-test/tests/aws_cloudwatch_alarm/test-not-found-query.sql
aws-test/tests/aws_cloudwatch_alarm/test-turbot-expected.json
aws-test/tests/aws_cloudwatch_alarm/test-turbot-query.sql
aws/table_aws_cloudwatch_alarm.go
docs/tables/aws_cloudwatch_alarm.md

<details>
```
SETUP: tests/aws_cloudwatch_alarm []
PRETEST: tests/aws_cloudwatch_alarm
TEST: tests/aws_cloudwatch_alarm
aws_cloudwatch_metric_alarm.named_test_resource: Creating...
aws_cloudwatch_metric_alarm.named_test_resource: Creation complete after 4s [id=turbottest69767]
re-use elsewhere in configuration, the same can now be achieved using locals
Apply complete! Resources: 1 added, 0 changed, 0 …
```

Update column name alarm_arn to arn in aws_cloudwatch_alarm table closes #483

---

aws/table_aws_inspector_assessment_template.go

<details>
```
```
</details>
<details>
> select name,event_subscriptions from aws_inspector_assessment_template where name like '%POC%' or name like '%caleb%';;
```
```
+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------
| name                       | event_subscriptions                                                                                                                                        
+----------------------------+----------------------------------------------------------- …

added event subscriptions field

---

.github/labels.yml
.github/workflows/stale.yml

- Add a workflow which will stale the issues/PRs if no activity found for a given time period
- Issues/PRs should be stale after 30 days
- Issues/PRs should be close after 30 days
- The workflow should post a comment in the Issue/PR while doing stale/close

Add Stale workflow for Issues/PRs closes #373

---

aws/table_aws_redshift_cluster.go

<details>
```
SETUP: tests/aws_redshift_cluster []
PRETEST: tests/aws_redshift_cluster
TEST: tests/aws_redshift_cluster
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Creation complete after 12s [id=vpc-09466eea9c63b4916]
aws_internet_gateway.igw: Creating... …
```

Remove use of deprecated function ItemFromKey from table aws_redshift_cluster. Closes #513

---

aws/table_aws_iam_credential_report.go
go.mod
go.sum

<details>
```
```
</details>
<details>
```
N/A
```
</details>

Improve error message from aws_iam_credential_report when no credential report exists. Closes #509

---

aws-test/tests/aws_dynamodb_table/test-get-expected.json
aws-test/tests/aws_dynamodb_table/test-get-query.sql
aws-test/tests/aws_dynamodb_table/test-list-expected.json
aws-test/tests/aws_dynamodb_table/test-list-query.sql
aws/table_aws_dynamodb_table.go

<details>
```
SETUP: tests/aws_dynamodb_table []
PRETEST: tests/aws_dynamodb_table
TEST: tests/aws_dynamodb_table
aws_dynamodb_table.named_test_resource: Creating...
aws_dynamodb_table.named_test_resource: Still creating... [10s elapsed]
aws_dynamodb_table.named_test_resource: Creation complete after 13s [id=turbottest92110]
re-use elsewhere in configuration, the same can now be achieved using locals …
```

Update column name table_arn to arn in aws_dynamodb_table table closes #487

---

aws/table_aws_efs_file_system.go
docs/tables/aws_efs_file_system.md

<details>
```
SETUP: tests/aws_efs_file_system []
PRETEST: tests/aws_efs_file_system
TEST: tests/aws_efs_file_system
aws_efs_file_system.named_test_resource: Creating...
aws_efs_file_system.named_test_resource: Creation complete after 6s [id=fs-178b05a3]
data.template_file.resource_aka: Refreshing state...
aws_efs_file_system_policy.efs_file_system_policy: Creating...
aws_efs_file_system_policy.efs_file_system_policy: Creation complete after 2s [id=fs-178b05a3]
The …
```

Update the column name file_system_arn to arn for the table aws_efs_file_system closes #493

---

aws/multi_region.go
aws/service.go

<details>
```
cat ~/.steampipe/config/aws.spc
connection "usgov" {
plugin     = "aws"
access_key = "redacted"
secret_key = "redacted"
regions = ["us-gov*"]
}
steampipe query "select name, region, partition from usgov.aws_s3_bucket"
+---------------------------------------------+---------------+------------+
| name                                        | region        | partition  |
+---------------------------------------------+---------------+------------+
| cody-test-us-east-bucket                    | us-gov-east-1 | aws-us-gov |
| elasticbeanstalk-us-gov-west-1-727379816578 | us-gov-west-1 | aws-us-gov |
| turbot-727379816578-us-gov-east-1           | us-gov-east-1 | aws-us-gov |
| test-poller-actor-lalit                     | us-gov-west-1 | aws-us-gov |
| …
```

Add wildcarding support for passing regions in connections for plugin. Closes #528

---

aws-test/tests/aws_vpc_nat_gateway/test-get-expected.json
aws-test/tests/aws_vpc_nat_gateway/test-get-query.sql
aws-test/tests/aws_vpc_nat_gateway/test-hydrate-expected.json
aws-test/tests/aws_vpc_nat_gateway/test-hydrate-query.sql
aws-test/tests/aws_vpc_nat_gateway/test-list-expected.json
aws-test/tests/aws_vpc_nat_gateway/test-list-query.sql
aws/table_aws_vpc_nat_gateway.go

<details>
```
SETUP: tests/aws_vpc_nat_gateway []
PRETEST: tests/aws_vpc_nat_gateway
TEST: tests/aws_vpc_nat_gateway
aws_eip.example: Creating...
aws_eip.example: Creation complete after 2s [id=eipalloc-06d0502a7635c2553]
aws_vpc.main: Creation …
```

Add column arn in table aws_vpc_nat_gateway. Closes #539

---

aws/table_aws_ec2_instance.go

<details>
```
> select instance_id,instance_state,launch_time,state_transition_time,region,account_id from awsagg.aws_ec2_instance where instance_state <> 'running'
+---------------------+----------------+---------------------+-----------------------+------------+--------------+
| instance_id         | instance_state | launch_time         | state_transition_time | region     | account_id   |
+---------------------+----------------+---------------------+-----------------------+------------+--------------+
| i-0680816e3feed28b0 | stopped        | 2021-07-29 03:55:24 | 2021-07-29 04:14:29   | ap-south-1 | 013122550996 |
| i-0bd0fba70e1c158c9 | stopped        | 2019-10-31 14:13:38 | 2019-11-14 05:27:26   | us-east-1  | 828685001623 |
| i-0eb8936103e4590f9 | stopped …
```

Fix: table aws_ec2_instance to handle empty value for StateTransitionReason. Fixes #575

---

aws/table_aws_cloudtrail_trail.go

<details>
```
```
</details>
<details>
```
> select name,region, home_region,arn, is_organization_trail, is_multi_region_trail, tags_src, tags from awsagg.aws_cloudtrail_trail
+--------------------------------+----------------+-------------+--------------------------------------------------------------------------------+-----------------------+-----------------------+----------
| name                           | region         | home_region | arn                                                                            | is_organization_trail | is_multi_region_trail | tags_src 
+--------------------------------+----------------+-------------+----------------------------------------------------------- …
```

Fix aws_cloudtrail_trail table queries fail to get organization trails. Closes #577

---

aws/table_aws_route53_zone.go

<details>
```
> select name,dnssec_key_signing_keys,dnssec_status,private_zone from aws_route53_zone
+---------------+-------------------------+-------------------------------------------------------+--------------+
| name          | dnssec_key_signing_keys | dnssec_status                                         | private_zone |
+---------------+-------------------------+-------------------------------------------------------+--------------+
| allithub.com. | <null>                  | <null>                                                | true         |
| turbot.com.   | <null>                  | {"ServeSignature":"NOT_SIGNING","StatusMessage":null} | false        |
+---------------+-------------------------+------------------------------------------------------ …
```

Add check for private hosted zones in dnssec hydrate method for aws_route53_zone table. Closes #587

---

aws/table_aws_securityhub_standards_subscription.go

<details>
```
```
</details>
<details>
```
```
</details>

Fix go lint issue for aws_securityhub_standards_subscription table. Fixes #602

---

aws/service.go

</details>
<details>
```
connection "aws" {
access_key = "*****"
secret_key = "*****"
plugin    = "aws"               
}
sourab@Souravs-MacBook-Air-3 aws-test % export AWS_REGION=ap-south-1
sourab@Souravs-MacBook-Air-3 aws-test % steampipe query             
Welcome to Steampipe v0.7.0
> select * from aws_cloudtrail_trail
+------+-------------------------------------------------------+-------------+-----------------------+-----------------------------+------------+---------------+--------------------------+----------------
| name | arn                                                   | home_region | is_multi_region_trail | log_file_validation_enabled | is_logging | log_group_arn | cloudwatch_logs_role_arn | has_custom_even …
```

Fix region pattern match in service file. Closes #595

---

aws-test/tests/aws_ec2_ssl_policy/test-get-query.sql
aws/table_aws_ec2_ssl_policy.go
docs/tables/aws_ec2_ssl_policy.md

<details>
```
arnab@turbotindias-MacBook-Pro aws-test % ./tint.js aws_ec2_ssl_policy
SETUP: tests/aws_ec2_ssl_policy []
PRETEST: tests/aws_ec2_ssl_policy
TEST: tests/aws_ec2_ssl_policy
on variables.tf line 37, in data "null_data_source" "resource":
37: data "null_data_source" "resource" {
re-use elsewhere in configuration, the same can now be achieved using locals
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
account_id = …
```

Fix table_aws_ec2_ssl_policy returning duplicate result when more than 1 region set in config. Closes #591

---

aws/service.go

Because most of the global services (like IAM, s3, Route53, etc..) in both cloud are the targeting the respective regions

Update default region for `us-gov` and `cn` partition. #595

---

aws/table_aws_elasticsearch_domain.go
docs/tables/aws_elasticsearch_domain.md

<details>
```
arnab@turbotindias-MacBook-Pro aws-test % ./tint.js aws_elasticsearch_domain
SETUP: tests/aws_elasticsearch_domain []
PRETEST: tests/aws_elasticsearch_domain
TEST: tests/aws_elasticsearch_domain
aws_elasticsearch_domain.named_test_resource: Creating...
aws_elasticsearch_domain.named_test_resource: Still creating... [10s elapsed]
aws_elasticsearch_domain.named_test_resource: Still creating... [20s elapsed]
aws_elasticsearch_domain.named_test_resource: Still creating... [30s elapsed]
aws_elasticsearch_domain.named_test_resource: Still …
```

Add Logs details in table aws_elasticsearch_domain. Closes #582

---

aws/table_aws_ec2_instance.go

<details>
```
+ create
+ resource "aws_instance" "named_test_resource" {
+ ami                                  = "ami-04bdd81ca5f1191d5"
+ arn                                  = (known after apply)
+ associate_public_ip_address          = false
+ availability_zone                    = (known after apply)
+ cpu_core_count                       = (known after apply)
+ cpu_threads_per_core                 = (known after apply)
+ disable_api_termination              = (known …
```

Add column `instance_lifecycle` in `aws_ec2_instance` table. Closes #616

---

aws/plugin.go
aws/table_aws_lambda_function_metric_errors_daily.go
docs/tables/aws_lambda_function_metric_errors_daily.md

<details>
```
> select
name,
timestamp,
minimum,
maximum,
average,
sample_count
from
aws_lambda_function_metric_errors_daily
order by
name,
timestamp;
+--------------------------+---------------------+---------+---------+--------------------+--------------+
| name                     | timestamp           | minimum | maximum | average            | sample_count |
+--------------------------+---------------------+---------+---------+--------------------+--------------+
| arnab-hello-world-python | 2021-08-22 12:00:00 | 0       | 1       | 0.3333333333333333 | 6            |
| arnab-hello-world-python | 2021-08-23 12:00:00 | 1       | 1       | 1                  | 3            |
| func-encrypted           | 2021-06-30 12:00:00 | 0       | 0       | 0 …
```

Add table aws_lambda_function_metric_errors_daily. Closes #622

---

aws/table_aws_macie2_classification_job.go

<details>
```
> select * from aws_macie2_classification_job
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| name         | job_id                           | arn                                                                                       | job_status | job_type | client_token                        
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| bucket-audit | f9d91733ace0a93c09e8da13f598916e | …
```

Handle AccessDeniedException - macie is not enabled

---

aws/table_aws_iam_credential_report.go

<details>
```
> select user_name,user_arn,password_enabled from aws_iam_credential_report where user_name = '<root_account>'
+----------------+--------------------------------+------------------+
| user_name      | user_arn                       | password_enabled |
+----------------+--------------------------------+------------------+
| <root_account> | arn:aws:iam::632902152528:root | false            |
+----------------+--------------------------------+------------------+```
</details>

Handling <root_account> password_enabled check in table_aws_iam_credential_report table.Closes #656

---

aws/table_aws_macie2_classification_job.go

<details>
```
> select * from aws_macie2_classification_job where job_id = 'f9d91733ace0a93c09e8da13f598916e'
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| name         | job_id                           | arn                                                                                       | job_status | job_type | client_token                        
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| bucket-audit | …
```

Handling exceptions aws_macie2_classification_job table. Closes #641

---

aws/table_aws_auditmanager_evidence.go
aws/table_aws_cloudfront_cache_policy.go
aws/table_aws_cloudfront_origin_request_policy.go
aws/table_aws_codepipeline_pipeline.go
aws/table_aws_directory_service_directory.go
aws/table_aws_dynamodb_table.go
aws/table_aws_ec2_instance_availability.go
aws/table_aws_ec2_instance_type.go
aws/table_aws_efs_mount_target.go
aws/table_aws_iam_access_key.go
aws/table_aws_kinesisanalyticsv2_application.go
aws/table_aws_kms_key.go
aws/table_aws_sagemaker_endpoint_configuration.go
aws/table_aws_sagemaker_model.go
aws/table_aws_sagemaker_notebook_instance.go
aws/table_aws_sagemaker_training_job.go
aws/table_aws_ssm_managed_instance_compliance.go
aws/table_aws_vpc_endpoint_service.go
aws/table_aws_waf_rate_based_rule.go
aws/table_aws_waf_rule.go
aws/table_aws_wafv2_ip_set.go
aws/table_aws_wafv2_regex_pattern_set.go
aws/table_aws_wafv2_rule_group.go
aws/table_aws_wafv2_web_acl.go
aws/utils.go

<details>
```
#Below are the tables for which pagination has been implemented -
table_aws_auditmanager_evidence
table_aws_cloudfront_cache_policy
table_aws_codepipeline_pipeline
table_aws_directory_service_directory
table_aws_dynamodb_table
table_aws_ec2_instance_availability
table_aws_ec2_instance_type
table_aws_efs_mount_target
table_aws_iam_access_key
table_aws_kinesisanalyticsv2_application
table_aws_kms_key
table_aws_sagemaker_endpoint_configuration
table_aws_sagemaker_model
table_aws_sagemaker_notebook_instance
table_aws_sagemaker_training_job
table_aws_ssm_managed_instance_compliance
table_aws_vpc_endpoint_service
#Log output to test pagination for aws_auditmanager_evidence table.
2021-09-24T13:52:11.956+0530 [ERROR] plugin.steampipe-plugin-aws.plugin: …
```

Fix tables with missing pagination implementations. Closes #651

---

aws/table_aws_ssm_managed_instance.go

<details>
```
```
</details>
<details>
```
> select count(*) as total from aws_ssm_managed_instance
+-------+
| total |
+-------+
| 1     |
+-------+
> select instance_id, platform_version from aws_ssm_managed_instance
+---------------------+------------------+
| instance_id         | platform_version |
+---------------------+------------------+
| i-0f69c3d430d17f714 | 2                |
+---------------------+------------------+
```
</details>

Fix incorrect data type for platform_version in aws_ssm_managed_instance. Closes #731

---

aws/plugin.go
aws/table_aws_lambda_layer.go
docs/tables/aws_lambda_layer.md

An integration test is not feasible as it requires a zip file either locally or stored in a S3 bucket.
<details>
```
> select
layer_arn,
layer_name,
layer_version_arn,
created_date,
jsonb_pretty(compatible_runtimes) as compatible_runtimes,
jsonb_pretty(compatible_architectures) as compatible_architectures,
version
from
aws_lambda_layer;
+-------------------------------------------------------+------------+---------------------------------------------------------+------------------------------+---------------------+--------------------------+---------+
| layer_arn                                             | layer_name | layer_version_arn                                       | created_date                 | compatible_runtimes | compatible_architectures | …
```

Add table aws_lambda_layer. Closes #738

---

aws/table_aws_iam_role.go

```
❯ make                                                                                                                                                                                                                     ─╯
go build -o  ~/.steampipe/plugins/hub.steampipe.io/plugins/turbot/aws@latest/steampipe-plugin-aws.plugin  *.go
❯ steampipe query                                                                                                                                                                                                          ─╯
Welcome to Steampipe v0.9.0
> select role_last_used_date, role_last_used_region from aws_iam_role
+----------------------+-----------------------+
| role_last_used_date  | role_last_used_region | …
```

Fix: The column's(role_last_used_region, role_last_used_date) content of the aws_iam_role table displays an abnormal value(null).

---

aws/service.go
aws/table_aws_region.go

```
➜  steampipe-plugin-aws git:(issue-698) ✗ make
go build -o  ~/.steampipe/plugins/hub.steampipe.io/plugins/turbot/aws@latest/steampipe-plugin-aws.plugin  *.go
➜  steampipe-plugin-aws git:(issue-698) ✗ steampipe query
Welcome to Steampipe v0.9.0
> selec2021-11-02T15:27:12.289+0530 [INFO]  steampipe: [Trace] SetUserSearchPath
> select
Time: 1.174077ms
> select * from aws_region
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
> select * from aws_iam_group
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
> .quit
➜  steampipe-plugin-aws git:(issue-698) ✗ aws configure list …
```

Fix: plugin to not retry (as it makes query to hang for long) in case the provided credentials are not valid or credentials are not available.

---

aws/table_aws_iam_credential_report.go

<details>
```
```
</details>
<details>
```
> select
-- Required Columns
user_arn as resource,
case
when password_enabled and not mfa_active then 'alarm'
else 'ok'
end as status,
case
when not password_enabled then user_name || ' password login disabled.'
when password_enabled and not mfa_active then user_name || ' password login enabled but no MFA device configured.'
else user_name || ' password login enabled and MFA device configured.'
end as reason,
-- Additional Dimensions
account_id
from
aws_iam_credential_report;
Error: Credential report not available. Please run aws iam generate-credential-report to generate it and try again.
> 
```
</details>

Update the error message for table aws_iam_credential_report. Closes #755

---

aws/service.go

<details>
```
```
</details>
<details>
```
```
</details>

Fix: Error handling for nullity check in case of `NoCredentialProviders` error. #762

---

aws/table_aws_lambda_version.go
docs/tables/aws_lambda_version.md

<details>
```
arnab@turbotindias-MacBook-Pro aws-test % ./tint.js aws_lambda_version
SETUP: tests/aws_lambda_version []
PRETEST: tests/aws_lambda_version
TEST: tests/aws_lambda_version
+ create
+ output_md5          = (known after …
```

Add policy and policy_std columns to table aws_lambda_version. Closes #775

---

aws/table_aws_lambda_alias.go
docs/tables/aws_lambda_alias.md

<details>
```
arnab@turbotindias-MacBook-Pro aws-test % ./tint.js aws_lambda_alias
SETUP: tests/aws_lambda_alias []
PRETEST: tests/aws_lambda_alias
TEST: tests/aws_lambda_alias
+ create
+ output_md5          = (known after apply)
+ …
```

Add policy and policy_std columns to table aws_lambda_alias. Closes #773

---

aws-test/tests/aws_accessanalyzer_analyzer/variables.tf
aws-test/tests/aws_ec2_application_load_balancer/test-hydrate-expected.json
aws-test/tests/aws_ec2_application_load_balancer/variables.tf
aws-test/tests/aws_ec2_autoscaling_group/test-hydrate-expected.json
aws-test/tests/aws_elastic_beanstalk_environment/test-get-expected.json
aws-test/tests/aws_elastic_beanstalk_environment/test-hydrate-expected.json
aws-test/tests/aws_elastic_beanstalk_environment/variables.tf
aws-test/tests/aws_elasticache_replication_group/variables.tf
aws-test/tests/aws_guardduty_finding/variables.tf
aws-test/tests/aws_kinesis_firehose_delivery_stream/variables.tf
aws-test/tests/aws_s3_bucket/test-hydrate-expected.json
aws-test/tests/aws_s3_bucket/test-list-expected.json
aws-test/tests/aws_ssm_managed_instance/test-list-expected.json
aws-test/tests/aws_ssm_managed_instance/variables.tf
aws-test/tests/aws_wafv2_rule_group/test-getGlobal-expected.json
aws-test/tests/aws_wafv2_rule_group/test-getRegional-expected.json

- aws_dms_replication_instance
- aws_ec2_application_load_balancer 
- aws_elastic_beanstalk_environment
- aws_elasticache_replication_group
- aws_guardduty_finding
- aws_securityhub_standards_subscription
- aws_sfn_state_machine_execution_history
-  aws_ssm_managed_instance

Fix integration tests for steampipe-plugin-sdk v1.8.0 closes #768

---

aws/service.go
aws/table_aws_ecrpublic_repository.go

<details>
```
SETUP: tests/aws_ecrpublic_repository []
PRETEST: tests/aws_ecrpublic_repository
TEST: tests/aws_ecrpublic_repository
+ create
+ resource "aws_ecrpublic_repository" "named_test_resource" {
+ arn             = (known after apply)
+ force_destroy   = false
+ id              = (known after apply)
+ registry_id     = (known after apply)
+ repository_name = "turbottest79051"
+ repository_uri  = (known after apply)
}
Plan: 1 to add, 0 to change, 0 to destroy.
Changes to Outputs:
+ account_id    = "533793682495"
+ aws_partition = "aws"
+ aws_region    = …
```

Fix  no such host error in aws_ecrpublic_repository. Closes#766

---

aws/table_aws_ecr_repository.go

<details>
```
arnab@turbotindias-MacBook-Pro aws-test % ./tint.js aws_ecr_repository
SETUP: tests/aws_ecr_repository []
PRETEST: tests/aws_ecr_repository
TEST: tests/aws_ecr_repository
aws_ecr_repository.named_test_resource: Refreshing state... [id=turbottest64716]
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
- resource "aws_ecr_repository" "named_test_resource" {
- arn                  = "arn:aws:ecr:us-east-1:632902152528:repository/turbottest64716" -> …
```

Add policy_std column to the aws_ecr_repository table. Closes #779

---

docs/tables/aws_iam_role.md

<details>
```
NA
```
</details>
<details>
```
> select
maintenance.name,
admin.name,
jsonb_pretty(maintenance_stmt),
jsonb_pretty(admin_stmt)
from
-- use the account to get the organization_id
aws_new.aws_account as a,
-- check any role as the maintenance-role
aws_new.aws_iam_role as maintenance,
-- Combine via join with any role as the "admin-role"
aws_new.aws_iam_role as admin,
jsonb_array_elements(maintenance.assume_role_policy_std -> 'Statement') as maintenance_stmt,
jsonb_array_elements(admin.assume_role_policy_std -> 'Statement') as admin_stmt
where
-- maintenance role can be assumed by any AWS principal
maintenance_stmt -> 'Principal' -> 'AWS' ? '*'
-- maintenance role principal must be in same account
and maintenance_stmt -> …
```

Add examples to IAM role docs. Closes #684

---

docs/tables/aws_cloudwatch_log_event.md

<details>
</details>
<details>
```
> select
log_group_name,
log_stream_name,
event_id,
timestamp,
ingestion_time,
message
from
aws_cloudwatch_log_event
where
log_group_name = 'raj-test-cis-4.2' and filter = '{ ($.eventName = AuthorizeSecurityGroupIngress) || ($.eventName = AuthorizeSecurityGroupEgress) || ($.eventName = RevokeSecurityGroupIngress) || ($.eventName = RevokeSecurityGroupEgress) || ($.eventName = CreateSecurityGroup) || ($.eventName = DeleteSecurityGroup) }'
and region='us-east-1'
and timestamp >= now() - interval '1 hour'
+------------------+-------------------------------------+----------------------------------------------------------+----------------------+----------------------+-------------------------------------------- …
```

Add filter example queries Closes #744

---

aws-test/tests/aws_lambda_alias/query.sql
aws-test/tests/aws_lambda_alias/test-get-call-query.sql
aws-test/tests/aws_lambda_alias/test-list-call-query.sql
aws/table_aws_lambda_alias.go

<details>
```
SETUP: tests/aws_lambda_alias []
PRETEST: tests/aws_lambda_alias
TEST: tests/aws_lambda_alias
+ create
+ output_md5          = (known after apply)
+ output_path         = "/private/var/folders/3j/6ybdbkm51c3449psm55pjsg00000gp/T/tests/aws_lambda_alias/terraform/test/../../test.zip"
+ output_sha          = (known after apply)
+ output_size         = (known after apply)
+ source_file         = …
```

Fix GET request for table aws_lambda_alias. Closes #777

---

aws/table_aws_dax_cluster.go

<details>
```
> select
cluster_name,
description,
active_nodes,
iam_role_arn,
status,
region
from
aws_dax_cluster;
+--------------+-------------+--------------+-----------------------------------------------------------+-----------+-----------+
| cluster_name | description | active_nodes | iam_role_arn                                              | status    | region    |
+--------------+-------------+--------------+-----------------------------------------------------------+-----------+-----------+
| test         | <null>      | 1            | arn:aws:iam::533793682495:role/service-role/DAXtoDynamoDB | available | us-east-1 |
+--------------+-------------+--------------+-----------------------------------------------------------+-----------+-----------+
> …
```

Handle InvalidParameterValueException  and ClusterNotFoundFault exceptions in aws_dax_cluster table. Fixes #782

---

aws/table_aws_ec2_application_load_balancer.go

<details>
```
SETUP: tests/aws_ec2_application_load_balancer []
PRETEST: tests/aws_ec2_application_load_balancer
TEST: tests/aws_ec2_application_load_balancer
+ create
+ resource "aws_internet_gateway" "igw" {
+ arn      = (known after apply)
+ id       = (known after apply)
+ owner_id = (known after apply)
+ tags_all = (known after apply)
+ vpc_id   = (known after apply)
}
+ resource "aws_lb" "named_test_resource" {
+ arn                        = (known after apply)
+ arn_suffix                 = (known after apply)
+ dns_name                   = (known after …
```

Handle ValidationError in get call for aws_ec2_application_load_balancer table.

---

aws/common_columns.go

this is very verbose in the logs (when running controls): 
```
2021-11-22T21:48:19.471Z [TRACE] steampipe-plugin-aws.plugin: [TRACE] getCommonColumns: region=global
2021-11-22T21:48:19.471Z [TRACE] steampipe-plugin-aws.plugin: [TRACE] getCommonColumns: region=global
2021-11-22T21:48:19.471Z [TRACE] steampipe-plugin-aws.plugin: [TRACE] getCommonColumns: region=global
2021-11-22T21:48:19.471Z [TRACE] steampipe-plugin-aws.plugin: [TRACE] getCommonColumns: region=global
2021-11-22T21:48:19.471Z [TRACE] steampipe-plugin-aws.plugin: [TRACE] getCommonColumns: region=global
2021-11-22T21:48:19.471Z [TRACE] steampipe-plugin-aws.plugin: [TRACE] getCommonColumns: region=global
2021-11-22T21:48:19.471Z [TRACE] steampipe-plugin-aws.plugin: [TRACE] getCommonColumns: region=global …
```

remove verbose logging

---

aws/utils.go

<details>
#invalid UTF-8
```
> select instance_id,user_data from aws_ec2_instance where instance_id = 'i-0319a7264d4208b4a'
+---------------------+----------------------------------------------------------------------------------------------------------------------+
| instance_id         | user_data                                                                                                            |
+---------------------+----------------------------------------------------------------------------------------------------------------------+
| i-0319a7264d4208b4a | bmFu5yBFc2FzbGFyICAgIHwKfCAgICAgICAgICAgICAgICAgICAgIHwgxLBuYW6nIEVzYXNsYXLEIHwKfCAgICAgICAgICAgICAgICAgICAgIHwgICA= |
+---------------------+------------------------------------------------------ …
```

Handle invalid UTF-8 user data in aws_ec2_instance table

---

aws/table_aws_config_rule.go
docs/tables/aws_config_rule.md

<details>
```
SETUP: tests/aws_config_rule []
PRETEST: tests/aws_config_rule
TEST: tests/aws_config_rule
aws_config_config_rule.named_test_resource: Creating...
aws_config_config_rule.named_test_resource: Creation complete after 3s [id=turbottest56118]
The null_data_source was historically …
```

Add compliant status information for config rules in aws_config_rule table closes #816

---

docs/tables/aws_rds_db_instance.md

<details>
```
NA
```
</details>
<details>
```
with db_parameter_group as (
select
name as db_parameter_group_name,
pg ->> 'ParameterName' as parameter_name,
pg ->> 'ParameterValue' as parameter_value
from
aws_rds_db_parameter_group,
jsonb_array_elements(parameters) as pg
where
pg ->> 'ParameterName' like 'rds.force_ssl'
and name not like 'default.%'
),
rds_associated_parameter_group as (
select
db_instance_identifier as db_instance_identifier,
arn,
pg ->> 'DBParameterGroupName' as DBParameterGroupName
from
aws_rds_db_instance,
jsonb_array_elements(db_parameter_groups) as pg
where
engine like 'sqlserve%'
)
select
rds.db_instance_identifier as name,
rds.DBParameterGroupName,
parameter_name,
parameter_value
from …
```

Add example query for aws_rds_db_instance. Closes #805

---

aws/table_aws_vpc_security_group_rule.go
aws/utils.go

<details>
```
> select group_name, group_id, ip_protocol, prefix_list_id from aws_vpc_security_group_rule where group_id = 'sg-005daf92f7db5ac15'
+------------+----------------------+-------------+----------------+
| group_name | group_id             | ip_protocol | prefix_list_id |
+------------+----------------------+-------------+----------------+
| db_pair    | sg-005daf92f7db5ac15 | tcp         | <null>         |
| db_pair    | sg-005daf92f7db5ac15 | tcp         | <null>         |
| db_pair    | sg-005daf92f7db5ac15 | icmp        | pl-02cd2c6b    |
| db_pair    | sg-005daf92f7db5ac15 | tcp         | <null>         |
| db_pair    | sg-005daf92f7db5ac15 | tcp         | <null>         |
| db_pair    | sg-005daf92f7db5ac15 | tcp         | <null>         |
| …
```

Add column `prefix_list_id` to `aws_vpc_security_group_rule` table

---

aws/table_aws_codebuild_project.go
docs/tables/aws_codebuild_project.md

<details>
```
SETUP: tests/aws_codebuild_project []
PRETEST: tests/aws_codebuild_project
TEST: tests/aws_codebuild_project
aws_iam_role.test_role: Creating...
aws_s3_bucket.test_bucket: Creating...
aws_s3_bucket.test_bucket: Still creating... [10s elapsed]
aws_iam_role.test_role: Still …
```

Add project_visibility column to aws_codebuild_project table closes #818

---

aws/table_aws_workspaces_workspace.go

<details>
```
Before - 
select * from aws_workspaces_workspace
Error: RequestError: send request failed
caused by: Post "https://workspaces.us-east-2.amazonaws.com/": dial tcp: lookup workspaces.us-east-2.amazonaws.com: no such host
After the fix -
> select * from aws_workspaces_workspace
+--------------+------+-----+-----------+--------------+-------+------------+---------------+------------+--------------------------------+-----------+-----------+--------------------------------+------
| workspace_id | name | arn | bundle_id | directory_id | state | error_code | error_message | ip_address | root_volume_encryption_enabled | subnet_id | user_name | user_volume_encryption_enabled | volum
+--------------+------+-----+-----------+--------------+-------+------------+ …
```

Workspaces "no such host" errrors closes #830

---

aws/table_aws_ebs_snapshot.go

<details>
```
aws_ebs_volume.test_volume: Creating...
aws_ebs_volume.test_volume: Still creating... [10s elapsed]
aws_ebs_volume.test_volume: Creation complete after 15s [id=vol-0e3ac6780e5445870]
aws_ebs_snapshot.named_test_resource: Creating...
aws_ebs_snapshot.named_test_resource: Creation complete after 4s [id=snap-0b466018061d8ae5e]
aws_snapshot_create_volume_permission.example_perm: Creating...
aws_snapshot_create_volume_permission.example_perm: Still creating... [10s elapsed]
aws_snapshot_create_volume_permission.example_perm: Creation complete after 14s [id=snap-0b466018061d8ae5e-388460667113]
The null_data_source was …
```

Queries against aws_ebs_snapshot are not returning results for aws ap-southeast-2 region closes #831

---

aws/table_aws_workspaces_workspace.go

<details>
```
select * from aws_workspaces_workspace
+--------------+------+-----+-----------+--------------+-------+------------+---------------+------------+--------------------------------+-----------+-----------+--------------------------------+-----------------------+----------------
| workspace_id | name | arn | bundle_id | directory_id | state | error_code | error_message | ip_address | root_volume_encryption_enabled | subnet_id | user_name | user_volume_encryption_enabled | volume_encryption_key | modification_st
+--------------+------+-----+-----------+--------------+-------+------------+---------------+------------+--------------------------------+-----------+-----------+--------------------------------+-----------------------+-----------
``` …

Fix the "no such host" error in the aws_workspaces_workspace table closes #830

---

aws/table_aws_ebs_snapshot.go

<details>
```
aws_ebs_volume.test_volume: Creating...
aws_ebs_volume.test_volume: Still creating... [10s elapsed]
aws_ebs_volume.test_volume: Creation complete after 15s [id=vol-0e3ac6780e5445870]
aws_ebs_snapshot.named_test_resource: Creating...
aws_ebs_snapshot.named_test_resource: Creation complete after 4s [id=snap-0b466018061d8ae5e]
aws_snapshot_create_volume_permission.example_perm: Creating...
aws_snapshot_create_volume_permission.example_perm: Still creating... [10s elapsed]
aws_snapshot_create_volume_permission.example_perm: Creation complete after 14s [id=snap-0b466018061d8ae5e-388460667113]
The null_data_source was …
```

Fix aws_ebs_snapshot table to use owner_id as an optional key qual

---

aws/table_aws_accessanalyzer_analyzer.go
aws/table_aws_acm_certificate.go
aws/table_aws_api_gateway_api_key.go
aws/table_aws_api_gateway_rest_api.go
aws/table_aws_api_gateway_usage_plan.go
aws/table_aws_appautoscaling_target.go
aws/table_aws_auditmanager_assessment.go
aws/table_aws_auditmanager_evidence.go
aws/table_aws_auditmanager_evidence_folder.go
aws/table_aws_backup_plan.go
aws/table_aws_backup_protected_resource.go
aws/table_aws_backup_recovery_point.go
aws/table_aws_backup_selection.go
aws/table_aws_backup_vault.go
aws/table_aws_cloudfront_cache_policy.go
aws/table_aws_cloudfront_distribution.go
aws/table_aws_cloudfront_origin_access_identity.go
aws/table_aws_cloudfront_origin_request_policy.go
aws/table_aws_cloudwatch_log_group.go
aws/table_aws_cloudwatch_log_metric_filter.go
aws/table_aws_cloudwatch_log_stream.go
aws/table_aws_codepipeline_pipeline.go
aws/table_aws_dax_cluster.go
aws/table_aws_dms_replication_instance.go
aws/table_aws_dynamodb_backup.go
aws/table_aws_dynamodb_global_table.go
aws/table_aws_dynamodb_table.go

<details>
```
N/A
```
</details>
<details>
```
select * from aws_accessanalyzer_analyzer limit 0
+------+-----+--------+------+------------+------------------------+---------------------------+---------------+----------+-------+------+------+-----------+--------+------------+
| name | arn | status | type | created_at | last_resource_analyzed | last_resource_analyzed_at | status_reason | findings | title | tags | akas | partition | region | account_id |
+------+-----+--------+------+------------+------------------------+---------------------------+---------------+----------+-------+------+------+-----------+--------+------------+
+------+-----+--------+------+------------+------------------------+---------------------------+---------------+ …
```

Update maximum result limit as per api calls closes #828

---

aws/table_aws_vpc_security_group_rule.go

<details>
```
> select group_id, group_name from aws_vpc_security_group_rule where security_group_rule_id = 'sgr-04c0d1145bd2ac638'
+----------------------+------------+
| group_id             | group_name |
+----------------------+------------+
| sg-0a6ab4a4ec00dda70 | <null>     |
+----------------------+------------+
> select group_id, group_name from aws_vpc_security_group_rule
+----------------------+------------------------------------------------------------------------------------------------------+
| group_id             | group_name                                                                                           |
+----------------------+------------------------------------------------------------------------------------------------------+
| …
```

Handle NotFound error for InvalidGroup in getSecurityGroupDetails Hydrate call for aws_vpc_security_group_rule table. Fixes #874

---

aws/cloudwatch_metric.go
aws/cost_explorer.go
aws/table_aws_api_gateway_api_authorizer.go
aws/table_aws_api_gatewayv2_stage.go
aws/table_aws_auditmanager_control.go
aws/table_aws_auditmanager_framework.go
aws/table_aws_backup_recovery_point.go
aws/table_aws_backup_vault.go
aws/table_aws_cloudfront_cache_policy.go
aws/table_aws_cloudtrail_trail.go
aws/table_aws_cloudtrail_trail_event.go
aws/table_aws_cloudwatch_log_event.go
aws/table_aws_cloudwatch_log_resource_policy.go
aws/table_aws_config_conformance_pack.go
aws/table_aws_directory_service_directory.go
aws/table_aws_ec2_reserved_instance.go
aws/table_aws_ecs_container_instance.go
aws/table_aws_ecs_service.go
aws/table_aws_guardduty_finding.go
aws/table_aws_iam_action.go
aws/table_aws_kinesis_video_stream.go
aws/table_aws_lambda_alias.go
aws/table_aws_lambda_function.go
aws/table_aws_serverlessapplicationrepository_application.go
aws/table_aws_ssm_patch_baseline.go
aws/table_aws_vpc_security_group_rule.go

**Table affected by the changes**
- aws_api_gateway_api_authorizer
- aws_api_gatewayv2_stage
- aws_auditmanager_control
- aws_auditmanager_framework
- aws_backup_recovery_point
- aws_backup_vault
- aws_cloudfront_cache_policy
- aws_cloudtrail_trail
- aws_cloudtrail_trail_event
- aws_cloudwatch_log_event
- aws_cloudwatch_log_resource_policy
- aws_config_conformance_pack
- aws_directory_service_directory
- aws_ec2_reserved_instance
- aws_ecs_container_instance
- aws_ecs_service
- aws_guardduty_finding
- aws_iam_action
- aws_kinesis_video_stream
- aws_lambda_alias
- aws_lambda_function
- aws_serverlessapplicationrepository_application
- aws_ssm_patch_baseline
- aws_vpc_security_group_rule
<details>
```
> select * from aws_backup_vault …
```

Add missing limit, context cancel logic in tables closes #895

---

aws/plugin.go
aws/table_aws_cloudwatch_metric.go
docs/tables/aws_cloudwatch_metric.md

<details>
```
N/A
```
</details>
<details>
```
> select
name,
namespace,
dimensions
from
aws_cloudwatch_metric
where
namespace = 'AWS/EBS' limit 5;
+-------------------+-----------+-------------------------------------------------------+
| name              | namespace | dimensions                                            |
+-------------------+-----------+-------------------------------------------------------+
| VolumeQueueLength | AWS/EBS   | [{"Name":"VolumeId","Value":"vol-0e93726d7a5ef5954"}] |
| VolumeReadOps     | AWS/EBS   | [{"Name":"VolumeId","Value":"vol-0e93726d7a5ef5954"}] |
| VolumeReadBytes   | AWS/EBS   | [{"Name":"VolumeId","Value":"vol-0e93726d7a5ef5954"}] |
| VolumeWriteOps    | AWS/EBS   | …
```

Add table aws_cloudwatch_metric closes #872

---

aws/table_aws_codecommit_repository.go

<details>
```
SETUP: tests/aws_codecommit_repository []
PRETEST: tests/aws_codecommit_repository
TEST: tests/aws_codecommit_repository
aws_codecommit_repository.named_test_resource: Creating...
aws_codecommit_repository.named_test_resource: Creation complete after 4s [id=turbottest53880] …
```

Fix aws_codecommit_repository table list call failing for regions with more than 25 repos due to API limitations. Fixes #891

---

aws/table_aws_iam_access_advisor.go

<details>
```
SETUP: tests/aws_iam_access_advisor []
PRETEST: tests/aws_iam_access_advisor
TEST: tests/aws_iam_access_advisor
+ create
+ resource "null_resource" "named_test_resource" {
+ id = (known after apply)
}
Plan: 1 to add, 0 to change, 0 to destroy.
Changes to Outputs:
+ aws_account   = "533793682495"
+ aws_partition = "aws"
+ aws_region    = "us-east-1"
+ user_arn      = "arn:aws:iam::533793682495:user/turbot/account/federated/sourav"
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'... …
```

Add check for account id and handle InvalidParameter exception in aws_iam_access_advisor table. Fixes #900

---

aws/table_aws_ecs_service.go

<details>
```
SETUP: tests/aws_ecs_service []
PRETEST: tests/aws_ecs_service
TEST: tests/aws_ecs_service
+ create
+ resource "aws_ecs_cluster" "named_test_resource" {
+ arn                = (known after apply)
+ capacity_providers = (known after apply)
+ id                 = (known after apply)
+ name               = "turbottest67666"
+ tags_all           = (known after apply)
+ default_capacity_provider_strategy {
+ base              = (known after apply)
+ capacity_provider = (known after apply)
+ weight            = (known after apply)
}
+ setting {
+ name  = …
```

Update MaxResults to default value 10 for ListServices API in aws_ecs_service table. Fixes #903

---

aws-test/tests/aws_auditmanager_assessment/variables.tf
aws-test/tests/aws_cloudfront_distribution/variables.tf
aws-test/tests/aws_codebuild_project/variables.tf
aws-test/tests/aws_codepipeline_pipeline/vatiable.tf
aws-test/tests/aws_dax_cluster/variables.tf
aws-test/tests/aws_directory_service_directory/variables.tf
aws-test/tests/aws_dms_replication_instance/test-get-expected.json
aws-test/tests/aws_dms_replication_instance/test-hydrate-expected.json
aws-test/tests/aws_ec2_ami/test-hydrate-expected.json
aws-test/tests/aws_ecs_cluster/test-list-expected.json
aws-test/tests/aws_emr_instance_group/variables.tf
aws-test/tests/aws_iam_access_advisor/test-list-expected.json
aws-test/tests/aws_iam_access_advisor/test-list-query.sql
aws-test/tests/aws_kinesis_firehose_delivery_stream/variables.tf
aws-test/tests/aws_macie2_classification_job/variables.tf
aws-test/tests/aws_rds_db_instance/test-get-expected.json
aws-test/tests/aws_rds_db_instance/test-hydrate-expected.json
aws-test/tests/aws_s3_bucket/variables.tf
aws-test/tests/aws_wafv2_web_acl/variables.tf
aws/table_aws_ec2_gateway_load_balancer.go
aws/table_aws_ec2_load_balancer_listener.go
aws/table_aws_ec2_network_load_balancer.go

<details>
```
SETUP: tests/aws_ec2_gateway_load_balancer []
PRETEST: tests/aws_ec2_gateway_load_balancer
TEST: tests/aws_ec2_gateway_load_balancer
aws_vpc.my_vpc: Creation complete after 4s [id=vpc-0dbf1458d5e0f5be7]
aws_internet_gateway.igw: Creating...
aws_internet_gateway.igw: Creation …
```

Fix the integration tests issues

---

aws/cost_explorer.go
aws/table_aws_cost_by_service_daily.go
aws/table_aws_cost_by_service_monthly.go
aws/table_aws_cost_by_service_usage_type_daily.go
aws/table_aws_cost_by_service_usage_type_monthly.go

<details>
```
> select * from morales_aws.aws_cost_by_service_usage_type_monthly where service = 'Amazon Elastic Compute Cloud - Compute' and usage_type = 'BoxUsage:t2.micro'
+----------------------------------------+-------------------+---------------------------+---------------------------+-----------+---------------------+-------------------+-----------------------+---------------------+---------------------------+-------------------------+-----------------------+---------------------+---------------------------+-------------------------+-----------------------+---------------------+-------------------------+-----------------------+-----------+--------+--------------+-----------------------------------+
| service                                | usage_type …
```

Add optional qual for list call for `aws_cost_by_service_*` and `aws_cost_by_service_usage_type_*` tables

---

aws/table_aws_vpc_security_group_rule.go

<details>
```
N/A
```
</details>
<details>
**Before Fix**
```
> select title, type, is_egress from aws_vpc_security_group_rule
+------------------------------------------------------------+---------+-----------+
| title                                                      | type    | is_egress |
+------------------------------------------------------------+---------+-----------+
| sgr-0177bd56f94cdd510_egress_tcp_22_22_0.0.0.0/0           | ingress | false     |
| sgr-0c364b3d2515d41c4_ingress_-1_-1_-1_0.0.0.0/0           | egress  | true      |
| sgr-0a91a6fe5233dedf4_ingress_-1_-1_-1_0.0.0.0/0           | egress  | true      |
| sgr-017d623c4abae77d7_ingress_-1_-1_-1_0.0.0.0/0           | egress  | true      |
| …
```

Fix title column value in aws_vpc_security_group_rule table closes #923

---

aws/table_aws_sqs_queue.go
docs/tables/aws_sqs_queue.md

<details>
```
SETUP: tests/aws_sqs_queue []
PRETEST: tests/aws_sqs_queue
TEST: tests/aws_sqs_queue
aws_sqs_queue.named_test_resource: Creating...
aws_sns_topic.named_test_resource: Creating...
aws_sns_topic.named_test_resource: Creation complete after 3s [id=arn:aws:sns:us-east-1:632902152528:turbottest92319] …
```

Add support for Amazon SQS key (SSE-SQS) in aws_sqs_queue table closes #921

---

aws/table_aws_ebs_snapshot.go
aws/table_aws_ebs_volume.go
aws/table_aws_ec2_instance.go
aws/utils.go

<details>
```
SETUP: tests/aws_ebs_volume []
PRETEST: tests/aws_ebs_volume
TEST: tests/aws_ebs_volume
aws_ebs_volume.named_test_resource: Creating...
aws_ebs_volume.named_test_resource: Still creating... [10s elapsed]
aws_ebs_volume.named_test_resource: Creation complete after 14s [id=vol-06ad0e5a6ea25412b]
Warning: …
```

Fix InvalidParameterValue exception in aws_ebs_volume table closes #918

---

aws/table_aws_dynamodb_table.go

<details>
```
Outputs:
account_id = "533793682495"
aws_partition = "aws"
aws_region = "us-east-1"
resource_aka = "arn:aws:dynamodb:us-east-1:533793682495:table/turbottest75877"
resource_name = "turbottest75877"
Running SQL query: test-get-query.sql
[
{
"arn": "arn:aws:dynamodb:us-east-1:533793682495:table/turbottest75877",
"name": "turbottest75877"
}
]
✔ PASSED
Running SQL query: test-hydrate-query.sql
[
{
"continuous_backups_status": "ENABLED",
"point_in_time_recovery_description": {
"EarliestRestorableDateTime": null,
"LatestRestorableDateTime": null,
"PointInTimeRecoveryStatus": "DISABLED"
}
}
]
✔ PASSED
Running SQL query: test-list-query.sql
[
{
"arn": "arn:aws:dynamodb:us-east-1:533793682495:table/turbottest75877",
"attribute_definitions": [
{
"AttributeName": …
```

Added support to fetch dynamoDB Table class attribute in aws_dynamodb_table. Closes #935

---

aws/table_aws_cost_by_service_daily.go
aws/table_aws_cost_by_service_monthly.go
aws/table_aws_cost_by_service_usage_type_daily.go
aws/table_aws_cost_by_service_usage_type_monthly.go
aws/table_aws_cost_forecast_daily.go
aws/table_aws_cost_forecast_monthly.go

<details>
```
N/A
```
</details>
<details>
```
> select
service,
period_start,
blended_cost_amount::numeric::money,
unblended_cost_amount::numeric::money,
amortized_cost_amount::numeric::money,
net_unblended_cost_amount::numeric::money,
net_amortized_cost_amount::numeric::money
from 
aws_cost_by_service_daily
order by
service,
period_start limit 10;
+----------------+---------------------------+---------------------+-----------------------+-----------------------+---------------------------+---------------------------+
| service        | period_start              | blended_cost_amount | unblended_cost_amount | amortized_cost_amount | net_unblended_cost_amount | net_amortized_cost_amount | …
```

Update aws_cost_* tables with optional quals closes #916

---

aws/plugin.go
aws/table_aws_cost_by_record_type_daily.go
aws/table_aws_cost_by_record_type_monthly.go
docs/tables/aws_cost_by_record_type_daily.md
docs/tables/aws_cost_by_record_type_monthly.md

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_cost_by_record_type_monthly;
+-------------------+-----------------+---------------------------+---------------------------+-----------+---------------------+-------------------+-----------------------+---------------------+-------
| linked_account_id | record_type     | period_start              | period_end                | estimated | blended_cost_amount | blended_cost_unit | unblended_cost_amount | unblended_cost_unit | net_un
+-------------------+-----------------+---------------------------+---------------------------+-----------+---------------------+-------------------+-----------------------+---------------------+-------
| 632902152528      | Tax             | …
```

Add table aws_cost_by_record_type_* closes #948 #949

---

aws/table_aws_elastic_beanstalk_environment.go

<details>
```
```
</details>
<details>
```
> select environment_name, date_created from aws.aws_elastic_beanstalk_environment
+------------------+---------------------------+
| environment_name | date_created              |
+------------------+---------------------------+
| Test1-env        | 2022-04-29T11:55:18+05:30 |
+------------------+---------------------------+
```
</details>

Update the column name date-created to date_created in table aws_elastic_beanstalk_environment closes #964

---

aws/table_aws_lambda_function.go
aws/table_aws_lambda_version.go

<details>
```
```
</details>
```
$ steampipe query "select environment_variables from aws_lambda_function where name = 'example-hello-world'"
+---------------------------------------------------------+
| environment_variables                                   |
+---------------------------------------------------------+
| {"PG_SCHEMA":"example","SERVERLESS_REGION":"us-east-1"} |
+---------------------------------------------------------+
$ steampipe query "select environment_variables from aws_lambda_function where arn = 'arn:aws:lambda:us-east-1:000000000000:function:example-hello-world'"
+---------------------------------------------------------+
| environment_variables                                   | …
```

Add environment_variables column to aws_lambda_function and aws_lambda_version tables.

---

aws/table_aws_ec2_network_interface.go
docs/tables/aws_ec2_network_interface.md

<details>
```
```
</details>
<details>
```
> select
eni.network_interface_id,
vpc.vpc_id,
vpc.is_default,
vpc.cidr_block,
vpc.state,
vpc.region
from
aws_ec2_network_interface eni,
aws_vpc vpc
where 
eni.vpc_id = vpc.vpc_id limit 5;
+-----------------------+-----------------------+------------+-----------------+-----------+-----------+
| network_interface_id  | vpc_id                | is_default | cidr_block      | state     | region    |
+-----------------------+-----------------------+------------+-----------------+-----------+-----------+
| eni-0e9ca2e3ec4e4b090 | vpc-02067788fa317042e | false      | 10.114.190.0/26 | available | us-east-2 |
| eni-0ad70e5067b71ba87 | vpc-02067788fa317042e | false …
```

Add column vpc_id to aws_ec2_network_interface table Closes #988

---

aws-test/tests/aws_securityhub_standards_control/test-list-expected.json
aws-test/tests/aws_securityhub_standards_control/test-list-query.sql
aws-test/tests/aws_securityhub_standards_control/test-turbot-query.sql
aws/table_aws_securityhub_standards_control.go
docs/tables/aws_securityhub_standards_control.md

<details>
```
SETUP: tests/aws_securityhub_standards_control []
PRETEST: tests/aws_securityhub_standards_control
TEST: tests/aws_securityhub_standards_control
+ create
<= data "local_file" "control"  {
+ content        = (known after apply)
+ content_base64 = (known after apply)
+ filename       = "/private/var/folders/3j/6ybdbkm51c3449psm55pjsg00000gp/T/tests/aws_securityhub_standards_control/terraform/test/control.json"
+ id             = (known after apply)
}
+ resource "null_resource" "named_test_resource" {
+ id = (known after apply)
} …
```

Update column name standards_control_arn to arn in aws_securityhub_standards_control table. Closes #1026

---

aws/table_aws_directory_service_directory.go
docs/tables/aws_directory_service_directory.md

<details>
```
```
</details>
<details>
```
> select
name,
directory_id,
sd ->> 'ShareMethod' share_method,
sd ->> 'ShareStatus' share_status,
sd ->> 'SharedAccountId' shared_account_id,
sd ->> 'SharedDirectoryId' shared_directory_id
from
aws_directory_service_directory,
jsonb_array_elements(shared_directories) sd;
+----------------------+--------------+--------------+--------------+-------------------+---------------------+
| name                 | directory_id | share_method | share_status | shared_account_id | shared_directory_id |
+----------------------+--------------+--------------+--------------+-------------------+---------------------+
| turbot.steampipe.com | d-90674d92a6 | HANDSHAKE    | …
```

Add column shared_directories in table aws_directory_service_directory Closes #1020

---

aws/table_aws_securityhub_hub.go
docs/tables/aws_securityhub_hub.md

<details>
```
```
</details>
<details>
```sql
> select
hub_arn,
auto_enable_controls,
administrator_account ->> 'AccountId' as administrator_account_id,
administrator_account ->> 'InvitationId' as administrator_invitation_id,
administrator_account ->> 'InvitedAt' as administrator_invitation_time,
administrator_account ->> 'MemberStatus' as administrator_status
from
aws_securityhub_hub
where
administrator_account is not null;
+--------------------------------------------------------+----------------------+--------------------------+----------------------------------+-------------------------------+----------------------+
| hub_arn                                                | auto_enable_controls | …
```

Add column administrator_account to table aws_securityhub_hub Closes #1037

---

aws-test/tests/aws_cloudtrail_trail/variables.tf
aws/service.go
aws/table_aws_cloudtrail_trail.go

<details>
```
SETUP: tests/aws_cloudtrail_trail []
PRETEST: tests/aws_cloudtrail_trail
TEST: tests/aws_cloudtrail_trail
aws_s3_bucket.named_test_resource: Creating...
aws_s3_bucket.named_test_resource: Creation complete after 7s [id=turbottest82533]
aws_cloudtrail.named_test_resource: Creating... …
```

Fix is_logging column of the aws_cloudtrail_trail table returns null when value is 'true' in the AWS CLI closes #957

---

aws/connection_config.go
aws/service.go
config/aws.spc

Closes #1050.
<details>
```
```
</details>
<details>
```
```
</details>

Allow custom endpoint url configuration. Closes #1050

---

aws/table_aws_rds_db_cluster.go
aws/table_aws_rds_db_instance.go
docs/tables/aws_rds_db_cluster.md
docs/tables/aws_rds_db_instance.md

<details>
```
> select
actions ->> 'ResourceIdentifier' as db_instance_identifier,
details ->> 'Action' as action,
details ->> 'OptInStatus' as opt_in_status,
details ->> 'ForcedApplyDate' as forced_apply_date,
details ->> 'CurrentApplyDate' as current_apply_date,
details ->> 'AutoAppliedAfterDate' as auto_applied_after_date
from
aws_rds_db_instance,
jsonb_array_elements(pending_maintenance_actions) as actions,
jsonb_array_elements(actions -> 'PendingMaintenanceActionDetails') as details;
+-------------------------------------------------------+---------------+------------------+-------------------+----------------------+-------------------------+
| db_instance_identifier                                | action        | opt_in_status    | forced_apply_date | …
```

Add column pending_maintenance_actions to aws_rds_db_cluster and aws_rds_db_instance tables. Closes #1060

---

aws/table_aws_vpc_endpoint_service.go
docs/tables/aws_vpc_endpoint_service.md

<details>
```
SETUP: tests/aws_vpc_endpoint_service []
PRETEST: tests/aws_vpc_endpoint_service
TEST: tests/aws_vpc_endpoint_service
data.aws_region.primary: Read complete after 0s [id=us-west-2]
data.aws_caller_identity.current: Read complete after 2s [id=533793682495]
plan. Resource …
```

Add column vpc_endpoint_service_permissions to aws_vpc_endpoint_service table. Closes #1093

---

aws/table_aws_guardduty_member.go
aws/table_aws_media_store_container.go

<details>
```
SETUP: tests/aws_media_store_container []
PRETEST: tests/aws_media_store_container
TEST: tests/aws_media_store_container
data.aws_caller_identity.current: Read complete after 2s [id=**************]
plan. Resource …
```

Fix unsupported region issue in aws_media_store_container table. Fixes #1101

---

aws/table_aws_eks_identity_provider_config.go

<details>
```
SETUP: tests/aws_eks_identity_provider_config []
PRETEST: tests/aws_eks_identity_provider_config
TEST: tests/aws_eks_identity_provider_config
data.aws_region.primary: Read complete after 0s [id=us-west-1]
data.aws_caller_identity.current: Read complete after 1s [id=**************]
Terraform used the selected providers to generate the following …
```

Fix MaxResults parameter issue in list API for aws_eks_identity_provider_config table. Fixes #1100

---

aws/table_aws_route53_zone.go
docs/tables/aws_route53_zone.md

<details>
```
SETUP: tests/aws_route53_zone []
PRETEST: tests/aws_route53_zone
TEST: tests/aws_route53_zone
data.aws_iam_policy_document.route53-query-logging-policy: Refreshing state...
aws_route53_zone.named_test_resource: Creating...
aws_kms_key.example: Creating... …
```

Add column vpcs in table aws_route53_zone closes #1081

---

aws-test/tests/aws_auditmanager_assessment/posttest-variables.tf
aws-test/tests/aws_auditmanager_assessment/variables.tf
aws-test/tests/aws_auditmanager_control/test-list-expected.json
aws-test/tests/aws_auditmanager_control/test-list-query.sql
aws-test/tests/aws_auditmanager_control/variables.tf
aws-test/tests/aws_auditmanager_framework/test-turbot-query.sql
aws/table_aws_auditmanager_assessment.go
aws/table_aws_auditmanager_control.go
aws/table_aws_auditmanager_evidence.go
aws/table_aws_auditmanager_evidence_folder.go
aws/table_aws_auditmanager_framework.go

<details>
```
SETUP: tests/aws_auditmanager_assessment []
PRETEST: tests/aws_auditmanager_assessment
TEST: tests/aws_auditmanager_assessment
data.aws_caller_identity.current: Read complete after 1s [id=533793682495]
plan. …
```

Fix no such host issue and complete audit manager setup issue in aws_auditmanager_* tables. Fixes#1107

---

aws/table_aws_backup_framework.go

<details>
```
SETUP: tests/aws_backup_framework []
PRETEST: tests/aws_backup_framework
TEST: tests/aws_backup_framework
aws_backup_framework.named_test_resource: Refreshing state... [id=turbottest51343]
data.aws_caller_identity.current: Read complete after 1s [id=**************]
Terraform used the …
```

Handle unsupported region issue in aws_backup_framework table. Fixes #1123

---

aws/table_aws_wafv2_web_acl.go
docs/tables/aws_wafv2_web_acl.md

<details>
```
> select
name,
id,
jsonb_pretty(associated_resources) as associated_resources,
region
from
aws_wafv2_web_acl;
+-------+--------------------------------------+--------------------------------------------------------------------------------------------------+-----------+
| name  | id                                   | associated_resources                                                                             | region    |
+-------+--------------------------------------+--------------------------------------------------------------------------------------------------+-----------+
| test  | 0f0d9a1e-1fa7-4dc6-9127-6fc9a1389c36 | [                                                                                                | us-east-1 |
| …
```

Add column associated_resources in aws_wafv2_web_acl table. Closes #1157

---

aws/table_aws_ec2_classic_load_balancer.go
docs/tables/aws_ec2_classic_load_balancer.md

<details>
```
> select name, health_check_target from aws_ec2_classic_load_balancer
+------+---------------------+
| name | health_check_target |
+------+---------------------+
| test | HTTP:80/index.html  |
+------+---------------------+
```
</details>

Fix column health_check_target in aws_ec2_classic_load_balancer table. Fixes #1178

---

aws/table_aws_neptune_db_cluster.go
aws/table_aws_rds_db_cluster.go
docs/tables/aws_neptune_db_cluster.md
docs/tables/aws_rds_db_cluster.md

<details>
```
```
</details>
<details>
```
> select db_cluster_identifier, engine from aws_neptune_db_cluster
+-----------------------+---------+
| db_cluster_identifier | engine  |
+-----------------------+---------+
| database-1            | neptune |
+-----------------------+---------+
```
</details>

Add better engine filtering in `aws_neptune_db_cluster` and `aws_rds_db_cluster` tables

---

aws/table_aws_neptune_db_cluster.go
aws/table_aws_rds_db_cluster.go
docs/tables/aws_neptune_db_cluster.md
docs/tables/aws_rds_db_cluster.md

<details>
```sql
select db_cluster_identifier, engine from aws_rds_db_cluster;
+-----------------------+--------+
| db_cluster_identifier | engine |
+-----------------------+--------+
| database-3            | mysql  |
+-----------------------+--------+
```
</details>

Fix rds cluster table to list mysql and postgres engine type clusters. Fixes #1211

---

aws/table_aws_eventbridge_bus.go
aws/table_aws_eventbridge_rule.go

<details>
```
./tint.js tests/aws_eventbridge_rule 
SETUP: tests/aws_eventbridge_rule []
PRETEST: tests/aws_eventbridge_rule
TEST: tests/aws_eventbridge_rule
data.aws_caller_identity.current: Read complete after 1s …
```

Fix aws_eventbridge_rule table to list rules from the all eventbridge buses. Fixes #1212

---

aws/table_aws_ec2_network_interface.go

<details>
```
➜  aws-test git:(ec2_eni) ✗ ./tint.js aws_ec2_network_interface              
SETUP: tests/aws_ec2_network_interface []
PRETEST: tests/aws_ec2_network_interface
TEST: tests/aws_ec2_network_interface …
```

Add subnet_id column in table aws_ec2_network_interface #1215

---

aws/table_aws_lambda_function.go

<details>
```
data.aws_caller_identity.current: Read complete after 1s [id=278493688375] …
```

Add column file_system_configs to aws_lambda_function table. closes #1199

---

aws/table_aws_emr_instance_group.go

<details>
```
SETUP: tests/aws_emr_instance_group []
PRETEST: tests/aws_emr_instance_group
TEST: tests/aws_emr_instance_group
data.aws_caller_identity.current: Read complete after 2s [id=533793682495]
plan. Resource actions are …
```

Fix InvalidRequestException in aws_emr_instance_group table. Fixes #1222

---

aws/table_aws_glacier_vault.go
docs/tables/aws_glacier_vault.md

<details>
```
Outputs:
resource_aka = "arn:aws:glacier:us-east-1:111122223333:vaults/turbottest40108"
resource_id = "turbottest40108"
resource_name = "turbottest40108"
Running SQL query: test-get-query.sql
[
{
"tags_src": {
"name": "turbottest40108"
},
"title": "turbottest40108",
"vault_name": "turbottest40108"
}
]
✔ PASSED
Running SQL query: test-hydrate-query.sql
[
{
"akas": [
"arn:aws:glacier:us-east-1:111122223333:vaults/turbottest40108"
],
"policy": {
"Statement": [
{
"Action": [
"glacier:InitiateJob",
"glacier:GetJobOutput"
],
"Effect": "Allow",
"Principal": "*",
"Resource": "arn:aws:glacier:us-east-1:111122223333:vaults/turbottest40108",
"Sid": "__default_policy_ID"
}
],
"Version": "2012-10-17"
},
"tags": {
"name": "turbottest40108"
},
"title": …
```

Add column `vault_notification_config` to table `aws_glacier_vault` Closes #1230

---

aws/table_aws_api_gatewayv2_api.go
docs/tables/aws_api_gatewayv2_api.md

<details>
```
Outputs:
api_endpoint = "https://t36iak6iz0.execute-api.us-east-1.amazonaws.com"
resource_aka = "arn:aws:apigateway:us-east-1::/apis/t36iak6iz0"
resource_id = "t36iak6iz0"
resource_name = "turbottest55990"
Running SQL query: query.sql
[
{
"name": "turbottest55990"
}
]
✔ PASSED
Running SQL query: test-get-query.sql
[
{
"akas": [
"arn:aws:apigateway:us-east-1::/apis/t36iak6iz0"
],
"tags": {
"name": "turbottest55990"
},
"title": "turbottest55990"
}
]
✔ PASSED
Running SQL query: test-list-query.sql
[
{
"akas": [
"arn:aws:apigateway:us-east-1::/apis/t36iak6iz0"
],
"api_endpoint": "https://t36iak6iz0.execute-api.us-east-1.amazonaws.com",
"api_id": "t36iak6iz0",
"name": "turbottest55990",
"tags": {
"name": "turbottest55990"
},
"title": "turbottest55990"
}
] …
```

Add column `disable_execute_api_endpoint` to table `aws_api_gatewayv2_api` Closes #1241

---

aws/table_aws_ec2_application_load_balancer.go

<details>
```
SETUP: tests/aws_ec2_application_load_balancer []
PRETEST: tests/aws_ec2_application_load_balancer
TEST: tests/aws_ec2_application_load_balancer
data.aws_region.primary: Read complete after 0s [id=us-west-2]
data.aws_caller_identity.current: Read complete after 1s …
```

Getting gateway load balancer information in aws_ec2_application_load_balancer table closes #1269

---

aws/multi_region.go
aws/service.go

Tested for below scenarios and it is working fine.
```
connection "aws" {
plugin = "aws"
regions = ["us-east-1"]
}
```

Fix query failure for any new regions released by AWS when the config uses `wilcards` for regions in steampipe connection config 

---

aws-test/tests/aws_kms_key/test-turbot-expected.json
aws/table_aws_kms_key.go
docs/tables/aws_kms_key.md

<details>
```
Outputs:
account_id = "111122223333"
alias_arn = "arn:aws:kms:us-east-1:111122223333:alias/my-key-alias_turbottest40147"
aws_partition = "aws"
key_title = "alias/my-key-alias_turbottest40147"
resource_aka = "arn:aws:kms:us-east-1:111122223333:key/99e97abd-3222-4082-b7d7-400db3bb21b6"
resource_id = "99e97abd-3222-4082-b7d7-400db3bb21b6"
resource_name = "turbottest40147"
Running SQL query: test-get-query.sql
[
{
"id": "99e97abd-3222-4082-b7d7-400db3bb21b6"
}
]
✔ PASSED
Running SQL query: test-hydrate-query.sql
[
{
"alias_arn": "arn:aws:kms:us-east-1:111122223333:alias/my-key-alias_turbottest40147",
"alias_name": "alias/my-key-alias_turbottest40147",
"alias_target_key_id": "99e97abd-3222-4082-b7d7-400db3bb21b6",
"key_manager": "CUSTOMER", …
```

Update `aws_kms_key` table `title` column to use the first alias if available Closes #1245

---

aws/table_aws_lambda_function.go

<details>
```
data.aws_caller_identity.current: Read complete after 1s [id=***********]
plan. Resource actions are indicated …
```

Add Code column in the aws_lambda_function table. Closes #1292

---

aws/table_aws_ec2_transit_gateway.go
aws/table_aws_ec2_transit_gateway_route.go
aws/table_aws_ec2_transit_gateway_route_table.go
aws/table_aws_ec2_transit_gateway_vpc_attachment.go

<details>
```
> select transit_gateway_id from aws_ec2_transit_gateway where region = 'me-central-1'
+--------------------+
| transit_gateway_id |
+--------------------+
+--------------------+
> select transit_gateway_route_table_id from aws_ec2_transit_gateway_route where region = 'me-central-1'
+--------------------------------+
| transit_gateway_route_table_id |
+--------------------------------+
+--------------------------------+
> select transit_gateway_route_table_id from aws_ec2_transit_gateway_route_table where region = 'me-central-1'
+--------------------------------+
| transit_gateway_route_table_id |
+--------------------------------+
+--------------------------------+
> select transit_gateway_attachment_id from aws_ec2_transit_gateway_vpc_attachment …
```

`aws_ec2_transit_gateway_*` tables should not error in me-central-1 region

---

aws/service_v2.go
aws/table_aws_fsx_file_system.go
aws/table_aws_inspector_assessment_template.go
aws/table_aws_kms_key.go
aws/table_aws_lambda_alias.go
aws/table_aws_lambda_function.go
aws/table_aws_lambda_layer.go
aws/table_aws_lambda_layer_version.go
aws/table_aws_lambda_version.go

<details>
```
```
</details>
<details>
```
```
</details>

Fix FSx, Inspector, KMS and Lambda tables to return null for unsupported regions

---

aws/plugin.go
aws/table_aws_ecr_image_scan_finding.go
docs/tables/aws_ecr_image_scan_finding.md

This table is used to get findings on a specific tag, in a specific repository allowing joins with others data sources
<details>
```
```
</details>
``` sql
select 
repository_name
,image_tag
,image_scan_completed_at
,vulnerability_source_updated_at
,finding
,partition
,repository_name
,account_id
from services.aws_ecr_image_findings where repository_name = 'my-ecr-repository-name' and image_tag = 'v1.0.0'
```
```sql
select
finding.*
from (
select
repository_name
,jsonb_array_elements_text(image_tags) as image_tag
from services.aws_ecr_image i
where
i.image_pushed_at > now() - interval '24' hour
) images
left outer join services.aws_ecr_image_findings finding
on images.repository_name = finding.repository_name and …
```

feat: add ecr image finding table

---

docs/tables/aws_cost_usage.md

<details>
```
```
</details>
<details>
```
```
</details>
This PR corrects a mistake in the documentation of the `aws_cost_usage` table, where the valid values of the `dimension_*` columns included `TAGS` as a valid value. However, as per [AWS](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsage.html), the columns don't support `TAGS` and can be misleading as mentioned in https://github.com/turbot/steampipe-plugin-aws/issues/1342

Fix typo and formatting in aws_cost_usage table

---

docs/tables/aws_ebs_volume.md

<details>
```
```
</details>
<details>
```
```
</details>

Update `aws_ebs_volume` table docs to handle the `attachments` column correctly when empty in the `aws_ebs_volume` table closes #1366

---

aws/table_aws_pricing_service_attribute.go

Sometimes `aws_pricing_service_attribute" table returns the multiples times the same column.
It seem a pointer shoud not be used in the for loop, before streaming item.
``` 
select
service_code, attribute_name
from bedrock_root_us.aws_pricing_service_attribute
where service_code = 'AmazonRDS'
+--------------+----------------+
| service_code | attribute_name |
+--------------+----------------+
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation      |
| AmazonRDS    | operation …
```

fix: fix invalid pointer usage in aws_pricing_service_attribute which returns randomly the same column

---

aws/table_aws_route53_record.go

<details>
```
SETUP: tests/aws_route53_record []
PRETEST: tests/aws_route53_record
TEST: tests/aws_route53_record
data.aws_caller_identity.current: Read complete after 1s [id=546902152798] …
```

aws_route53_record results incomplete or broken closes #1374

---

aws/table_aws_securityhub_finding.go
docs/tables/aws_securityhub_finding.md

The field `WorkflowState` is deprecated:
`Note that in the available filter fields, WorkflowState is deprecated. To search for a finding based on its workflow status, use WorkflowStatus .`
Link: https://docs.aws.amazon.com/cli/latest/reference/securityhub/get-findings.html
I added the `WorkflowStatus` field and the filter to use in the queries. 
I left the previous one, `WorfklowState` with a note "DEPRECATED."
<details>
```
```
</details>
<details>
```
select
title,
product_arn,
product_name,
workflow_status
from
local.aws_securityhub_finding
where
record_state = 'ACTIVE' and
workflow_status = 'NOTIFIED' and
severity ->> 'Original' = 'CRITICAL'
```
``` …
```

Security Hub Workflow Status field and filter

---

aws/table_aws_dynamodb_table.go

<details>
```
1380-error-when-querying-aws_dynamodb_table⚡ ⇒  ./tint.js aws_dynamodb_table
SETUP: tests/aws_dynamodb_table []
PRETEST: tests/aws_dynamodb_table
TEST: tests/aws_dynamodb_table …
```

Fix `getTableBillingMode` transform for type casting error in `aws_dynamodb_table`

---

aws/table_aws_s3_access_point.go

<details>
```
SETUP: tests/aws_s3_access_point []
PRETEST: tests/aws_s3_access_point
TEST: tests/aws_s3_access_point
data.aws_caller_identity.current: Read complete after 2s [id=548702155676]
Terraform used the …
```

List call is breaking when passing optional column in aws_s3_access_point table closes #1394

---

aws/plugin.go
aws/service.go
aws/table_aws_pricing_product.go
docs/tables/aws_pricing_product.md

Allowing usage of aws pricing API
</details>
<details>
```
select
service_code,
instance_type,
cache_engine,
term,
purchase_option,
lease_contract_length,
description,
price_per_unit,
currency
from
aws_pricing_product
where
service_code = 'AmazonElastiCache'
and region_code = 'eu-west-3'
and location_type = 'AWS Region'
and instance_type = 'cache.m5.xlarge'
and cache_engine = 'Redis';
```
| service\_code     | instance\_type  | cache\_engine | term     | purchase\_option | lease\_contract\_length | description                                             | price\_per\_unit | currency |
| ----------------- | --------------- | ------------- | -------- | ---------------- | ----------------------- | ------------------------------------------------------- | …

feat: add aws_pricing_product table

---

aws/multi_region.go
aws/service.go

<details>
```
connection "aws" {
plugin  = "aws"
regions = ["*"]
}
connection "aws_1" {
plugin  = "aws"
regions = ["eu-south-2"]
}
```
```
lalit@Lalits-MacBook-Pro:~/WORK/Turbot/steampipe/plugins/steampipe-plugin-aws|main⚡ ⇒  steampipe query                                                                              
Welcome to Steampipe v0.18.0-dev.8
> select * from aws_1.aws_sns_topic
Error: connection config has invalid "regions": eu-south-2. Edit your connection configuration file and then restart Steampipe. (SQLSTATE HV000)
+-----------+--------------+---------------------------------------+---------------------------------------+------------------------------------------+------------------------------------+---------------- …
```

Fix `getDefaultAwsRegion` to infer AWS default region based off of the region prefix in `aws.spc` regions argument.

---

aws/table_aws_cloudwatch_log_metric_filter.go

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_aab.aws_cloudwatch_log_metric_filter where log_group_name = 'hdalkjl'
+------+----------------+---------------+----------------+----------------------------+---------------------------------+-----------------------------+-------+------+-----------+--------+------------+------+
| name | log_group_name | creation_time | filter_pattern | metric_transformation_name | metric_transformation_namespace | metric_transformation_value | title | akas | partition | region | account_id | _ctx |
+------+----------------+---------------+----------------+----------------------------+---------------------------------+-----------------------------+-------+------+-----------+--------+--------- …
```

Fixed ResourceNotFoundException in aws_cloudwatch_log_metric_filter table closes #1419

---

aws/table_aws_ecs_task.go

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_ecs_task where service_name = 'tesgs'
+----------+------------------------+--------------+----------------+-------------+-------------------+------------------------+-------------+--------------+-----------------+-----+------------+------------------------+----------------------+-------+---------------+----
| task_arn | container_instance_arn | cluster_name | desired_status | launch_type | availability_zone | capacity_provider_name | cluster_arn | connectivity | connectivity_at | cpu | created_at | enable_execute_command | execution_stopped_at | group | health_status | las
+----------+------------------------+--------------+----------------+-------------+------------------- …
```

Fixed ServiceNotFoundException in aws_ecs_task table closes #1415

---

CHANGELOG.md
aws/table_aws_cloudwatch_metric.go
docs/tables/aws_cloudwatch_metric.md

N/A
<details>
```
> select
metric_name,
namespace,
dimensions
from
aws_cloudwatch_metric limit 10
-[ RECORD 1  ]---------------------------------------------------------------------------
metric_name | CallCount
namespace   | AWS/Usage
dimensions  | [{"Name":"Type","Value":"API"},{"Name":"Resource","Value":"DescribeTransitGatewayRouteTables"},{"Name":"Service","Value":"EC2"},{"Name":"Class","Value":"None"}]
-[ RECORD 2  ]---------------------------------------------------------------------------
metric_name | CallCount
namespace   | AWS/Usage
dimensions  | [{"Name":"Type","Value":"API"},{"Name":"Resource","Value":"DescribeKeyPairs"},{"Name":"Service","Value":"EC2"},{"Name":"Class","Value":"None"}]
-[ RECORD 3 …
```

Update `aws_cloudwatch_metric` table to return a metric in each row instead of a metric dimension

---

aws/table_aws_ec2_ami.go
aws/table_aws_ec2_ami_shared.go
go.mod
go.sum

<details>
```
SETUP: tests/aws_ec2_ami []
PRETEST: tests/aws_ec2_ami
TEST: tests/aws_ec2_ami
data.aws_caller_identity.current: Read complete after 1s [id=986502156756] …
```

Add column imds_support to aws_ec2_ami and aws_ec2_ami_shared table closes #1417

---

aws/table_aws_dynamodb_table.go

<details>
```
SETUP: tests/aws_dynamodb_table []
PRETEST: tests/aws_dynamodb_table
TEST: tests/aws_dynamodb_table
data.aws_caller_identity.current: Read complete after 1s [id=394802159485] …
```

Handle ResourceNotFoundException in ListTagsOfResource API of aws_dynamodb_table. Fixes #1516

---

aws/table_aws_drs_source_server.go
docs/tables/aws_drs_source_server.md

<details>
```
N/A
```
</details>
<details>
```
> select
arn,
title,
launch_configuration ->> 'Name' as launch_configuration_name,
launch_configuration ->> 'CopyPrivateIp' as launch_configuration_copy_private_ip,
launch_configuration ->> 'CopyTags' as launch_configuration_copy_tags,
launch_configuration ->> 'Ec2LaunchTemplateID' as ec2_launch_template_id,
launch_configuration ->> 'LaunchDisposition' as launch_configuration_disposition,
launch_configuration ->> 'TargetInstanceTypeRightSizingMethod' as target_instance_type_right_sizing_method,
launch_configuration -> 'Licensing' as launch_configuration_licensing,
launch_configuration -> 'ResultMetadata' as launch_configuration_result_metadata
from
aws_drs_source_server; …
```

Add column launch_configuration in aws_drs_source_server table. closes #1459

---

aws/table_aws_cloudtrail_trail.go

<details>
```
SETUP: tests/aws_cloudtrail_trail []
PRETEST: tests/aws_cloudtrail_trail
TEST: tests/aws_cloudtrail_trail
data.aws_caller_identity.current: Read complete after 1s [id=485602159834] …
```

The column insight_selectors in aws_cloudtrail_trail table return nil closes #1503

---

aws/service.go

<details>
```
SETUP: tests/aws_api_gatewayv2_api []
PRETEST: tests/aws_api_gatewayv2_api
TEST: tests/aws_api_gatewayv2_api
data.aws_caller_identity.current: Read complete after 2s [id=347802154958] …
```

Remove unsupported region(ap-southeast-3) for aws_api_gatewayv2_api service client closes #1526

---

aws/service.go
aws/table_aws_s3_access_point.go

<details>
```
```
</details>
<details>
```
SETUP: tests/aws_s3_access_point []
PRETEST: tests/aws_s3_access_point
TEST: tests/aws_s3_access_point
data.aws_region.primary: Read complete after 1s [id=us-east-1]
data.aws_partition.current: Read complete after 1s [id=aws] …
```

Fix aws_s3_access_point table to return resources from all the regions instead of only us-east-1 closes #1406

---

aws/table_aws_ebs_snapshot.go
docs/tables/aws_ebs_snapshot.md

<details>
```
```
</details>
<details>
```sql
> select arn, owner_id, account_id from aws_ebs_snapshot limit 5
+--------------------------------------------------------------------+--------------+--------------+
| arn                                                                | owner_id     | account_id   |
+--------------------------------------------------------------------+--------------+--------------+
| arn:aws:ec2:us-east-1:111222333444:snapshot/snap-0d741ecs455725d05 | 111222333444 | 111222333444 |
| arn:aws:ec2:us-east-1:111222333444:snapshot/snap-0c086de5a79eb01d5 | 111222333444 | 111222333444 |
| arn:aws:ec2:us-east-1:111222333444:snapshot/snap-007e4fg96da1949ab | 111222333444 | …
```

Fix `aws_ebs_snapshot` not returning details for shared snapshots

---

CHANGELOG.md
aws/table_aws_api_gatewayv2_stage.go
docs/tables/aws_api_gatewayv2_stage.md

<details>
```
➜  aws-test git:(issue-1538) ✗ ./tint.js aws_api_gatewayv2_stage
SETUP: tests/aws_api_gatewayv2_stage []
PRETEST: tests/aws_api_gatewayv2_stage
TEST: tests/aws_api_gatewayv2_stage …
```

Add column access_log_settings in table aws_api_gatewayv2_stage closes #1538

---

aws/table_aws_cloudwatch_log_group.go

<details>
```
SETUP: tests/aws_cloudwatch_log_group []
PRETEST: tests/aws_cloudwatch_log_group
TEST: tests/aws_cloudwatch_log_group
data.aws_caller_identity.current: Read complete after 1s [id=533793682495]
plan. Resource …
```

Update aws_cloudwatch_log_group table and fix ValidationException issue in getLogGroupTagging function

---

docs/tables/aws_cloudcontrol_resource.md
docs/tables/aws_cloudfront_origin_request_policy.md
docs/tables/aws_cloudtrail_query.md
docs/tables/aws_ec2_network_interface.md
docs/tables/aws_inspector_exclusion.md
docs/tables/aws_inspector_finding.md
docs/tables/aws_networkfirewall_firewall_policy.md
docs/tables/aws_oam_link.md
docs/tables/aws_pipes_pipe.md
docs/tables/aws_securityhub_finding.md
docs/tables/aws_securityhub_finding_aggregator.md
docs/tables/aws_vpc_verified_access_trust_provider.md

```pgsql
select
network_interface_id,
interface_type,
description,
private_ip_address,
association_public_ip,
mac_address
from
aws_ec2_network_interface
where
private_ip_address :: cidr <<= '10.66.0.0/16';
```
```pgsql
select
verified_access_trust_provider_id,
creation_time,
last_updated_time,
policy_reference_name,
trust_provider_type
from
aws_vpc_verified_access_trust_provider
where
creation_time >= now() - interval '90' day;
```
```pgsql
select
identifier,
properties ->> 'AlpnPolicy' as alpn_policy,
properties ->> 'Certificates' as certificates,
properties ->> 'Port' as port,
properties ->> 'Protocol' as protocol,
region,
account_id
from
aws_cloudcontrol_resource
where
type_name = 'AWS::ElasticLoadBalancingV2::Listener'
and resource_model = '{"LoadBalancerArn": …
```

Fix:Example queries update

---

aws/table_aws_eventbridge_rule.go

<details>
```
```
</details>
<details>
```
select name, event_pattern from aws_eventbridge_rule where event_bus_name = 'non-default-eventbus-name'
+------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Fix eventbus rule query for non-default eventbus closes #1591

---

docs/tables/aws_glue_dev_endpoint.md

<details>
```
```
</details>
<details>
```
```
</details>

Fix example query in aws_glue_dev_endpoint table doc to remove database_name column closes #1567

---

aws/table_aws_lambda_function.go
docs/tables/aws_lambda_function.md

<details>
```
data.aws_caller_identity.current: Read complete after 1s [id=533793682495] …
```

Add column `tracing_config` in table `aws_lambda_function` closes #1595

---

aws/table_aws_lambda_function.go

<details>
```
+ create
+ output_md5          = (known after apply)
+ output_path         = …
```

Fix architectures, snap_start column in aws_lambda_function table to correctly return data instead of null. Closes #1615

---

aws/table_aws_ec2_instance.go
docs/tables/aws_ec2_instance.md

<details>
```
data.aws_ami.ubuntu: Reading...
data.aws_caller_identity.current: Read complete after 2s [id=432504854533] …
```

Add column launch_template_data in table aws_ec2_instance closes #1552

---

aws/table_aws_s3_bucket.go
docs/tables/aws_s3_bucket.md

<details>
```sql
SETUP: tests/aws_s3_bucket []
PRETEST: tests/aws_s3_bucket
TEST: tests/aws_s3_bucket
data.aws_region.alternate: Read complete after 0s [id=us-east-1]
data.aws_canonical_user_id.current_user: Reading...
data.aws_region.primary: Read complete after 0s [id=us-east-2]
data.aws_caller_identity.current: Read complete after 2s …
```

Add column `website_configuration` in table `aws_s3_bucket`

---

aws/plugin.go
aws/table_aws_codebuild_build.go
docs/tables/aws_codebuild_build.md

<details>
```
No integration test exist.
```
</details>
<details>
```
select
arn,
id,
build_complete,
timeout_in_minutes,
project_name,
build_status,
encryption_key,
end_time,
region
from
aws_codebuild_build;
+--------------------------------------------------------------------------------------------------+---------------------------------------------------+----------------+--------------------+--------------+--------------+--------------------------------------------------+>
| arn                                                                                              | id                                                | build_complete | timeout_in_minutes | project_name | build_status | encryption_key …
```

Add table aws_codebuild_build

---

aws-test/tests/aws_eventbridge_rule/test-get-query.sql
aws-test/tests/aws_eventbridge_rule/variables.tf

<details>
```
SETUP: tests/aws_eventbridge_rule []
PRETEST: tests/aws_eventbridge_rule
TEST: tests/aws_eventbridge_rule
data.aws_caller_identity.current: Read complete after 2s [id=123456789876] …
```

Fix Integration test get query for aws_eventbridge_rule table. closes #1614

---

aws/table_aws_glue_security_configuration.go

<details>
```
SETUP: tests/aws_glue_security_configuration []
PRETEST: tests/aws_glue_security_configuration
TEST: tests/aws_glue_security_configuration
data.aws_caller_identity.current: Read complete after 2s …
```

Fix API limits in the ListConfig of aws_glue_security_configuration table. closes #1573

---

aws/table_aws_guardduty_ipset.go

<details>
```
SETUP: tests/aws_guardduty_ipset []
PRETEST: tests/aws_guardduty_ipset
TEST: tests/aws_guardduty_ipset
data.aws_caller_identity.current: Read complete after 2s [id=123453412343] …
```

Fix panic interface conversion error in aws_guardduty_ipset while making a list call. closes #1572

---

aws/table_aws_cloudfront_function.go

<details>
```
SETUP: tests/aws_cloudfront_function []
PRETEST: tests/aws_cloudfront_function
TEST: tests/aws_cloudfront_function
data.aws_caller_identity.current: Read complete after 1s [id=123453412343] …
```

Fix aws_cloudfront_function table to remove GetMatrixItemFunc from the table definition. closes #1570

---

docs/tables/aws_elastic_beanstalk_environment.md

<details>
```
```
</details>
<details>
```
```
</details>

Remove example query `List managed actions for each environment` aws_elastic_beanstalk_environment table doc Closes # 1632

---

aws/table_aws_ses_domain_identity.go

<details>
```
N/A
```
</details>
<details>
```
> select identity, dkim_attributes, identity_mail_from_domain_attributes from aws_ses_domain_identity;
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------->
| identity   | dkim_attributes                                                                                                                                                                                | identity_mail_from_domain_attributes                         > …
```

Add columns `dkim_attributes` and `identity_mail_from_domain_attributes` to aws_ses_domain_identity table. closes #1564

---

aws/plugin.go
aws/table_aws_ssm_document.go
aws/table_aws_ssm_document_permission.go
docs/tables/aws_ssm_document_permission.md

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_ssm_document_permission where document_name = 'test';
+---------------+-------------------+-------------------------+---------------------------------+----------+-----------+-----------+--------------+---------------------------+
| document_name | shared_account_id | shared_document_version | account_ids                     | title    | partition | region    | account_id   | _ctx                      |
+---------------+-------------------+-------------------------+---------------------------------+----------+-----------+-----------+--------------+---------------------------+
| test          | 321321312412      | $DEFAULT                | ["123456789012","321321312412"] | …
```

Add table aws_ssm_document_permission. closes #1669

---

aws/table_aws_securitylake_data_lake.go
aws/table_aws_simspaceweaver_simulation.go

<details>
```
N/A
```
</details>
<details>
```
> select encryption_key, replication_role_arn, tags from aws_securitylake_data_lake
+----------------+-------------------------------------------------------------------------+--------+
| encryption_key | replication_role_arn                                                    | tags   |
+----------------+-------------------------------------------------------------------------+--------+
| S3_MANAGED_KEY | arn:aws:iam::123456789009:role/SecurityLake_S3ReplicationRole_us_east_1 | <null> |
| S3_MANAGED_KEY | <null>                                                                  | <null> |
| S3_MANAGED_KEY | <null>                                                                  | <null> |
| …
```

Fixed the tags column data type for the tables aws_securitylake_data_lake and aws_simspaceweaver_simulation closes #1682

---

aws/table_aws_sfn_state_machine.go
aws/table_aws_sfn_state_machine_execution.go
aws/table_aws_sfn_state_machine_execution_history.go

- fix: typo
- Rename arn into stateMachineArn for clarity
<details>
```
```
</details>
<details>
```
```
</details>

typo: `aws_sfn_state_machine_*`

---

aws/plugin.go
aws/table_aws_wellarchitected_lens_review.go
docs/tables/aws_wellarchitected_lens_review.md

<details>
```
N/A
```
</details>
<details>
```
> select
lens_name,
workload_id,
lens_arn,
lens_alias,
lens_version,
updated_at
from
aws_wellarchitected_lens_review;
+--------------------------------+----------------------------------+---------------------------------------------------+-----------------+--------------+---------------------------+
| lens_name                      | workload_id                      | lens_arn                                          | lens_alias      | lens_version | updated_at                |
+--------------------------------+----------------------------------+---------------------------------------------------+-----------------+--------------+---------------------------+
| AWS Well-Architected Framework | …
```

Add table aws_wellarchitected_lens_review

---

aws/table_aws_ec2_instance.go
docs/tables/aws_ec2_instance.md

<details>
```
data.aws_ami.ubuntu: Reading...
data.aws_caller_identity.current: Read complete after 2s [id=432504854533] …
```

Add column maintenance_options, placement_*, spot_instance_request_id and licenses columns to aws_ec2_instance table closes #1708

---

aws-test/tests/aws_ssm_document/test-get-query.sql
aws-test/tests/aws_ssm_document/test-list-query.sql
aws/table_aws_ssm_document.go
docs/tables/aws_ssm_document.md

<details>
```
SETUP: tests/aws_ssm_document []
PRETEST: tests/aws_ssm_document
TEST: tests/aws_ssm_document
data.aws_caller_identity.current: Read complete after 2s [id=112233445566]
Terraform used the selected …
```

Fixed aws_ssm_document queries fail when querying multiple regions with the same document name Closes #1715

---

aws/table_aws_securityhub_finding.go
docs/tables/aws_securityhub_finding.md

The table `aws_securityhub_finding` exposes a column `account_id` which based on this document: https://hub.steampipe.io/plugins/turbot/aws/tables/aws_securityhub_finding is "The AWS Account ID in which the resource is located.". This can be very confusing, in this case, account_id is where security hub is running, not where the affected resource by a security hub finding is running. When you are aggregating findings from different accounts, is important to understand or been able to filter by the affected account: where the affected resource lives.
That's why i'm adding the column `affected_account_id`

Adding source_account_id column to aws_securityhub_finding table

---

aws/table_aws_ecr_repository.go
docs/tables/aws_ecr_repository.md

…ns using batch-get-repository-scanning-configuration method Closes #1716
<details>
```
```
</details>
<details>
```
> select title, repository_scanning_configuration,image_scanning_configuration from aws_ecr_repository
[
{
"image_scanning_configuration": {
"ScanOnPush": false
},
"repository_scanning_configuration": {
"Failures": [],
"ResultMetadata": {},
"ScanningConfigurations": [
{
"AppliedScanFilters": [],
"RepositoryArn": "arn:aws:ecr:us-east-1:698112345678:repository/demo",
"RepositoryName": "demo",
"ScanFrequency": "MANUAL",
"ScanOnPush": false
}
]
},
"title": "demo"
}
]
```
</details>

Add repository_scanning_configuration column to aws_ecr_repository table Closes #1716

---

aws/table_aws_ecr_image_scan_finding.go

When you query a non existing aws image, or when there is still no finding, aws api returns an nil `output.ImageScanFindings.Findings` object.
This results in a `[HV000] ERROR: rpc error: code = Internal desc = hydrate function listAwsEcrImageScanFindings failed with panic runtime error: invalid memory address or nil pointer dereference` error.
This PR fixes this issue.

fix: fix invalid pointer usage when your ecr image doesn't have any finding

---

aws/table_aws_ecr_image_scan_finding.go

<details>
```
```
</details>
<details>
```
```
</details>

Fix aws_ecr_image_scan_finding table to return an empty row instead of an error when image scanning is in progress

---

aws/table_aws_securityhub_finding.go

Field source_account_id was incorrectly defined, fixed.

Fix source_account_id optional qual column in aws_security_hub_finding table 

---

aws/plugin.go
aws/table_aws_rds_db_instance_automated_backup.go
docs/tables/aws_rds_db_instance_automated_backup.md

<details>
```
```
</details>
<details>
```
```
**Create the RDS backup using backup plan** 
```
> select * from aws_rds_db_instance_automated_backup
[
{
"_ctx": {
"connection_name": "aws_aab"
},
"account_id": "533791234567",
"akas": [
"arn:aws:rds:ap-south-1:533791234567:auto-backup:ab-edtifkapdodpuarzgevkxyipqddgikvhcsoxzwy"
],
"allocated_storage": 5,
"arn": "arn:aws:rds:ap-south-1:533791234567:auto-backup:ab-edtifkapdodpuarzgevkxyipqddgikvhcsoxzwy",
"availability_zone": "ap-south-1a",
"backup_retention_period": 1,
"backup_target": "region",
"db_instance_arn": "arn:aws:rds:ap-south-1:533791234567:db:my-sql-database-1", …
```

Add table aws_rds_db_instance_automated_backup Closes #1714

---

aws/service.go
aws/table_aws_wafv2_ip_set.go
aws/table_aws_wafv2_regex_pattern_set.go
aws/table_aws_wafv2_rule_group.go
aws/table_aws_wafv2_web_acl.go

<details>
```
```
</details>
<details>
```
> select
name,
id,
scope,
description,
capacity,
managed_by_firewall_manager
from
aws_wafv2_web_acl;
+---------------------+--------------------------------------+------------+-------------------+----------+-----------------------------+
| name                | id                                   | scope      | description       | capacity | managed_by_firewall_manager |
+---------------------+--------------------------------------+------------+-------------------+----------+-----------------------------+
| test-waf-acl-global | 73c9276d-be09-4a0d-9b67-83c87862e9e5 | CLOUDFRONT | test-waf-acl      | 0        | false                       |
| …
```

Fix `aws_wafv2_web_acl` not returning `CLOUDFRONT` resources closes #1747

---

aws/service.go

<details>
```
N/A
```
</details>
<details>
```
> select
scan_status_reason, region, resource_type,
count(*)
from
aws_inspector2_coverage
group by  scan_status_reason, region, resource_type
+--------------------+-----------+---------------+-------+
| scan_status_reason | region    | resource_type | count |
+--------------------+-----------+---------------+-------+
| SUCCESSFUL         | us-east-1 | AWS_ACCOUNT   | 1     |
+--------------------+-----------+---------------+-------+
```
</details>

Fixed aws_inspector2_coverage doesn't process regions correctly Closes #1756

---

aws/table_aws_wafv2_web_acl.go

<details>
```
```
</details>
<details>
```
> select name, region, associated_resources from aws_wafv2_web_acl
+-----------------+-----------+----------------------------------------------------------------------------+
| name            | region    | associated_resources                                                       |
+-----------------+-----------+----------------------------------------------------------------------------+
| test-cloudfront | global    | ["arn:aws:cloudfront::112233445566:distribution/E3SVMR2TLS0Z8S"]           |
| test-regional   | us-east-2 | ["arn:aws:appsync:us-east-2:112233445566:apis/2z2iik2jt5dyblbxwsozdpzqwy"] | …
```

Fixed associated_resources column of aws_wafv2_web_acl table to return associated CF distributions Closes #1762

---

aws/table_aws_cloudformation_stack_resource.go

<details>
```
```
</details>
<details>
```
> select logical_resource_id, stack_name, stack_id from aws_cloudformation_stack_resource limit 4
+---------------------------+------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| logical_resource_id       | stack_name                         | stack_id                                                                                                                     |
+---------------------------+------------------------------------+------------------------------------------------------------------------------------------------------------------- …
```

Fix `aws_cloudformation_stack_resource` returns empty if not provided with `stack_name`. Closes #1765

---

aws/table_aws_ec2_launch_template_version.go

<details>
```
SETUP: tests/aws_ec2_launch_template_version []
PRETEST: tests/aws_ec2_launch_template_version
TEST: tests/aws_ec2_launch_template_version
data.aws_caller_identity.current: Read complete after 2s …
```

Add column user_data in the table aws_ec2_launch_template_version Closes #1791

---

aws/table_aws_acm_certificate.go

<details>
```
SETUP: tests/aws_acm_certificate []
PRETEST: tests/aws_acm_certificate
TEST: tests/aws_acm_certificate
data.aws_caller_identity.current: Read complete after 2s [id=222222222222] …
```

Fix aws_acm_certificate table to return certificates of all type of key_algorithms Closes #1794

---

aws/table_aws_route53_record.go
docs/tables/aws_route53_record.md

<details>
```
SETUP: tests/aws_route53_record []
PRETEST: tests/aws_route53_record
TEST: tests/aws_route53_record
data.aws_caller_identity.current: Read complete after 1s [id=1223243543543]
plan. Resource actions are indicated …
```

Fix aws_route53_record table to use listHostedZones as the ParentHydrate to avoid cross-account access denied errors

---

aws/table_aws_acm_certificate.go

<details>
```
SETUP: tests/aws_acm_certificate []
PRETEST: tests/aws_acm_certificate
TEST: tests/aws_acm_certificate
data.aws_caller_identity.current: Read complete after 2s [id=222222222222] …
```

ACM Certificate tables error out on querying Closes #1815

---

aws/table_aws_directory_service_directory.go
docs/tables/aws_directory_service_directory.md

<details>
```
SETUP: tests/aws_directory_service_directory []
PRETEST: tests/aws_directory_service_directory
TEST: tests/aws_directory_service_directory
data.aws_caller_identity.current: Read complete after 2s …
```

Add columns event_topics and snapshot_limit  in the table aws_directory_service_directory Closes #1825

---

aws/plugin.go
aws/table_aws_vpc_nat_gateway_metric_bytes_out_to_destination.go
docs/tables/aws_vpc_nat_gateway_metric_bytes_out_to_destination.md

<details>
```
N/A
```
</details>
<details>
```
select
g.nat_gateway_id,
vpc_id,
subnet_id
from
aws_vpc_nat_gateway as g
left join aws_vpc_nat_gateway_metric_bytes_out_to_destination as d
on g.nat_gateway_id = d.nat_gateway_id
group by
g.nat_gateway_id,
vpc_id,
subnet_id
having
sum(average) <> 0;
+-----------------------+-----------------------+--------------------------+
| nat_gateway_id        | vpc_id                | subnet_id                |
+-----------------------+-----------------------+--------------------------+
| nat-0601e5792805b2571 | vpc-0e6e5565b44c7f8e1 | subnet-0160eb88cc3f8b7bd |
+-----------------------+-----------------------+--------------------------+
```
</details>

Add table aws_vpc_nat_gateway_metric_bytes_out_to_destination

---

aws/plugin.go
aws/table_aws_directory_service_certificate.go
docs/tables/aws_directory_service_certificate.md

<details>
```
```
</details>
<details>
```
> select * from aws_aab.aws_directory_service_certificate
+--------------+----------------+-------------+-------------+------------+---------------------------+---------------------------+--------------------------------------+---------------------------+------>
| directory_id | certificate_id | common_name | type        | state      | expiry_date_time          | registered_date_time      | state_reason                         | client_cert_auth_settings | title>
+--------------+----------------+-------------+-------------+------------+---------------------------+---------------------------+--------------------------------------+---------------------------+-- …
```

Add table aws_directory_service_certificate Closes #1835

---

aws/plugin.go
aws/table_aws_directory_service_log_subscription.go
aws/table_aws_directory_servicelog_subscription.go
docs/tables/aws_directory_servicelog_subscription.md

<details>
```
```
</details>
<details>
```sql
select * from aws_directory_service_log_subscription
[
{
"_ctx": {
"connection_name": "aws_zero_intg"
},
"account_id": "111111111111",
"directory_id": "d-9f671f1111",
"log_group_name": "/aws/directoryservice/d-9f671f1111-test.turbot.coom",
"partition": "aws",
"region": "ap-south-1",
"subscription_created_date_time": "2023-07-27T14:31:33+05:30",
"title": "/aws/directoryservice/d-9f671f1111-test.turbot.coom"
}
]
```
```sql
select * from aws_directory_service_log_subscription where directory_id = 'd-9f671f8b10'
[
{
"_ctx": {
"connection_name": "aws_zero_intg"
},
"account_id": "111111111111",
"directory_id": "d-9f671f1111",
"log_group_name": …
```

Add table `aws_directory_service_log_subscription`. Closes #1824

---

aws/table_aws_pricing_product.go

Hey folks 👋 
I made that little PR that should solve the issue #1862 
Actually the `OfferingClass` field is not in the regular attributes of the product but after some investigation I figure it out that it is in the `TermAttributes`
<details>
```
```
</details>
<details>
```
select
attributes ->> 'tenancy' as tenancy,
attributes ->> 'regionCode' as region,
offering_class,
term, unit,
price_per_unit,
purchase_option,
lease_contract_length
from aws_fix.aws_pricing_product where service_code='AmazonEC2' and filters='{"regionCode": "eu-west-1", "tenancy": "Shared", "operatingSystem":"Linux", "operation":"RunInstances", "instanceType": "m5.large"}' :: jsonb and term = 'Reserved' …
```

feat(aws_pricing_product): add OfferingClass field

---

docs/tables/aws_ec2_network_load_balancer.md

Documentation update, AWS NLBs do not use security group attachments

nlbs do not use sec groups

---

aws/table_aws_docdb_cluster.go
aws/table_aws_neptune_db_cluster.go
aws/table_aws_rds_db_cluster.go
aws/table_aws_rds_db_cluster_snapshot.go
aws/table_aws_rds_db_instance.go
aws/table_aws_rds_db_snapshot.go
aws/utils.go

<details>
```
```
</details>
<details>
```
> select
arn,
db_cluster_identifier,
deletion_protection,
engine,
status,
region
from
aws_docdb_cluster where db_cluster_identifier = 'docdb-2023-08-08-06-20-43';
+----------------------------------------------------------------------+---------------------------+---------------------+--------+-----------+-----------+
| arn                                                                  | db_cluster_identifier     | deletion_protection | engine | status    | region    |
+----------------------------------------------------------------------+---------------------------+---------------------+--------+-----------+-----------+
| …
```

Add checks for supported RDS engines

---

aws/table_aws_elasticsearch_domain.go
aws/table_aws_opensearch_domain.go

<details>
```
```
</details>
<details>
```
```
</details>

feat: add engine_type and endpoints columns to aws_elasticsearch_domain table

---

aws/plugin.go
aws/service.go
aws/table_aws_cognito_identity_pool.go
aws/table_aws_cognito_identity_provider.go
docs/tables/aws_cognito_identity_pool.md
go.mod
go.sum

This PR adds the `aws_cognito_identity_pool` table.
~Marked as draft as it is based on the branch of #1854, will rebase on `main` once that one is merged.~
<details>
```
```
</details>
<details>
```
> select
identity_pool_id,
identity_pool_name,
tags,
region,
account_id
from
aws_cognito_identity_pool;
+------------------------------------------------+---------------------------+------+-----------+--------------+
| identity_pool_id                               | identity_pool_name        | tags | region    | account_id   |
+------------------------------------------------+---------------------------+------+-----------+--------------+
| eu-west-3:e96205bf-1ef2-4fe6-a748-65e948673960 | …
```

feat: add `aws_cognito_identity_pool` table

---

docs/tables/aws_ec2_instance.md

Hi, In this PR i have added example to query aws ec2 instance with their subnet information.
Example i added
```sql
select 
i.instance_id, 
i.vpc_id, 
i.subnet_id, 
s.tags ->> 'Name'  as subnet_name
from 
aws_ec2_instance as i, 
aws_vpc_subnet as s 
where 
i.subnet_id = s.subnet_id;
```

added example for query instance with their subnet information

---

aws/table_aws_cognito_user_pool.go

From `json` to `string`.
The [official documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DescribeUserPool.html) confirms this as well.
<details>
```
> select sms_configuration_failure from aws.aws_cognito_user_pool;
+---------------------------+
| sms_configuration_failure |
+---------------------------+
| <null>                    |
| <null>                    |
| <null>                    |
| SNSSandbox                |
| SNSSandbox                |
+---------------------------+
```
</details>

Fix the type of `sms_configuration_failure` in `aws_cognito_user_pool`. Closes #1888

---

aws/plugin.go
aws/table_aws_workspaces_directory.go
docs/tables/aws_workspaces_directory.md

<details>
```
```
</details>
<details>
```sql
select
name,
directory_id,
arn,
alias,
customer_user_name,
directory_type,
state
from
aws_workspaces_directory;
+------------+--------------+-----------------------------------------------------------------------+----------+--------------------+----------------+------------+
| name       | directory_id | arn                                                                   | alias    | customer_user_name | directory_type | state      |
+------------+--------------+-----------------------------------------------------------------------+----------+--------------------+----------------+------------+
| turbot.com | d-9667699578 | …
```

Add table `aws_workspaces_directory`. Closes #1819

---

aws/table_aws_ec2_instance.go

<details>
```
```
</details>
<details>
```sql
> select instance_id, arn, capacity_reservation_specification from aws_ec2_instance
[
{
"arn": "arn:aws:ec2:us-east-1:111111111111:instance/i-061073b2b90b8a7da",
"capacity_reservation_specification": {
"CapacityReservationPreference": "",
"CapacityReservationTarget": {
"CapacityReservationId": "cr-022bb8c139a39f1d2",
"CapacityReservationResourceGroupArn": null
}
},
"instance_id": "i-061073b2b90b8a7da"
}
]
> 
```
</details>

Fix capacity_reservation_specification column of aws_ec2_instance table to be of JSON type closes #1894

---

aws/table_aws_dynamodb_backup.go

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_aab.aws_dynamodb_backup where arn = 'arn:aws:dynamodb:us-east-1:123457632432:table/table-delete/backup/01678793340962-cc4bfb86'
+---------------------------------------+-------------------------------------------------------------------------------------------+--------------+------------------------------------------------------->
| name                                  | arn                                                                                       | table_name   | table_arn                                             >
+---------------------------------------+-------------------------------------------------------------------------------------------+----------- …
```

Fixed the table aws_dynamodb_backup returns error BackupNotFoundException closes #1913

---

aws/table_aws_securityhub_finding.go

The field `source_account_id` in table `table_aws_securityhub_finding` was trying to fetch that field, which doesn't exist in the AWS API. The correct API field for this table field is `AwsAccountId`, so I'm adding the `Transform` option. 
Cheers 🥂 
Before: 
```
+---------------------------------------------------+-------------------+
| title                                             | source_account_id |
+---------------------------------------------------+-------------------+
| S3 bucket server access logging should be enabled | <null> |
```
After:
```
+---------------------------------------------------+-------------------+
| title                                             | source_account_id |
+---------------------------------------------------+-------------------+
| S3 bucket …
```

fix table_aws_securityhub_finding field source_account_id

---

docs/tables/aws_iam_role.md

Improve documentation and descriptions on the aws_iam_role table

Improve the documentation and descriptions for the aws_iam_role table (1939)

---

aws/table_aws_organizations_account.go

This is a minor fix to the `.inspect aws_organizations_account` command; the text currently refers to a permission set, but should refer to an AWS account. This PR corrects the text in the description.
Current output:
```
> .inspect aws_organizations_account
+------------------+--------------------------+----------------------------------------------------------------------------------+
| column           | type                     | description                                                                      |
+------------------+--------------------------+----------------------------------------------------------------------------------+
| _ctx             | jsonb                    | Steampipe context in JSON form, e.g. connection_name.                            |
| account_id …
```

Fixed a typo in the description of a column

---

aws/plugin.go
aws/table_aws_lambda_function_event_source_mapping.go
docs/tables/aws_lambda_function_event_source_mapping.md

<details>
```
```
</details>
<details>
```sql
select
event_source_arn,
function_arn,
function_name,
last_processing_result,
parallelization_factor,
state,
destination_config
from
aws_lambda_function_event_source_mapping;
```
|event_source_arn|function_arn|function_name|last_processing_result|parallelization_factor|state|destination_config|
|----------------|------------|-------------|----------------------|----------------------|-----|------------------|
|arn:aws:kinesis:us-east-1:XXXXXXXXXXXXXX:stream/w8imy|arn:aws:lambda:us-east-1:XXXXXXXXXXXXXX:function:eventaudit|eventaudit|OK|9|Enabled|{"OnFailure": {"Destination": "arn:aws:sqs:us-east-1:XXXXXXXXXXXXXX:FailedAuditEvents"}, "OnSuccess": null}| …

Add table aws_lambda_function_event_source_mapping Closes #1872

---

aws/table_aws_route53_zone.go

<details>
```
```
</details>
<details>
```
SELECT                                                                                                                                                                                                                              
resource_record_set_limit
from aws_route53_zone
WHERE 
name not like '%internal%'
LIMIT 1;"
```
```
+---------------------------+
| resource_record_set_limit |
+---------------------------+
| 10000                     |
+---------------------------+
```
</details>

Add column resource_record_set_limit to aws_route53_zone

---

aws/table_aws_iam_policy_attachment.go

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_iam_policy_attachment
+------------------------------------------------------------------------------------------------------------------------------+-------------+----------------------------------------------------------------------+-------------------------------------------------------->
| policy_arn                                                                                                                   | is_attached | policy_groups                                                        | policy_roles                                           >
+--------------------------------------------------------------------------------------------------------------------- …
```

Fixed MaxItems for aws_iam_policy_attachment should be 1000, not 100 Closes #2022

---

aws/table_aws_iam_policy.go

<details>
```
SETUP: tests/aws_iam_policy []
PRETEST: tests/aws_iam_policy
TEST: tests/aws_iam_policy
data.aws_caller_identity.current: Read complete after 1s [id=333333333333]
data.null_data_source.resource: …
```

Fixed MaxItems for aws_iam_policy should be 1000, not 100 Closes #2023

---

aws/table_aws_backup_recovery_point.go
aws/table_aws_backup_vault.go
docs/tables/aws_backup_recovery_point.md

<details>
```
```
</details>
<details>
```
> select name, tags from aws_backup_vault
+--------------------------------+---------------+
| name                           | tags          |
+--------------------------------+---------------+
| Default                        | {}            |
| aws/efs/automatic-backup-vault | {}            |
| Default                        | {"foo":"bar"} |
| Default                        | {}            |
| Default                        | {}            |
| aws/efs/automatic-backup-vault | {}            |
+--------------------------------+---------------+
```
</details>

Support tags for aws_backup_vault and aws_backup_recovery_point Closes #2031

---

aws/table_aws_dynamodb_table.go
go.mod
go.sum

Please see https://github.com/aws/aws-sdk-go-v2/commit/5799416de4970748df37d556db57a88e050d99c9#diff-5bff2101cfda3ee73930b662b6d8c0498792c94dae3d4f403f703fe3f8e4e342R1
<details>
N/A
</details>
<details>
```
> select arn, deletion_protection_enabled from aws_dynamodb_table;
+-------------------------------------------------------------------------------------+-----------------------------+
| arn                                                                                 | deletion_protection_enabled |
+-------------------------------------------------------------------------------------+-----------------------------+
| arn:aws:dynamodb:eu-central-1:123456789012:table/prod-foobar                        | true                       |
| …
```

Add deletion_protection_enabled column to aws_dynamodb_table table

---

aws/table_aws_rds_db_instance.go

Note: This PR contains the fix if the `ProcessorFeatures` value has been set to the default configuration, then we should get the default value for the particular DB Instance.
<details>
```
```
</details>
<details>
```
> select db_instance_identifier, engine,engine_version, availability_zone, class, processor_features from aws_rds_db_instance;
+------------------------+-----------+------------------------------------+-------------------+--------------+--------------------------------------------------------------------------+
| db_instance_identifier | engine    | engine_version                     | availability_zone | class        | processor_features …
```

Populate 'processor_features' Column When Default Value Is Set Closes #2018

---

aws-test/tests/aws_cloudwatch_log_group/test-get-query.sql
aws/table_aws_cloudwatch_log_group.go

<details>
```
SETUP: tests/aws_cloudwatch_log_group []
PRETEST: tests/aws_cloudwatch_log_group
TEST: tests/aws_cloudwatch_log_group
data.aws_caller_identity.current: Read complete after 0s [id=333333333333] …
```

Fixed aws_cloudwatch_log_group table for the error key column is not globally unique Closes #1975

---

aws/table_aws_ec2_launch_template.go
aws/table_aws_s3_multi_region_access_point.go

<details>
```
```
</details>
<details>
```
Before fix:
steampipe query "select * from aws_ec2_launch_template" 
Warning: terminal options has been deprecated and will be removed in a future version of Steampipe.
These can now be set in a steampipe workspace.
(/Users/parthas/.steampipe/config/default.spc:34,20-42,2)
+-------------------------+----------------------+---------------------------+----------------------------------------------------------------------------------------------------+------------------------+-----------------------+----------+-------------------------+--------+------------------------------------------------------------------------------+-----------+------------+--------------+ …
```

Remove duplicate memoizing of getCommonColumns. Closes #2064

---

CHANGELOG.md

<details>
```
```
</details>
<details>
```
```
</details>

Add CHANGELOG for v0.130.0

---

aws/table_aws_sfn_state_machine_execution_history.go

This PR updates  the `aws_sfn_state_machine_execution_history` table to implement pagination and ignore errors for expired executions history, [which are only preserved for a maximum of 90 days](https://docs.aws.amazon.com/step-functions/latest/dg/limits-overview.html#service-limits-state-machine-executions).
Without this latter change, one would get errors like this one:
```
Error: operation error SFN: GetExecutionHistory, https response error StatusCode: 400, RequestID: 68dacbfc-af53-42f5-985e-a019c51b679f, ExecutionDoesNotExist: Execution Does Not Exist: 'arn:aw
s:states:eu-west-3:012345678901:execution:sfn-test-012345678901:b1b58243-1276-4195-863a-e83bed3dd603' (SQLSTATE HV000)
```
<details>
```
```
</details>
<details> …

fix(sfn): handle pagination and ignore errors for expired executions history

---

aws/plugin.go
aws/table_aws_organizations_organizational_unit.go
docs/tables/aws_organizations_organizational_unit.md

**Note:** This table is compatible with Steampipe CLI version `v0.21.4` and later.
<details>
```
N/A
```
</details>
<details>
```
> select
name,
id,
parent_id,
title, path
from
aws_organizations_organizational_unit;
+--------------------------+------------------+------------------+--------------------------+------------------------------------------+
| name                     | id               | parent_id        | title                    | path                                     |
+--------------------------+------------------+------------------+--------------------------+------------------------------------------+
| account creation testing | ou-wxnb-feyv7riq | r-wxnb           | account creation testing | r_wxnb.ou_wxnb_feyv7riq …
```

Add table aws_organizations_organizational_unit back to the table list

---

aws/table_aws_health_affected_entity.go

<details>
```
N/A
```
</details>
<details>
```
```
</details>

Fixed Interface Conversion Error When Querying aws.aws_health_affected_entity Closes #2069

---

aws/table_aws_rds_db_instance_metric_write_iops_daily.go

<details>
```
Add passing integration test logs herN/A
```
</details>
<details>
```
Before Fix:
> select * from aws_silverwater.aws_rds_db_instance_metric_write_iops_daily
+------------------------+-------------+-----------+---------------------+--------------------+----------------------+--------------+--------------------+--------------+---------------------------+-----------+----------------+--------------+---------------------------->
| db_instance_identifier | metric_name | namespace | average             | maximum            | minimum              | sample_count | sum                | unit         | timestamp                 | partition | region         | account_id   | _ctx                       > …
```

Fixed aws_rds_db_instance_metric_write_iops_daily displays "ReadIOPS" instead of "WriteIOPS" Closes #2075

---

aws-test/tests/aws_ecr_registry_scanning_configuration/test-get-expected.json
aws-test/tests/aws_ecr_registry_scanning_configuration/test-get-query.sql
aws-test/tests/aws_ecr_registry_scanning_configuration/variables.tf
aws/plugin.go
aws/table_aws_ecr_registry_scanning_configuration.go
docs/tables/aws_ecr_registry_scanning_configuration.md

<details>
```
SETUP: tests/aws_ecr_registry_scanning_configuration []
PRETEST: tests/aws_ecr_registry_scanning_configuration
TEST: tests/aws_ecr_registry_scanning_configuration
data.aws_caller_identity.current: Read complete after 0s [id=12345678910]
Terraform used the selected providers to generate …
```

Add table aws_ecr_registry_scanning_configuration #2083

---

aws/table_aws_elastic_beanstalk_environment.go

<details>
```
```
</details>
<details>
```
> select arn from aws_elastic_beanstalk_environment
+-------------------------------------------------------------------------------+
| arn                                                                           |
+-------------------------------------------------------------------------------+
| arn:aws:elasticbeanstalk:us-east-1:123456789012:environment/TESTNO/TESTNO-env |
| arn:aws:elasticbeanstalk:us-east-1:123456789012:environment/tes5t6/Tes5t6-env |
+-------------------------------------------------------------------------------+
```
</details>

Fix arn column in table aws_elastic_beanstalk_environment closes #2105

---

aws/table_aws_rds_db_cluster.go

… 
<details>
```
```
</details>
<details>
```
> select title, auto_minor_version_upgrade from aws_rds_db_cluster
+------------+----------------------------+
| title      | auto_minor_version_upgrade |
+------------+----------------------------+
| database-1 | true                       |
+------------+----------------------------+
```
</details>

Add new column auto_minor_version_upgrade in table aws_rds_db_cluster closes #2108

---

aws/table_aws_fsx_file_system.go

<details>
```
SETUP: tests/aws_fsx_file_system []
PRETEST: tests/aws_fsx_file_system
TEST: tests/aws_fsx_file_system
data.aws_caller_identity.current: Read complete after 0s [id=434553143433]
Terraform used the …
```

Add OpenZFSFileSystemConfiguration in table aws_fsx_file_system Closes #2112

---

aws/table_aws_ec2_client_vpn_endpoint.go
docs/tables/aws_ec2_client_vpn_endpoint.md

<details>
```
```
</details>
<details>
```
> select title, connection_log_options from aws_ec2_client_vpn_endpoint
+--------+---------------------------------------------------------------------------------------------------------------------------------------+
| title  | connection_log_options                                                                                                                |
+--------+---------------------------------------------------------------------------------------------------------------------------------------+
| tets56 | {"CloudwatchLogGroup":"test","CloudwatchLogStream":"log_stream_created_by_aws_to_validate_log_delivery_subscriptions","Enabled":true} | …
```

Rename client_log_options column to connection_log_options in aws_ec2_client_vpn_endpoint table to correctly fetch data closes #2121

---

aws/table_aws_sns_topic_subscription.go
docs/tables/aws_sns_topic_subscription.md

<details>
```
SETUP: tests/aws_sns_topic_subscription []
PRETEST: tests/aws_sns_topic_subscription
TEST: tests/aws_sns_topic_subscription
data.aws_caller_identity.current: Read complete after 0s [id=345644333333] …
```

Update the table aws_sns_topic_subscription to use ListSubscriptionsByTopic API instead of ListSubscriptions

---

aws/table_aws_ssm_maintenance_window.go

<details>
```
SETUP: tests/aws_ssm_maintenance_window []
PRETEST: tests/aws_ssm_maintenance_window
TEST: tests/aws_ssm_maintenance_window
data.aws_caller_identity.current: Read complete after 1s [id=478932174913] …
```

Fixed aws_ssm_maintenance_window fails if ScheduleTimezone is not UTC Closes #2114

---

aws/plugin.go
aws/table_aws_rds_db_engine_version.go
docs/tables/aws_rds_db_engine_version.md

<details>
```
N/A
```
</details>
<details>
```
select * from aws_rds_db_engine_version where not list_supported_timezones;
+----------------------+------------------------------------+--------+-----------+-------------+-----------------------------------+-------------------------------+------------->
| engine               | engine_version                     | arn    | status    | create_time | custom_db_engine_version_manifest | list_supported_character_sets | list_support>
+----------------------+------------------------------------+--------+-----------+-------------+-----------------------------------+-------------------------------+------------->
| aurora-mysql         | 8.0.mysql_aurora.3.01.1            | <null> | available | …
```

Add table aws_rds_db_engine_version Closes #2097

---

aws/table_aws_api_gateway_stage.go
aws/table_aws_vpc_eip.go
aws/table_aws_vpc_vpn_connection.go

Note: If a Service Control Policy is applied to an account for a specific region, we should receive an access denied error, not an invalid memory address or nil pointer dereference error.
<details>
```
N/A
```
</details>
<details>
```
Before fix:
Error: rpc error: code = Internal desc = aws_org_1: rpc error: code = Internal desc = hydrate function listVpcEips failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
+---------------+-----+-----------+------------------+--------+----------------+------------+-------------------+--------------------------+-------------+----------------------+----------------------+----------------------------+------>
| allocation_id | arn | public_ip | …
```

Fixed aws_vpc_eip produce nil pointer error Closes #2124

---

aws/multi_region.go

<details>
```
N/A
```
</details>
<details>
```
Before fix: 
Global table(Returns error):
> select * from assumed_role_from_aab.aws_iam_user
Error: assumed_role_from_aab: operation error IAM: ListUsers, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: 225233fe-d5c2-4356-90a5-48c04ffe8810, api error InvalidClientTokenId: The security token included in the request is invalid. (SQLSTATE HV000)
+------+---------+------+-----+-------------+--------------------+--------------------------+---------------------------+-------------+---------------+-------------+--------+-----------------+---------------------+--------------- …
```

Fixed when using AWS profiles with cross-account role credentials, querying regional tables does not result in an error Closes #2074

---

aws/service.go
go.mod
go.sum

With this change, the following messages are logged:
```
2023-11-14 05:14:18.020 UTC [DEBUG] steampipe-plugin-aws.plugin: [DEBUG] 1699938850561: retrying request CloudFront/ListTagsForResource, attempt 2
2023-11-14 05:14:19.400 UTC [DEBUG] steampipe-plugin-aws.plugin: [DEBUG] 1699938850561: retrying request CloudFront/ListTagsForResource, attempt 2
2023-11-14 05:14:19.993 UTC [DEBUG] steampipe-plugin-aws.plugin: [DEBUG] 1699938850561: retrying request CloudFront/ListTagsForResource, attempt 3
2023-11-14 05:14:23.015 UTC [DEBUG] steampipe-plugin-aws.plugin: [DEBUG] 1699938850561: retrying request CloudFront/ListTagsForResource, attempt 2
2023-11-14 05:14:26.211 UTC [DEBUG] steampipe-plugin-aws.plugin: [DEBUG] 1699938850561: retrying request CloudFront/ListTagsForResource, attempt 2 …
```

feat: make AWS SDK log retries at DEBUG or TRACE levels

---

aws-test/tests/aws_s3_bucket/variables.tf

Without this change, bucket creation required by tests fails with a `AccessControlListNotSupported: The bucket does not allow ACLs` error during `PutBucketAcl` terraform call:
```
SETUP: tests/aws_s3_bucket []
PRETEST: tests/aws_s3_bucket
TEST: tests/aws_s3_bucket
data.aws_region.alternate: Read complete after 0s [id=us-east-1]
data.aws_canonical_user_id.current_user: Reading...
data.aws_region.primary: Read complete after 0s …
```

fix: configure AWS S3 bucket object ownership to make tests pass

---

aws/table_aws_ebs_snapshot.go

<details>
```
data.aws_caller_identity.current: Read complete after 0s [id=333333333333]
data.null_data_source.resource: …
```

Updated aws_ebs_snapshot should not set maxlimit by default Closes #2081

---

aws/plugin.go
aws/table_aws_accessanalyzer_analyzer.go
aws/table_aws_accessanalyzer_finding.go
docs/tables/aws_accessanalyzer_finding.md

<details>
```
```
</details>
<details>
```
select
id,
analyzed_at,
resource_type,
status,
is_public
from
aws_accessanalyzer_finding;
+--------------------------------------+---------------------------+-----------------------------+----------+-----------+
| id                                   | analyzed_at               | resource_type               | status   | is_public |
+--------------------------------------+---------------------------+-----------------------------+----------+-----------+
| 05c16136-d793-46b6-9b30-13f4d85687ac | 2024-03-21T06:50:35+05:30 | AWS::IAM::Role              | ACTIVE   | false     |
| a200ea7b-209d-47cb-9200-4f9f3014aed0 | 2024-03-13T21:15:43+05:30 | …
```

Add table aws_accessanalyzer_finding. Closes #1812

---

aws/table_aws_directory_service_directory.go

<details>
```
SETUP: tests/aws_directory_service_directory []
PRETEST: tests/aws_directory_service_directory
TEST: tests/aws_directory_service_directory
data.aws_caller_identity.current: Read complete after 0s …
```

Fixed Directory Service shared into account causes some queries like SELECT ... FROM aws_directory_service_directory to fail Closes #2155

---

.github/workflows/steampipe-anywhere.yml

<details>
```
```
</details>
<details>
```
```
</details>

Add test installation steps to the Steampipe Anywhere components workflow

---

aws/table_aws_directory_service_directory.go

<details>
```
N/A
```
</details>
<details>
```
Before fix:
> select name, type, event_topics, snapshot_limit from aws_directory_service_directory
Error: aws: operation error Directory Service: GetSnapshotLimits, https response error StatusCode: 400, RequestID: b75299bd-9b0c-4818-9609-e61aba43c002, ClientException: Snapshot limits can be fetched only for VPC or Microsoft AD directories. : RequestId: b75299bd-9b0c-4818-9609-e61aba43c002 (SQLSTATE HV000)
+----------+----------+--------------+------------------------------------------------------------------------------------------------+
| name     | type     | event_topics | snapshot_limit                                                                                 | …
```

Fixed the operation not allowed error for the table aws_directory_service_directory Closes #2155

---

aws/table_aws_ebs_snapshot.go

<details>
```
data.aws_caller_identity.current: Read complete after 0s [id=xxxxxxxxxxxx]
plan. Resource actions are indicated with …
```

Fixed table aws_ebs_snapshot is returning empty rows even though there is data present Closes #2184

---

aws/table_aws_ec2_key_pair.go

<details>
```
```
</details>
<details>
```
> .inspect aws_ec2_key_pair
+--------------------+--------------------------+------------------------------+
| column             | type                     | description                  |
+--------------------+--------------------------+------------------------------+
| _ctx               | jsonb                    | Steampipe context in JSON fo |
|                    |                          | rm.                          |
| account_id         | text                     | The AWS Account ID in which  |
|                    |                          | the resource is located.     |
| akas               | jsonb                    | Array of globally …
```

Add ec2 keypair create_time field (#2196)

---

aws-test/tests/aws_elastic_beanstalk_environment/variables.tf
aws/table_aws_elastic_beanstalk_environment.go

<details>
```
SETUP: tests/aws_elastic_beanstalk_environment []
PRETEST: tests/aws_elastic_beanstalk_environment
TEST: tests/aws_elastic_beanstalk_environment
data.aws_caller_identity.current: Read complete after 0s [id=xxxxxxxxxxxx]
data.aws_region.alternate: Read complete after …
```

Fixed aws_elastic_beanstalk_environment - cname/endpoint_url fields return NULL Closes #2193

---

aws/table_aws_ec2_instance_type.go

<details>
```
N/A
```
</details>
<details>
```
> select count(*) from aws_ec2_instance_type
+-------+
| count |
+-------+
| 11139 |
+-------+
> select count(*) from aws_ec2_instance_type where region = 'us-east-1'
+-------+
| count |
+-------+
| 776   |
+-------+
> select count(*) from aws_ec2_instance_type where region = 'ap-south-1'
+-------+
| count |
+-------+
| 518   |
+-------+
> select instance_type, region from aws_gov.aws_ec2_instance_type
+-------------------+---------------+
| instance_type     | region        |
+-------------------+---------------+
| r6g.large         | us-gov-west-1 |
| r5dn.xlarge       | us-gov-west-1 |
| c6gd.4xlarge      | us-gov-west-1 |
| r6in.2xlarge      | us-gov-west-1 |
| r6idn.16xlarge    | …
```

Updated the table aws_ec2_instance_type for populating the column value per region and filter results by instance_type Closes #2195

---

aws-test/tests/aws_elasticache_cluster/variables.tf
aws/table_aws_elasticache_cluster.go

<details>
```
SETUP: tests/aws_elasticache_cluster []
PRETEST: tests/aws_elasticache_cluster
TEST: tests/aws_elasticache_cluster
data.aws_caller_identity.current: Read complete after 0s [id=************]
data.null_data_source.resource: …
```

Fixed aws_elasticache_cluster - configuration_endpoint not returned as JSON Closes #2213

---

aws/table_aws_elasticache_cluster.go

<details>
```
SETUP: tests/aws_elasticache_cluster []
PRETEST: tests/aws_elasticache_cluster
TEST: tests/aws_elasticache_cluster
aws_vpc.my_vpc: Refreshing state... [id=vpc-04e9acce04f2ac144]
data.aws_caller_identity.current: Read complete after 0s [id=xxxxxxxxxxxx] …
```

Added the missing columns to the table  aws_elasticache_cluster Closes #2223

---

aws/table_aws_s3_object.go

<details>
```
N/A
```
</details>
<details>
```
> SELECT key, bucket_name, region
FROM   aws_s3_object
WHERE  bucket_name = 'test-delete90'
+-----------------------+---------------+-----------+
| key                   | bucket_name   | region    |
+-----------------------+---------------+-----------+
| test1/template.txt    | test-delete90 | us-east-2 |
| AWSLogs/632902152528/ | test-delete90 | us-east-2 |
| test1/                | test-delete90 | us-east-2 |
+-----------------------+---------------+-----------+
Time: 0.5s. Rows returned: 3. Rows fetched: 3. Hydrate calls: 3.
> select * from aws_s3_object where bucket_name = 'test-delete90'
+-----------------------+--------------------------------------------------+---------------+--------- …
```

Fixed the table  aws_s3_object - hydrate function listS3Objects failed with panic Closes #2218

---

aws-test/tests/aws_lambda_version/test-get-call-expected.json
aws-test/tests/aws_lambda_version/test-list-call-expected.json
aws-test/tests/aws_lambda_version/variables.tf
aws/table_aws_lambda_version.go

<details>
```
SETUP: tests/aws_lambda_version []
PRETEST: tests/aws_lambda_version
TEST: tests/aws_lambda_version
data.aws_caller_identity.current: Read complete after 0s [id=xxxxxxxxxxxx] …
```

Added missing columns to the table aws_lambda_version Closes #2228

---

docs/tables/aws_cost_by_account_monthly.md
docs/tables/aws_cost_by_service_monthly.md

I believe these example are using the wrong direction!

fix lag direction in examples of aws_cost_* table docs

---

aws/utils.go

<details>
```
```
</details>
<details>
Before
```
select instance_id, user_data from aws_unicode.aws_ec2_instance where instance_id='i-0de5b360e69bab111'
+---------------------+-----------+
| instance_id         | user_data |
+---------------------+-----------+
| i-0de5b360e69bab111 | pfconf    |
+---------------------+-----------+
```
After
```
select instance_id, user_data from aws_unicode.aws_ec2_instance where instance_id='i-0de5b360e69ba1111'
+---------------------+--------------------------------------------------------------------------------------------------------------------->
| instance_id         | user_data …
```

Fixed base64DecodedData function to remove null characters from the decoded output

---

aws/table_aws_auditmanager_control.go
docs/tables/aws_auditmanager_control.md

<details>
```
N/A
```
</details>
<details>
```
with test as (
select
distinct cms -> 'SourceKeyword' ->> 'KeywordValue' as steampipe_control,
region
from 
aws_auditmanager_framework as f,
jsonb_array_elements(control_sets) as cs, jsonb_array_elements(cs -> 'Controls') as c, jsonb_array_elements(c -> 'ControlMappingSources') as cms 
where lower(f.name) = 'nist cybersecurity framework (csf) v1.1' and cms ->> 'SourceType' = 'Core_Control' limit 10
)
select 
name, id, jsonb_pretty(control_mapping_sources) as control_mapping_sources 
from 
aws_auditmanager_control as c,
test as t
where c.id = t.steampipe_control
and c.type = 'Core'
and c.region = t.region
Warning: Server enforces maximum TTL of 300 seconds. Cannot set TTL to 900 seconds. TTL …
```

Enhanced the aws_auditmanager_control table to list controls by type and fixed the Get config error "get call returned 2 results"

---

aws/table_aws_ebs_snapshot.go
aws/table_aws_ec2_instance_availability.go
aws/table_aws_ec2_instance_type.go

_**Note:**_ I have tested all the tables utilizing the EC2 package and found no breaking changes. The data from the current EC2 package in the main branch and the new EC2 package featured in [this PR](https://github.com/turbot/steampipe-plugin-aws/pull/2077) were compared, revealing identical results.
<details>
```
N/A
```
</details>
<details>
```
> select * from aws_ec2_instance_availability limit 1
+---------------+-----------+---------------+-------------+------------------------------------------------------+---------------------------------------------------------------+
| instance_type | location  | location_type | title       | akas                                                 | _ctx …
```

Updated tables as per EC2 package version updated

---

aws-test/tests/aws_ec2_ami/test-get-expected.json
aws-test/tests/aws_ec2_ami/variables.tf
aws/table_aws_ec2_ami.go

<details>
```
SETUP: tests/aws_ec2_ami []
PRETEST: tests/aws_ec2_ami
TEST: tests/aws_ec2_ami
data.aws_caller_identity.current: Read complete after 0s [id=111222333444]
Terraform used the selected providers to generate …
```

Add check when querying for disabled AMI

---

aws/table_aws_ec2_instance_type.go

…nstance_type. Add the location_type column. Fixes #2292.
<details>
```
```
</details>
<details>
```
```
</details>

Remove unnecessary hydration of the instance_type column in aws_ec2_instance_type. Add the location_type column. Fixes #2292.

---

aws/table_aws_servicequotas_service_quota.go

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_servicequotas_service_quota WHERE quota_code = 'L-0263D0A3' and service_code = 'ec2'
+---------------------+------------+------------------------------------------------------------------+--------------+-------------------------------------------+--------------+------------+------+------------------------+-------+--------------+--------+----------+--------------+---------------+--------+--------->
| quota_name          | quota_code | quota_arn                                                        | global_quota | service_name                              | service_code | adjustable | unit | quota_applied_at_level | value | error_reason | period | tags_src | usage_metric | …
```

Fixed aws_servicequotas_service_quota queries fail when querying multiple regions with the same service_code Closes #2313

---

aws/table_aws_kinesis_stream.go

This is my first contribution to the Steampipe project, and I’m excited to collaborate with the team! Please feel free to provide any feedback or guidance on improvements. I’m happy to make any adjustments as needed. Thank you for reviewing my contribution!
This PR introduces a new column, StreamModeDetails, in the aws/table_aws_kinesis_stream.go table. The purpose of this column is to provide essential information about the mode of Kinesis streams, allowing users to easily identify whether a stream is provisioned or on-demand.
Added StreamModeDetails column to the Kinesis Stream table definition.
Updated logic to retrieve and display stream mode details.
Enhances the visibility of Kinesis stream configuration by indicating the stream mode.
Simplifies resource monitoring and management …

Add StreamModeDetails column to Kinesis stream table

---

aws/table_aws_accessanalyzer_analyzer.go
aws/table_aws_ecr_repository.go
aws/table_aws_ecrpublic_repository.go
aws/table_aws_glue_job.go
aws/table_aws_securityhub_finding.go
aws/table_aws_ses_domain_identity.go
aws/table_aws_ses_email_identity.go
aws/table_aws_ssm_document.go
aws/table_aws_vpc_security_group_rule.go

<details>
```
```
</details>
<details>
```
```
</details>

Remove the deprecated columns from the tables

---

aws/table_aws_iam_user.go
aws/table_aws_s3_bucket.go

This PR fixes the error handling for some APIs for the `table_aws_iam_user` and `table_aws_s3_bucket` table. If an error occurs (e.g., missing permissions for the respective API), a nil pointer dereference error is thrown.
<details>
```
```
</details>
<details>
```
```
</details>

Fixed error handling for table_aws_iam_user and table_aws_s3_bucket

---

aws/table_aws_ssm_document_permission.go

<details>
```
```
</details>
<details>
```
```
</details>

Fixed table `aws_ssm_document_permission` to handle  `InvalidDocument` error code

---

aws/table_aws_inspector2_finding.go

This PR adds the missing EPSS Score column to the `aws_inspector2_finding` table.
<details>
```
```
</details>
<details>
```
```
</details>

Adding EPSS Score Column

---

docs/tables/aws_accessanalyzer_analyzer.md
docs/tables/aws_rds_db_subnet_group.md
docs/tables/aws_ssm_document.md
docs/tables/aws_vpc_security_group.md
docs/tables/aws_vpc_security_group_rule.md

<details>
```
```
</details>
<details>
```
```
</details>

Update SQL queries to exclude removed table columns

---

aws/table_aws_inspector2_finding.go

This PR fixes a nasty bug which made the `aws_inspector2_finding` table returned no results if the SQL query contains the `<=` or `>=` operator for number or date columns.
To explain the bug take this query:
```sql
select
title,
epss_score
from
aws_inspector2_finding
where
epss_score >= 0.7
```
In this case, the call to the Inspector2 findings API should contain the NumberFilter for the EPSS score field with the field `LowerInclusive` and the value 0.7. However, in the code the SQL operator `>=` was mapped to the NumberFilter field `UpperInclusive`. This leads to the API response with exactly the opposite results we actually wanted to retrieve. When the list function returned the result list to Steampipe, the SQL query operator was applied to the result set, which then filtered out all …

Bug Fix: Wrong Comparison Operator for Number and Date Filter in `aws_inspector2_finding`

---

aws/table_aws_kms_key.go

<details>
```
```
</details>
<details>
```
> SELECT
substring(aliases[0] ->> 'AliasName' FROM 7) AS "alias",
arn,
creation_date,
multi_region,
multi_region_configuration ->> 'MultiRegionKeyType' AS key_type,
multi_region_configuration -> 'PrimaryKey' -> 'Arn' AS primary_key_arn
FROM
aws_kms_key
WHERE
aliases[0] ->> 'AliasName' NOT LIKE 'alias/aws/%'
ORDER BY
alias, arn
+-----------------------------------------------------------+-----------------------------------------------------------------------------+---------------------------+--------------+----------+-------------------------------------------------------------------------------+
| alias                                                     | …
```

feat: add `multi_region` and `multi_region_configuration` columns to `aws_kms_key` table

---

aws/table_aws_s3_bucket.go

<details>
```
```
</details>
<details>
Breaks: 
```
> select * from aws_s3_bucket
Error: aws: operation error S3: GetBucketWebsite, https response error StatusCode: 404, RequestID: 5F42KQGXEHF4XCKR, HostID: RjigpSaozYqUmuu33Jlgl1GdLxm811ewXfw7TvnyMBqdDCplwqJ+Peu8sr4j8iHGCoSiCEZ5gGo=, api error NoSuchWebsiteConfiguration: The specified bucket does not have a website configuration (SQLSTATE HV000)
+------+-----+---------------+-------------------------+--------------------+-----------------------+-------------------+---------------------+--------------------+-------------------------+----------------------->
| name | arn | creation_date | bucket_policy_is_public | versioning_enabled | …
```

Handle the "not found" error code in the getBucketTagging and getBucketWebsite functions Closes #2334

---

aws/table_aws_accessanalyzer_finding.go

This PR adds the following key columns for the list function of the `aws_accessanalyzer_finding` table:
- `error`
- `is_public`
- `resource_owner_account`
- `resource_type`
<details>
```
```
</details>
<details>
```
```
</details>

Additional Key Columns for `aws_accessanalyzer_finding` Table

---

aws/backup_tags.go
aws/table_aws_backup_plan.go
aws/table_aws_backup_recovery_point.go
aws/table_aws_backup_vault.go

<details>
```
```
</details>
<details>
```
> SELECT
name,
region,
tags
FROM aws_backup_plan
WHERE
name LIKE '%pdecat%'
+-----------------------+-----------+-------------------+
| name                  | region    | tags              |
+-----------------------+-----------+-------------------+
| test-pdecat-plan-tags | eu-west-3 | {"test":"pdecat"} |
+-----------------------+-----------+-------------------+
```
</details>

feat: add `tags` to `aws_backup_plan` table

---

aws/plugin.go
aws/table_aws_config_delivery_channel.go
docs/tables/aws_config_delivery_channel.md

<details>
```
```
</details>
<details>
```
select * from aws_config_delivery_channel
+---------+-----------------------------------------------------------------+----------------------------+---------------+----------------+------------------------------------------------->
| name    | arn                                                             | s3_bucket_name             | s3_key_prefix | s3_kms_key_arn | sns_topic_arn                                   >
+---------+-----------------------------------------------------------------+----------------------------+---------------+----------------+------------------------------------------------->
| default | …
```

Add aws_config_delivery_channel table closes #2325

---

aws/table_aws_rds_db_instance.go

<details>
```
```
</details>
<details>
```
> select db_instance_identifier, ca_certificate_identifier, certificate from aws_rds_db_instance
+------------------------+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
| db_instance_identifier | ca_certificate_identifier | certificate                                                                                                                                                                                                           > …
```

Fixed the error CertificateNotFound: Certificate rds-ca-2019 not found when querying RDS Instances Closes #2362

---

aws/plugin.go
aws/service.go
aws/table_aws_scheduler_schedule.go
docs/tables/aws_scheduler_schedule.md
go.mod
go.sum

<details>
```
N/A
```
</details>
<details>
```
> select * from aws_scheduler_schedule where state = 'ENABLED'
+----------+---------------------------------------------------------------------+---------+-------------+-------------------------+------------------------------+---------------------------+---------------------------+---------------------------+---------------------->
| name     | arn                                                                 | state   | description | schedule_expression     | schedule_expression_timezone | creation_date             | last_modification_date    | start_date                | end_date             >
+----------+---------------------------------------------------------------------+---------+----- …
```

Add table aws_scheduler_schedule Closes #2304

---

aws/plugin.go
aws/service.go
aws/table_aws_costoptimizationhub_recommendation.go
docs/tables/aws_costoptimizationhub_recommendation.md
go.mod
go.sum

<details>
```
```
</details>
<details>
```
> select * from aws_costoptimizationhub_recommendation
+----------------------------------------------------------------------+------------------------------------------------------------------+-----------------------+---------------------------+-------------+---------------+--------------------------+--------------------->
| recommendation_id                                                    | resource_arn                                                     | resource_id           | recommendation_account_id | action_type | currency_code | current_resource_summary | current_resource_typ>
+--------------------------------------------------------------------- …
```

Add table aws_costoptimizationhub_recommendation Closes #2350

---

aws/table_aws_glue_catalog_database.go
aws/table_aws_glue_connection.go
aws/table_aws_glue_crawler.go
aws/table_aws_glue_dev_endpoint.go
aws/table_aws_glue_job.go
aws/table_aws_glue_security_configuration.go

<details>
```
```
</details>
<details>
```
> SELECT
name,
akas,
tags
FROM
aws_glue_catalog_database
+----------------------------+-----------------------------------------------------------------------------+-------------------+
| name                       | akas                                                                        | tags              |
+----------------------------+-----------------------------------------------------------------------------+-------------------+
| default                    | ["arn:aws:glue:eu-west-3:012345678901:database/default"]                    | {}                |
| ec2_marketplace_offers     | ["arn:aws:glue:eu-west-3:012345678901:database/ec2_marketplace_ …
```

feat: add tags to most Glue tables

---

docs/tables/aws_cloudtrail_lookup_event.md

There was an error in a sample query on `aws_cloudtrail_lookup_event` [documentation page](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_cloudtrail_lookup_event):
This PR fix that

Fix query sample on `aws_cloudtrail_lookup_event` table documentation page

---

aws/table_aws_vpc_eip.go

Correct format is `arn:${Partition}:ec2:${Region}:${Account}:elastic-ip/${AllocationId}` (so `elastic-ip` instead of `eip`). 
Can be verified using [policy_sentry](https://policy-sentry.readthedocs.io/en/latest/querying/arn-table/): 
```
$ policy_sentry query arn-table --service ec2 --fmt json --list-arn-types
=> 
{
"elastic-ip": "arn:${Partition}:ec2:${Region}:${Account}:elastic-ip/${AllocationId}",
...
}
```
This format with `elastic-ip` is also the one appearing for the resource in the CUR.

Fix VPC Elastic IP ARNs in aws_vpc_eip table

---

aws/table_aws_ecs_service.go

<details>
```
```
</details>
<details>
```
> select service_name, tags_src, tags from aws_ecs_service;
+-----------------+-------------------------------------------------------------+-----------------------------+
| service_name    | tags_src                                                    | tags                        |
+-----------------+-------------------------------------------------------------+-----------------------------+
| test-53-service | [{"Key":"help","Value":"me"},{"Key":"foo1","Value":"bar1"}] | {"foo1":"bar1","help":"me"} |
+-----------------+-------------------------------------------------------------+-----------------------------+
```
</details>

Resolved `InvalidParameterException` in `aws_ecs_service` table when listing tags for older services. Closes #2388

---

aws/table_aws_wafregional_rule.go

<details>
```
```
</details>
<details>
Earlier:
```
> select name, region from aws_wafregional_rule;
+-----------------+--------+
| name            | region |
+-----------------+--------+
| turbottest64128 | global |
+-----------------+--------+
```
Now:
```
> select name, region from aws_wafregional_rule;
+-----------------+-----------+
| name            | region    |
+-----------------+-----------+
| turbottest64128 | us-east-1 |
| test2           | us-east-2 |
+-----------------+-----------+
```
</details>

Fixed aws_wafregional_rule table uses regional columns instead of global table columns Closes #2428

---

aws/table_aws_ses_domain_identity.go
aws/utils.go
docs/tables/aws_ses_domain_identity.md

<details>
```
```
</details>
<details>
```
select tags, title, region, _ctx from aws_ses_domain_identity
+-------------------+------------+-----------+-----------------------------------------------------------------------+
| tags              | title      | region    | _ctx                                                                  |
+-------------------+------------+-----------+-----------------------------------------------------------------------+
| {"test":"delete"} | abc.com | us-east-1 | {"connection_name":"test","steampipe":{"sdk_version":"5.10.4"}} |
+-------------------+------------+-----------+-----------------------------------------------------------------------+
> .cache clear
> …
```

Add tag retrieval example to `aws_ses_domain_identity table` documentation closes #2396

---

aws/table_aws_rds_db_instance.go

<details>
```
```
</details>
<details>
```
> select db_instance_identifier, ca_certificate_identifier, certificate from aws_rds_db_instance;
+------------------------+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
| db_instance_identifier | ca_certificate_identifier | certificate                                                                                                                                                                                                           > …
```

Fix nil pointer dereference when fetching certificate details for RDS Custom instance Closes #2435

---

aws/table_aws_ecr_image_scan_finding.go

<details>
```
```
</details>
<details>
```
> select
f.repository_name,
f.image_tag,
f.name,
f.severity,
jsonb_pretty(f.attributes) as attributes
from
(
select
repository_name,
jsonb_array_elements_text(image_tags) as image_tag
from
aws_ecr_image as i
)
images
left outer join
aws_ecr_image_scan_finding as f
on images.repository_name = f.repository_name
and images.image_tag = f.image_tag;
+-----------------+-----------+----------------+---------------+-----------------------------------------------------------------+
| repository_name | image_tag | name           | severity      | attributes                                                      | …
```

Add parent hydrate support for the  table aws_ecr_image_scan_finding to manage the complex join queries Closes #2367

---

aws/service.go
aws/table_aws_health_affected_entity.go
aws/table_aws_health_event.go

<details>
```
```
</details>
<details>
```
```
</details>

Fix aws_health_* tables to correctly reference the Global endpoint instead of regional endpoint closes #2449

---

aws/table_aws_ssoadmin_permission_set.go

This PR adds two columns, `inline_policy` and `inline_policy_std`, to the `aws_ssoadmin_permission_set` table using the [sso:GetInlinePolicyForPermissionSet](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_GetInlinePolicyForPermissionSet.html) API.
<details>
```
N/A
```
</details>
<details>
```
select 
arn, 
inline_policy 
from aws_ssoadmin_permission_set
+-------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| arn                                                                     | inline_policy …
```

Inline policy for Identity Center Permission Sets

---

aws/table_aws_health_event.go

<details>
```
```
</details>
<details>
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

feat: add column `description` to `aws_health_event` table

---

aws/table_aws_transfer_server.go

<details>
```
```
</details>
<details>
```
> select server_id, tags_src, tags from aws_transfer_server;
+---------------------+-------------------------------+---------------+
| server_id           | tags_src                      | tags          |
+---------------------+-------------------------------+---------------+
| s-d2195f72b96646f78 | [{"Key":"foo","Value":"bar"}] | {"foo":"bar"} |
+---------------------+-------------------------------+---------------+
```
</details>

Fix the column `tags` to populate the value correctly for the table `aws_transfer_server` Closes #2483

---

aws/plugin.go
aws/service.go
aws/table_aws_rolesanywhere_profile.go
aws/table_aws_rolesanywhere_trust_anchor.go
docs/tables/aws_rolesanywhere_profile.md
docs/tables/aws_rolesanywhere_trust_anchor.md
go.mod
go.sum

This PR adds two new tables for the [Roles Anywhere](https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html) service. Specifically, it adds support for enumerating Trust Anchors (`aws_rolesanywhere_trust_anchor`) and Profiles (`aws_rolesanywhere_profile`).
<details>
```
select 
arn, 
inline_policy 
from aws_rolesanywhere_profile
+-------------------------------------------------------------------------------------------+----------------------------------------------------------------+
| arn                                                                                       | role_arns                                                      |
+-------------------------------------------------------------------------------------------+--------- …
```

Tables for Roles Anywhere Profiles and Trust Anchors

---

CHANGELOG.md
aws/plugin.go
aws/table_aws_cognito_user_group.go
docs/tables/aws_cognito_user_group.md

<details>
```
```
</details>
<details>
```
> select * from aws_cognito_user_group;
+-------------+---------------------+------------------------------------------------------+---------------------------+---------------------------+------------+----------------------------------------------------------------+-------------+--->
| group_name  | user_pool_id        | description                                          | creation_date             | last_modified_date        | precedence | role_arn                                                       | title       | ak>
+-------------+---------------------+------------------------------------------------------+---------------------------+----------------- …
```

Add table aws_cognito_user_group

---

aws/plugin.go
aws/table_aws_codebuild_fleet.go
docs/tables/aws_codebuild_fleet.md

<details>
```
```
</details>
<details>
```
> select * from aws_codebuild_fleet
+--------------------+--------------------------------------------------------------------------------------------------------+---------------+---------------------------+--------->
| name               | arn                                                                                                    | base_capacity | created                   | last_mod>
+--------------------+--------------------------------------------------------------------------------------------------------+---------------+---------------------------+--------->
| my-codebuild-fleet | arn:aws:codebuild:us-east-1:123456789012:fleet/my-codebuild-fl …
```

Add table aws_codebuild_fleet

---

aws/table_aws_lambda_function.go

<details>
```
```
</details>
<details>
```
select title, ephemeral_storage from aws_lambda_function
+-----------------------------------------------------------+-------------------+
| title                                                     | ephemeral_storage |
+-----------------------------------------------------------+-------------------+
| SecurityLake_Glue_Partition_Updater_Lambda_us-west-2      | {"Size":512}      |
| testfn                                                    | {"Size":512}      |
| test-node-lambda                                          | {"Size":512}      |
| aws-quicksetup-lifecycle-LA-l07up                         | {"Size":512}      |
| SampleLambda-test-lambda-log …
```

Add column ephemeral_storage to aws_lambda_function table closes #2504

---

aws/table_aws_rds_db_instance.go
aws/table_aws_rds_pending_maintenance_action.go

<details>
```
```
</details>
<details>
```
Before the fix:
> select
a.db_instance_identifier,
b.action,
a.status,
b.opt_in_status,
b.forced_apply_date,
b.current_apply_date,
b.auto_applied_after_date
from
aws_rds_db_instance as a
join aws_rds_pending_maintenance_action as b on b.resource_identifier = a.arn;
Error: aws_a: operation error RDS: DescribePendingMaintenanceActions, https response error StatusCode: 400, RequestID: b6c9c600-35e3-4969-9340-8a20782ef111, api error InvalidParameterValue: The parameter Filter: resource-id is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive …
```

Add ignore error config to aws_rds_db_instance and aws_rds_pending_maintenance_action tables fixes #2543

---

aws/plugin.go

This PR adds a few more rate limiters for the AWS CloudFront, Kinesis, Route53, WAF Classic and WAF v2 services.

feat: add a few more rate limiters

---

aws/table_aws_cloudformation_stack.go
docs/tables/aws_cloudformation_stack.md

<details>
```
```
</details>
<details>
```
> select name, status from aws_cloudformation_stack;
+---------------------------------------------------------------------------+-----------------+
| name                                                                      | status          |
+---------------------------------------------------------------------------+-----------------+
| AWS-QuickSetup-SSM-LocalDeploymentRolesStack                              | CREATE_COMPLETE |
| StackSet-AWS-QuickSetup-SSM-LA-l07up-76f5313f-3905-4a4c-ae1b-b649cf3abe06 | CREATE_COMPLETE |
| test-ecs-35                                                               | DELETE_COMPLETE |
| my-vpc-stack …
```

Added support to the table aws_cloudformation_stack to fetch the stack with DELETE_COMPLETE state Closes #2542

---

aws/connection_config.go
aws/errors.go
config/aws.spc
docs/index.md

<details>
```
> select * from aws_trusted_advisor_check_summary where language = 'en'
Error: aws: operation error Support: DescribeTrustedAdvisorChecks, https response error StatusCode: 400, RequestID: 3cdb0e8d-57aa-4327-8308-c911f963a77e, api error SubscriptionRequiredException: Amazon Web Services Premium Support Subscription is required to use this service. (SQLSTATE HV000)
+------+----------+----------+----------+-------------+--------+-----------+-------------------+-------------------+---------------------+----------------------+------------->
| name | check_id | category | language | description | status | timestamp | resources_flagged | resources_ignored | resources_processed | resources_suppressed | category_spe> …
```

Added support for `ignore_error_messages` config arg to ignore errors by message Closes #2517

---

aws/plugin.go
aws/table_aws_glue_ml_transform.go
docs/tables/aws_glue_ml_transform.md

<details>
```
```
</details>
<details>
```
> select * from aws_glue_ml_transform
+----------------------------------------------+------------------------------------------+-------------+-----------+---------------------------+---------------------------+--------------+-------------+----------->
| transform_id                                 | name                                     | description | status    | created_on                | last_modified_on          | glue_version | label_count | max_capaci>
+----------------------------------------------+------------------------------------------+-------------+-----------+---------------------------+---------------------------+--------------+----------- …
```

Add table aws_glue_ml_transform Closes #2605

---

aws/table_aws_availability_zone.go

Note: It is a known error that the Steampipe SDK is failing to respect if the `ParentHydrate` is being used in the table. So we need to handle it in the LIST function itself
<details>
```
```
</details>
<details>
```
```
</details>

Fix the table aws_availability_zone to respect `ignore_error_codes` and  `ignore_error_messages` from connection config

---

aws/table_aws_cloudformation_stack_resource.go
docs/tables/aws_cloudformation_stack_resource.md

<details>
```
```
</details>
<details>
```
> select * from aws_cloudformation_stack_resource
+-----------------------------------------+---------------------------------------------------------------------------+------------------------------------------------------------->
| logical_resource_id                     | stack_name                                                                | stack_id                                                    >
+-----------------------------------------+---------------------------------------------------------------------------+------------------------------------------------------------->
| LocalAdministrationRole                 | …
```

Enhance aws_cloudformation_stack_resource table to search by `physical_resource_id` and added new column `metadata` #2627
