- aws-test/tests/aws_s3_bucket/test-hydrate-expected.json
- aws-test/tests/aws_s3_bucket/test-list-expected.json
- aws/table_aws_s3_bucket.go
```
> select name, jsonb_pretty(lifecycle_rules) from aws_s3_bucket;
+------------------------------------+------------------------------------------------+
| NAME                               | JSONB_PRETTY                                   |
+------------------------------------+------------------------------------------------+
| abhi-trustedaccess-test            |                                                |
| tests8899                          | [                                              |
|                                    |     {                                          |
|                                    |         "ID": "rule 1",                        |
|                                    |         "Filter": {                            |
| …
```
> aws_s3_bucket.lifecycle_rules should return an array, not a single field object. Closes #26

- aws-test/tests/aws_rds_db_cluster/test-get-expected.json
- aws-test/tests/aws_rds_db_cluster/test-get-query.sql
- aws-test/tests/aws_rds_db_cluster/test-hydrate-expected.json
- aws-test/tests/aws_rds_db_cluster/test-hydrate-query.sql
- aws-test/tests/aws_rds_db_cluster_parameter_group/test-hydrate-expected.json
- aws-test/tests/aws_rds_db_cluster_parameter_group/test-hydrate-query.sql
- aws-test/tests/aws_rds_db_cluster_snapshot/test-get-expected.json
- aws-test/tests/aws_rds_db_cluster_snapshot/test-get-query.sql
- aws-test/tests/aws_rds_db_instance/test-get-expected.json
- aws-test/tests/aws_rds_db_instance/test-get-query.sql
- aws-test/tests/aws_rds_db_instance/test-hydrate-expected.json
- aws-test/tests/aws_rds_db_instance/test-hydrate-query.sql
- aws-test/tests/aws_rds_db_option_group/test-hydrate-expected.json
- aws-test/tests/aws_rds_db_option_group/test-hydrate-query.sql
- aws-test/tests/aws_rds_db_parameter_group/test-hydrate-expected.json
- aws-test/tests/aws_rds_db_parameter_group/test-hydrate-query.sql
- aws-test/tests/aws_rds_db_snapshot/test-get-expected.json
- aws-test/tests/aws_rds_db_snapshot/test-get-query.sql
- aws-test/tests/aws_rds_db_subnet_group/test-hydrate-expected.json
- aws-test/tests/aws_rds_db_subnet_group/test-hydrate-query.sql
- aws/table_aws_rds_db_cluster.go
- aws/table_aws_rds_db_cluster_parameter_group.go
- aws/table_aws_rds_db_cluster_snapshot.go
- aws/table_aws_rds_db_instance.go
- aws/table_aws_rds_db_option_group.go
- aws/table_aws_rds_db_parameter_group.go
- aws/table_aws_rds_db_snapshot.go
- aws/table_aws_rds_db_subnet_group.go
> aws_rds_* tables should have `tags_src` column (not `tag_list`). Closes #56

- aws/table_aws_availability_zone.go
- aws/table_aws_ec2_instance_availability.go
…n zones that arent opted-in. Closes #162
> check opt-in status in aws_availability_zone to resolve AuthFailure on zones that aren't opted-in. Closes #162

- aws/table_aws_lambda_version.go
<details>
```
➜  aws-test git:(issue-189) ./tint.js aws_lambda_version
SETUP: tests/aws_lambda_version []
PRETEST: tests/aws_lambda_version
TEST: tests/aws_lambda_version
local_file.python_file: Creating...
local_file.python_file: Creation complete after 0s [id=31a055a187e07d0bd8fca8ceb1f633aa4497fe53]
data.archive_file.zip: Reading...
data.archive_file.zip: Read complete after 0s [id=3d2780bc13324b697460b666c413908a395d952e]
aws_iam_role.aws_lambda_function: Creating...
aws_iam_role.aws_lambda_function: Creation complete after 5s [id=turbottest10743] …
```
> Fix: aws_lambda_version breaking for query on function_name and version field. Closes #189

- docs/tables/aws_ec2_autoscaling_group.md
<details>
```
<N/A>
```
</details>
<details>
```
<N/A>
```
</details>
> [FIX] The doc link should indicate exact table name. Closes #266

- aws/service.go
<details>
```
N/A
```
</details>
<details>
```
N/A
```
</details>
> [FIX] Remove duplicate service connection. Closes #301

- aws/table_aws_s3_bucket.go
<details>
```
```
</details>
<details>
```sql
> select arn from aws_s3_bucket where name like 'dmi%';
+-------------------------------------+
| arn                                 |
+-------------------------------------+
| arn:aws:s3:::dmi-data-lake-metadata |
| arn:aws:s3:::dmi-employee-data      |
| arn:aws:s3:::dmi-data-wrangling     |
+-------------------------------------+
```
</details>
> Add ARN column to aws_s3_bucket table

- aws-test/tests/aws_iam_account_password_policy/test-get-expected.json
- aws/table_aws_iam_account_password_policy.go
<details>
```
SETUP: tests/aws_iam_account_password_policy []
PRETEST: tests/aws_iam_account_password_policy
TEST: tests/aws_iam_account_password_policy
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "aws iam get-account-password-policy --output json --profile default --region us-east-1 > /private/var/folders/5q/jqv70bxs7g73gwgv5tvl80l40000gn/T/tests/aws_iam_account_password_policy/terraform/test/output.json"] …
```
> table_aws_iam_account_password_policy fails with Error: NoSuchEntity: The Password Policy with domain name 123456789012 cannot be found. closes #369

- aws/table_aws_elasticache_cluster.go
<details>
```
SETUP: tests/aws_elasticache_cluster []
PRETEST: tests/aws_elasticache_cluster
TEST: tests/aws_elasticache_cluster
aws_vpc.my_vpc: Still creating... [10s elapsed]
aws_vpc.my_vpc: Creation complete after 11s [id=vpc-042c8108efe2304a4]
aws_subnet.my_subnet: Creating...
aws_subnet.my_subnet: Creation complete after 3s [id=subnet-0c903c50b2cb9b02d]
aws_elasticache_subnet_group.my_subnet_group: Creating...
aws_elasticache_subnet_group.my_subnet_group: Creation complete …
```
> Getting 404 error when elasticache cluster is in creating state. closes  #446

- aws/service.go
<details>
```
```
</details>
<details>
```
```
</details>
> update cache key for services in service.go file. Closes #499

- aws/cloudwatch_metric.go
<details>
```
```
</details>
<details>
```
```
</details>
> A spelling correction required. Closes #504

- docs/index.md
- scripts/mfa.sh
<details>
```
```
</details>
<details>
```
```
</details>
> updated docs/index.md with expanded credential options

- aws/table_aws_ecs_task_definition.go
Descriptions from: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinition.html
> Update ECS table descriptions

- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
N/A
```
</details>
> Update steampipe-plugin-sdk to v1.3.1. Closes #559

- aws/multi_region.go
- aws/service.go
- aws/table_aws_wafv2_ip_set.go
- go.mod
- go.sum
<details>
```
connection "aws_osborn" {
plugin  = "aws"
profile = "osborn"
regions = ["ap-southeast-?"]
}
> select topic_arn, region, subscriptions_confirmed, subscriptions_deleted from aws_osborn.aws_sns_topic
+----------------------------------------------------------------+----------------+-------------------------+-----------------------+
| topic_arn                                                      | region         | subscriptions_confirmed | subscriptions_deleted |
+----------------------------------------------------------------+----------------+-------------------------+-----------------------+
| arn:aws:sns:ap-southeast-1:123456789321:turbot_aws_api_handler | ap-southeast-1 | 3                       | 0                     | …
```
> Update error message in case the set region/regions in connection config is not valid. Closes #543

- aws/multi_region.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix: multi-region configuration to pick correct region from connection config. #543

- docs/index.md
Docs updates - dont merge / releasee until steampip 0.7.0 is out
> updated docs/index.md for aggregators

- aws/plugin.go
- aws/table_aws_lambda_function_metric_invocations_daily.go
- docs/tables/aws_lambda_function_metric_invocations_daily.md
<details>
```
> select
name,
timestamp,
sum
from
aws_lambda_function_metric_invocations_daily
order by
name,
timestamp;
+-----------------------------------------------------------------+---------------------+------+
| name                                                            | timestamp           | sum  |
+-----------------------------------------------------------------+---------------------+------+
| GitStack-GitLookerA37793FB-ZYgxqb22sQii                         | 2021-08-17 06:00:00 | 56   |
| GitStack-GitLookerA37793FB-ZYgxqb22sQii                         | 2021-08-18 06:00:00 | 2    |
| GitStack-GitLookerA37793FB-ZYgxqb22sQii                         | 2021-08-19 06:00:00 | 1    |
| GitStack-GitLookerA37793FB-ZYgxqb22sQii                         | …
```
> Add table aws_lambda_function_metric_invocations_daily

- aws/service.go
- aws/table_aws_ec2_instance.go
- aws/table_aws_iam_credential_report.go
With 5s minimum retry delay
```
2021-09-02T14:12:42.045+0530 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] NewConnectionErrRetryer:: DefaultRetryer:=5
2021-09-02T14:12:42.078+0530 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] inside_ShouldRetry:: EXTRA_VALUE_AT_END="RequestError: send request failed
2021-09-02T14:12:42.078+0530 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] RetryRules:: current_delay:=5s
2021-09-02T14:12:47.081+0530 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] inside_ShouldRetry:: EXTRA_VALUE_AT_END="RequestError: send request failed
2021-09-02T14:12:47.081+0530 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] RetryRules:: current_delay:=20s
2021-09-02T14:13:07.084+0530 [ERROR] plugin.steampipe-plugin-aws.plugin: [ERROR] inside_ShouldRetry:: …
```
> Add customized exponential backoff retry. Closes#634

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.32.1 closes #654

- aws/table_aws_iam_credential_report.go
<details>
```
```
</details>
<details>
```
```
</details>
> Revert handling <root_account> password_enabled check in table_aws_iam_credential_report table.Closes #656

- aws/table_aws_ecs_task.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix getting duplicate task in aws_ecs_task table. Closes #725

- go.mod
- go.sum
<details>
```
select name, opt_in_status from aws_region
+----------------+---------------------+
| name           | opt_in_status       |
+----------------+---------------------+
| us-east-2      | opt-in-not-required |
| eu-west-1      | opt-in-not-required |
| us-west-1      | opt-in-not-required |
| sa-east-1      | opt-in-not-required |
| us-east-1      | opt-in-not-required |
| eu-west-2      | opt-in-not-required |
| ap-southeast-2 | opt-in-not-required |
| ap-northeast-1 | opt-in-not-required |
| eu-central-1   | opt-in-not-required |
| ap-east-1      | not-opted-in        |
| ca-central-1   | opt-in-not-required |
| eu-south-1     | not-opted-in        |
| eu-west-3      | opt-in-not-required |
| us-west-2      | opt-in-not-required |
| ap-southeast-1 | …
```
> Recompiled plugin with steampipe-plugin-sdk v1.7.3

- aws/table_aws_backup_vault.go
- docs/tables/aws_backup_vault.md
<details>
```
arnab@turbotindias-MacBook-Pro aws-test % ./tint.js aws_backup_vault
SETUP: tests/aws_backup_vault []
PRETEST: tests/aws_backup_vault
TEST: tests/aws_backup_vault
+ create
+ resource "aws_backup_vault" "named_test_resource" {
+ arn             = (known after apply)
+ id              = (known after apply)
+ kms_key_arn     = (known after apply)
+ name …
```
> Add policy_std column to the aws_backup_vault table. Closes #720

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.39.1

- aws/table_aws_vpc_route.go
conatining -> containing
<details>
```
```
</details>
<details>
```
```
</details>
> Fix small typo

- aws-test/tests/aws_codebuild_project/test-get-expected.json
- aws-test/tests/aws_codebuild_project/test-list-expected.json
- aws-test/tests/aws_ec2_ami_shared/test-list-query.sql
- aws-test/tests/aws_rds_db_cluster/test-get-expected.json
- aws-test/tests/aws_rds_db_cluster/test-hydrate-expected.json
- aws-test/tests/aws_rds_db_cluster_snapshot/test-get-expected.json
- aws-test/tests/aws_rds_db_instance/test-get-expected.json
- aws-test/tests/aws_rds_db_instance/test-hydrate-expected.json
- aws_codebuild_project
- aws_ec2_ami_shared
- aws_rds_db_cluster
- aws_rds_db_cluster_snapshot
- aws_rds_db_instance
> Fix integration tests for steampipe-plugin-sdk v1.8.1-beta.0 #788

- .github/workflows/registry-publish.yml
- go.mod
<details>
```
select name, create_date from aws_iam_user
+------------------+----------------------+
| name             | create_date          |
+------------------+----------------------+
| sourav           | 2021-08-20T05:55:08Z |
| venu@turbot.com  | 2021-11-16T11:36:52Z |
| partha           | 2021-08-18T16:28:00Z |
| partha-console   | 2021-08-19T09:44:05Z |
| lalit@turbot.com | 2020-08-27T09:31:45Z |
| ved              | 2021-08-20T08:02:24Z |
| user-steampipe   | 2021-03-02T05:58:58Z |
| raj              | 2021-08-20T08:03:55Z |
| mike@turbot.com  | 2021-09-28T12:51:10Z |
| steampipe-cloud  | 2021-09-28T12:22:07Z |
| khushboo         | 2021-08-25T07:06:11Z |
| arnab            | 2021-08-11T07:55:20Z 
```
</details>
> Recompiled plugin with Go version 1.17

- docs/tables/aws_rds_db_instance.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update the `rds_db_instance` table document

- aws/table_aws_ec2_ami.go
- aws/table_aws_ec2_ami_shared.go
- aws/table_aws_iam_policy.go
<details>
```
> select title, image_owner_alias from aws_ec2_ami where public = 'false'
+--------------------------------------------------------------------+-------------------+
| title                                                              | image_owner_alias |
+--------------------------------------------------------------------+-------------------+
| test                                                               | self              |
| AwsBackup_i-006ae642663c062d2_74b4a4ea-2d54-474d-9550-b1e22e40de68 | self              |
+--------------------------------------------------------------------+-------------------+
> select title, image_owner_alias from aws_ec2_ami_shared where owner_id = '533793682495' …
```
> Fixed image_owner_alias column null value issue in aws_ec2_ami and aws_ec2_ami_shared table. Fixes #840

- go.mod
- go.sum
<details>
```
N/A
```
</details>
> Update the AWS SDK version to the latest closes #844

- aws/multi_region.go
- aws/service.go
- aws/table_aws_workspaces_workspace.go
<details>
```
> select * from aws_workspaces_workspace where workspace_id = 'ws-874kdm8yw'
+--------------+----------------+------------------------------------------------------------------+---------------+--------------+-----------+------------+---------------+---------------+----------------
| workspace_id | name           | arn                                                              | bundle_id     | directory_id | state     | error_code | error_message | ip_address    | root_volume_enc
+--------------+----------------+------------------------------------------------------------------+---------------+--------------+-----------+------------+---------------+---------------+----------------
| ws-874kdm8yw | A-NCDOKGV5P2CR | …
```
> Add check for unsupported regions for workspaces service using endpoints package. Fixes #861

- aws/table_aws_lambda_function.go
- aws/table_aws_lambda_layer.go
- aws/table_aws_lambda_layer_version.go
- aws/table_aws_lambda_version.go
<details>
```
> select name, handler, last_modified from aws_lambda_function
+-----------------------------------------------------------------+--------------------------------+---------------------------+
| name                                                            | handler                        | last_modified             |
+-----------------------------------------------------------------+--------------------------------+---------------------------+
| test1                                                           | index.handler                  | 2022-01-28T11:44:53+05:30 |
| tets                                                            | index.handler                  | 2021-05-28T17:29:42+05:30 |
| SecretsManagermysqldb-admin-cred …
```
> Update created_date, last_modified column type in lamda_* table

- aws/table_aws_dax_cluster.go
<details>
```
> select cluster_name, arn, node_type from aws_dax_cluster
+--------------+-------------------------------------------------+--------------+
| cluster_name | arn                                             | node_type    |
+--------------+-------------------------------------------------+--------------+
| test1        | arn:aws:dax:ap-south-1:533793682495:cache/test1 | dax.r5.large |
+--------------+-------------------------------------------------+--------------+
> select cluster_name, arn, node_type from aws_dax_cluster where cluster_name = 'test1'
+--------------+-------------------------------------------------+--------------+
| cluster_name | arn                                             | node_type    | …
```
> Add valid region check for Dax cluster and fix tag column issue in aws_dax_cluster table.

- aws/plugin.go
- aws/table_aws_servicequotas_service_quota_change_request.go
- docs/tables/aws_servicequotas_service_quota_change_request.md
<details>
```
Integration test is not feasible 
```
</details>
<details>
```
> select * from aws_servicequotas_service_quota_change_request where status = 'APPROVED'
+------------------------------------------+---------+----------+--------------------+------------+-----------------------------------------------------------------+---------------+-----------------------
| id                                       | case_id | status   | quota_name         | quota_code | quota_arn                                                       | desired_value | created               
+------------------------------------------+---------+----------+--------------------+------------+-----------------------------------------------------------------+-------- …
```
> Add table aws_servicequotas_service_quota_change_request. Closes #888

- aws/table_aws_servicequotas_service_quota_change_request.go
<details>
```
```
</details>
<details>
```
```
</details>
> Update the steampipe plugin  sdk version in aws_servicequotas_service_quota_change_request table

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.49.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.50.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.50.1

- aws/table_aws_securityhub_standards_subscription.go
<details>
```
N/A
```
</details>
<details>
```
> select name, status_reason_code from aws_securityhub_standards_subscription
+-------------------------------------------------+-------------------------------------+
| name                                            | standards_status_reason_code        |
+-------------------------------------------------+-------------------------------------+
| CIS AWS Foundations Benchmark v1.2.0            | <null>                              |
| AWS Foundational Security Best Practices v1.0.0 | <null>                              |
| PCI DSS v3.2.1                                  | <null>                              |
| AWS Foundational Security Best Practices v1.0.0 | <null> …
```
> Add column standards_status_reason_code to table aws_securityhub_standards_subscription closes #929

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
select * from aws_s3_bucket limit 1
+------------+-------------------------+---------------------------+-------------------------+--------------------+-----------------------+-------------------+---------------------+----------
| name       | arn                     | creation_date             | bucket_policy_is_public | versioning_enabled | versioning_mfa_delete | block_public_acls | block_public_policy | ignore_pu
+------------+-------------------------+---------------------------+-------------------------+--------------------+-----------------------+-------------------+---------------------+----------
| 64yr5trbds | arn:aws:s3:::64yr5trbds | …
```
> Recompile plugin with steampipe-plugin-sdk v2.1.1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.52.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.55.0

- aws/connection_config.go
- aws/service.go
- config/aws.spc
- docs/index.md
<details>
```
N/A
```
</details>
<details>
```
N/A
```
</details>
> Add support for custom retry count closes #913

- aws/table_aws_iam_user.go
<details>
```
```
</details>
<details>
```
> select name, login_profile from aws_iam_user
+------------------+---------------------------------------------------------------------------------------------------+
| name             | login_profile                                                                                     |
+------------------+---------------------------------------------------------------------------------------------------+
| partha-console   | {"CreateDate":"2021-08-19T09:44:07Z","PasswordResetRequired":false,"UserName":"partha-console"}   |
| abc@xxxxxx.com   | {}                                                                                                |
| …
```
> Add login profile for table aws_iam_user closes #899

- aws/table_aws_s3_bucket.go
<details>
```
```
</details>
<details>
```
> select name, jsonb_pretty(event_notification_configuration) as event_notification_configuration  from aws_s3_bucket
+-------------------------------------------+-----------------------------------------------------------------------------------------------+
| name                                      | event_notification_configuration                                                              |
+-------------------------------------------+-----------------------------------------------------------------------------------------------+
| turbot-632902152528-ap-south-1            | { …
```
> Add Event Notifications Detail in table aws_s3_bucket closes #940

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.56.0

- aws/table_aws_lambda_function.go
- aws/table_aws_lambda_version.go
<details>
```
> select version, function_name, environment_variables from aws_lambda_version
+---------+-----------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| version | function_name                                                   | environment_variables                                                                                        |
+---------+-----------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| $LATEST | test1                                                           | <null> …
```
> Remove extra FromField for environment_variables column in aws_lambda_version table 

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.58.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.59.0

- aws/plugin.go
- aws/table_aws_inspector_exclusion.go
- docs/tables/aws_inspector_exclusion.md
<details>
```
```
</details>
<details>
```
> select
arn,
attributes,
description,
title,
region
from
test_aab.aws_inspector_exclusion;
+--------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+----------------------------->
| arn                                                                                                                | attributes                                            | description                 >
+--------------------------------------------------------------------------------------------------------------------+----------------------------------------------- …
```
> Add table aws_inspector_exclusion. Closes #1034

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.60.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.61.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.62.0

- aws/plugin.go
- aws/table_aws_ssm_inventory.go
- docs/tables/aws_ssm_inventory.md
<details>
```
N/A
```
</details>
<details>
```
> select * from aws_ssm_inventory
+---------------------+-------------------------+----------------------+----------------+-----------------------------------------------------------------------------------------------------------------
| instance_id         | type_name               | capture_time         | schema_version | content                                                                                                         
+---------------------+-------------------------+----------------------+----------------+-----------------------------------------------------------------------------------------------------------------
| i-0665a65b1a1c2b64f | AWS:InstanceInformation | …
```
> Add table aws_ssm_inventory closes #1041

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.64.0

- .gitignore
Updated `.gitignore` to ignore all the files in the folder `.vscode` 
Previously it only ignored the `launch.json` file.
> Widen .gitignore to include all VS Code user settings

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.65.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.66.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.67.0

- aws/common_columns.go
- aws/plugin.go
- aws/service.go
- aws/table_aws_s3_bucket.go
- aws/table_aws_service_attribute.go
- docs/tables/aws_service_attribute.md
<details>
```
> select
service_code,
attribute_name,
attribute_values
from
aws_service_attribute
where
service_code = 'AWSBackup';
+--------------+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| service_code | attribute_name    | attribute_values                                                                                                                                                                 
+--------------+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Add table aws_service_attribute. Closes #1135

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.69.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update CHANGELOG for v0.70.0

- aws/table_aws_ecs_cluster.go
<details>
```
> select cluster_name, jsonb_pretty(settings) as settings, jsonb_pretty(statistics) as statistics, jsonb_pretty(attachments) as attachments  from aws_ecs_cluster
+--------------+--------------------------------------+-------------------------------------------------+-------------+
| cluster_name | settings                             | statistics                                      | attachments |
+--------------+--------------------------------------+-------------------------------------------------+-------------+
| test         | [                                    | [                                               | [           |
|              |     {                                |     {                                           | ] …
```
> Fix settings column issue in table aws_ecs_cluster. Fixes #1165

- docs/tables/aws_sns_topic.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update the example query in the aws_sns_topic.md file

- aws/table_aws_route53_record.go
- docs/tables/aws_route53_record.md
<details>
```
> select zone_id, name, type, jsonb_pretty(records) as records from aws_route53_record where zone_id = 'Z07961652UZFFINSTYHRV'
+-----------------------+-----------------+------+------------------------------------------------------------------------------------+
| zone_id               | name            | type | records                                                                            |
+-----------------------+-----------------+------+------------------------------------------------------------------------------------+
| Z07961652UZFFINSTYHRV | codybruno2.com. | NS   | [                                                                                  |
|                       |                 |      |     "ns-181.awsdns-22.com.", …
```
> Re-enable `name` and `type` optional list quals in `aws_route53_record` table. Closes #1066

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.73.0

- aws/plugin.go
- aws/table_aws_dynamodb_table_export.go
- docs/tables/aws_dynamodb_table_export.md
<details>
```
```
</details>
<details>
```
> select
arn,
end_time,
export_format,
export_status,
s3_bucket
from
aws_aab.aws_dynamodb_table_export;
+------------------------------------------------------------------------------------------+---------------------------+---------------+---------------+-----------------------+
| arn                                                                                      | end_time                  | export_format | export_status | s3_bucket             |
+------------------------------------------------------------------------------------------+---------------------------+---------------+---------------+-----------------------+
| …
```
> Add table aws_dynamodb_table_export closes #1208

- aws/table_aws_ecs_container_instance.go
<details>
```
```
</details>
<details>
```
> select
ec2_instance_id,
cluster_arn,
status
from 
aws_ecs_container_instance
+---------------------+--------------------------------------------------------+--------+
| ec2_instance_id     | cluster_arn                                            | status |
+---------------------+--------------------------------------------------------+--------+
| i-094b4c6c196d31234 | arn:aws:ecs:us-east-1:12345678910:cluster/test2   | ACTIVE |
| i-009806d97f6201234 | arn:aws:ecs:sa-east-1:12345678910:cluster/test1   | ACTIVE |
| i-09962947de28a1234 | arn:aws:ecs:ap-south-1:12345678910:cluster/test3      | ACTIVE |
| i-077702cd75efe1234 | …
```
> Add cluster_arn column in table aws_ecs_container_instance Closes #1237

- aws/plugin.go
- aws/table_aws_eks_node_group.go
- docs/tables/aws_eks_node_group.md
<details>
```
Not Feasible. Node group creation takes too much time.
```
</details>
<details>
```
> select
nodegroup_name,
arn,
created_at,
cluster_name,
status
from
aws_eks_node_group;
+----------------+--------------------------------------------------------------------------------------------------+---------------------------+--------------+---------------+
| nodegroup_name | arn                                                                                              | created_at                | cluster_name | status        |
+----------------+--------------------------------------------------------------------------------------------------+---------------------------+--------------+---------------+
| tertt          | …
```
> Add table aws_eks_node_group. Closes #1235

- aws/service.go
- aws/service_v2.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix route53 service connection

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with steampipe-plugin-sdk v4.1.1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.74.0

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with steampipe-plugin-sdk v4.1.2

- aws/service.go
- aws/service_v2.go
These fixes are important to release ASAP ... I'm not sure how much the bad caching might affect behavior.
> Fixes for credential caching

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with v4.1.2

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.74.1

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with steampipe-plugin-sdk v4.1.3

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with steampipe-plugin-sdk v4.1.4

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.74.2

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.75.0

- .github/workflows/registry-publish.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Update registry-publish.yml workflow to address breaking changes

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.76.0

- aws/table_aws_iam_access_key.go
<details>
```
```
</details>
<details>
```
```
</details>
> Add columns access_key_last_used_date, access_key_last_used_region and access_key_last_used_service to aws_iam_access_key table closes #1240

- docs/index.md
<details>
```
```
</details>
<details>
```
```
</details>
> extended Configuring AWS Credentials with hop-off case

- aws/table_aws_acm_certificate.go
<details>
```
```
</details>
<details>
**Earlier** 
```
> select * from aws_acm_certificate
Error: failed to populate column 'title': rpc error: code = Internal desc = transform certificateArnToTitle failed with panic interface conversion: interface {} is *string, not string (SQLSTATE HV000)
```
```
select title from aws_acm_certificate
+--------------------------------------+
| title                                |
+--------------------------------------+
| d1865da1-1742-4d11-9a2a-86acc3cea48f |
| 24c967dc-da4a-4ed7-9866-019f766ae32b |
+--------------------------------------+
> select * from aws_acm_certificate
+-------------------------------------------------------------------------------------+----------------
| …
```
> Fix ACM list api call

- aws/table_aws_iam_role.go
- aws/table_aws_iam_user.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix duplicate values in inline_policies column of aws_iam_user and aws_iam_role tables closes #1343

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.81.1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update the CHANGELOG of v0.81.1 release

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.82.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.84.0

- aws/multi_region.go
```
plugins/steampipe-plugin-aws|main⚡ ⇒  aws configure list
Name                    Value             Type    Location
----                    -----             ----    --------
profile                <not set>             None    None
access_key     ****************7UAH shared-credentials-file    
secret_key     ****************/g/w shared-credentials-file    
region                <not set>             None    None
plugins/steampipe-plugin-aws|main⚡ ⇒  steampipe query
Welcome to Steampipe v0.18.0-alpha.1
> select topic_arn, region from aws_sns_topic
Error: you must specify a region in "regions" in ~/.steampipe/config/aws.spc. Edit your connection configuration file and then restart Steampipe. (SQLSTATE HV000)
+-----------+--------+
| topic_arn | region …
```
> Steampipe Ignores AWS_DEFAULT_REGION variable after latest change. Fixes #1408

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.84.2

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.85.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.86.0

- aws/table_aws_ec2_capacity_reservation.go
- go.mod
- go.sum
<details>
```
SETUP: tests/aws_ec2_capacity_reservation []
PRETEST: tests/aws_ec2_capacity_reservation
TEST: tests/aws_ec2_capacity_reservation
data.aws_caller_identity.current: Read complete after 1s …
```
> Add column capacity_allocations to table aws_ec2_capacity_reservation closes #1416

- aws/plugin.go
- aws/table_aws_backup_legal_hold.go
- docs/tables/aws_backup_legal_hold.md
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
> select
legal_hold_id,
arn,
creation_date,
cancellation_date
from
aws_backup_legal_hold;
+--------------------------------------+---------------------------------------------------------------------------------------+---------------------------+-------------------+
| legal_hold_id                        | arn                                                                                   | creation_date             | cancellation_date |
+--------------------------------------+---------------------------------------------------------------------------------------+---------------------------+-------------------+
| 2c72c4e3-2936-4d53-8eb6-fdafce991da6 | …
```
> Add table aws_backup_legal_hold closes #1439

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.87.0

- aws/table_aws_ecs_service.go
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
> select title, platform_family from aws_ecs_service
+-------+-----------------+
| title | platform_family |
+-------+-----------------+
| test  | Linux           |
+-------+-----------------+
>
```
</details>
> Add column platform_family to table aws_ecs_service . closes #1462

- aws/plugin.go
- aws/table_aws_vpc_verified_access_trust_provider.go
- docs/tables/aws_vpc_verified_access_trust_provider.md
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
> select
verified_access_trust_provider_id,
creation_time,
device_trust_provider_type,
last_updated_time,
policy_reference_name,
trust_provider_type
from
aws_vpc_verified_access_trust_provider;
+-----------------------------------+---------------------------+----------------------------+---------------------------+-----------------------+---------------------+
| verified_access_trust_provider_id | creation_time             | device_trust_provider_type | last_updated_time         | policy_reference_name | trust_provider_type |
+-----------------------------------+---------------------------+----------------------------+---------------------------+-----------------------+---------------------+ …
```
> Add table aws_vpc_verified_access_trust_provider closes #1469

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.88.0

- aws/table_aws_ecs_task.go
- docs/tables/aws_ecs_task.md
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Add protection column to aws_ecs_task table. closes #1421

- aws/plugin.go
- aws/table_aws_drs_job.go
- docs/tables/aws_drs_job.md
<details>
```
N/A
```
</details>
<details>
```
N/A
```
</details>
> Add table aws_drs_job. closes #1458

- aws/table_aws_eks_addon_version.go
- docs/tables/aws_eks_addon_version.md
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
> select addon_name, jsonb_pretty(addon_configuration) from aws_eks_addon_version limit 10
+--------------------+----------------------------------------------------------------------------------------------------------------------------+
| addon_name         | jsonb_pretty                                                                                                               |
+--------------------+----------------------------------------------------------------------------------------------------------------------------+
| aws-ebs-csi-driver | {                                                                                                                          |
| …
```
> Add add-on configuration details to aws_eks_addon_version table closes #1507

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.89.0

- aws/plugin.go
- aws/table_aws_securitylake_data_lake.go
- docs/tables/aws_securitylake_data_lake.md
<details>
```
N/A
```
</details>
<details>
```
> select
encryption_key,
replication_role_arn,
s3_bucket_arn,
status
from
aws_securitylake_data_lake;
+----------------+-------------------------------------------------------------------------+------------------------------------------------------------------------------+-----------+
| encryption_key | replication_role_arn                                                    | s3_bucket_arn                                                                | status    |
+----------------+-------------------------------------------------------------------------+------------------------------------------------------------------------------+-----------+
| S3_MANAGED_KEY | <null> …
```
> Add table aws_securitylake_data_lake closes #1441

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.90.0

- aws/plugin.go
- aws/table_aws_glue_data_quality_ruleset.go
- docs/tables/aws_glue_data_quality_ruleset.md
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Add table aws_glue_data_quality_ruleset closes #1506

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.91.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.91.1

- aws/plugin.go
- aws/table_aws_health_affected_entity.go
- docs/tables/aws_health_affected_entity.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add table aws_health_affected_entity closes #1410

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.92.0

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with steampipe-plugin-sdk v4.1.10

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.92.1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.92.2

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.94.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.95.0

- aws-test/tests/aws_cloudfront_response_headers_policy/test-get-expected.json
- aws-test/tests/aws_cloudfront_response_headers_policy/test-get-query.sql
- aws-test/tests/aws_cloudfront_response_headers_policy/test-list-expected.json
- aws-test/tests/aws_cloudfront_response_headers_policy/test-list-query.sql
- aws-test/tests/aws_cloudfront_response_headers_policy/test-turbot-expected.json
- aws/table_aws_cloudfront_response_headers_policy.go
<details>
```
SETUP: tests/aws_cloudfront_response_headers_policy []
PRETEST: tests/aws_cloudfront_response_headers_policy
TEST: tests/aws_cloudfront_response_headers_policy
data.aws_caller_identity.current: Read …
```
> Fixed duplicate result in aws_cloudfront_response_headers_policy table. closes #1571

- aws/common_columns.go
- aws/multi_region.go
- aws/service.go
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with steampipe-plugin-sdk v5.2.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.96.0

- aws/table_aws_health_affected_entity.go
<details>
```
```
</details>
<details>
```
```
</details>
> Add `ParentHydrate` to `listHealthEvents` in table `aws_health_affected_entity`. Fixes  #1580

- aws/plugin.go
- aws/service.go
- aws/table_aws_appstream_image.go
- docs/tables/aws_appstream_image.md
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
> select
name,
arn,
base_image_arn,
description,
created_time,
display_name,
image_builder_name,
tags
from
aws_appstream_image;
+------------------------------------------------------+----------------------------------------------------------------------------------------------+----------------+---------------------------------------------------------------------------+------------------------->
| name                                                 | arn                                                                                          | base_image_arn | description                                                               | created_time            > …
```
> Add table aws_appstream_image. Closes #1656

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.97.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.98.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.99.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.100.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.102.0

- docs/tables/aws_ssoadmin_account_assignment.md
<details>
```
```
</details>
<details>
```
```
</details>
> Fixed the example query in the doc for the table aws_ssoadmin_account_assignment Closes #1733

- aws/plugin.go
- aws/table_aws_ec2_client_vpn_endpoint.go
- docs/tables/aws_ec2_client_vpn_endpoint.md
<details>
```
```
</details>
<details>
```
select * from aws_ec2_client_vpn_endpoint
[
{
"_ctx": {
"connection_name": "default"
},
"account_id": "112233445566",
"authentication_options": [
{
"ActiveDirectory": null,
"FederatedAuthentication": null,
"MutualAuthentication": {
"ClientRootCertificateChain": "arn:aws:acm:us-east-1:112233445566:certificate/68ed52d9-ae3e-4543-a2d5-112233445566"
},
"Type": "certificate-authentication"
}
],
"client_cidr_block": "10.0.0.0/10",
"client_connect_options": {
"Enabled": false,
"LambdaFunctionArn": null,
"Status": {
"Code": "applying",
"Message": null
}
},
"client_log_options": null,
"client_login_banner_options": {
"BannerText": null,
"Enabled": false
}, …
```
> Add table aws_ec2_client_vpn_endpoint closes #1717

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.103.0

- aws/table_aws_cloudwatch_metric_data_point.go
- docs/tables/aws_cloudwatch_metric_data_point.md
<details>
```
```
</details>
<details>
```
```
</details>
> Rename the account_id column to source_account_id in aws_cloudwatch_metric_data_point table

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.104.0

- docs/tables/aws_inspector2_finding.md
<details>
```
```
</details>
<details>
```
```
</details>
> Fixed example query for the table aws_inspector2_finding

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.105.1

- aws/table_aws_ecr_image.go
- docs/tables/aws_ecr_image.md
<details>
```
NA
```
</details>
<details>
```
> select
artifact_name,
artifact_type,
metadata,
results
from
trivy_scan_artifact as a,
aws_ecr_image as i
where
artifact_name = image_uri
and repository_name = 'hello';
+-----------------------------------------------------------------------------------------------------------------------------+-----------------+------------------------------------------
| artifact_name                                                                                                               | artifact_type   | metadata                                 
+-----------------------------------------------------------------------------------------------------------------------------+-----------------+------------ …
```
> Add image_uri column in aws_ecr_image table

- aws/plugin.go
- aws/table_aws_organizations_policy_target.go
- docs/tables/aws_organizations_policy_target.md
<details>
```
N/A
```
</details>
<details>
```
> select * from aws_organizations_policy_target where id = 'p-FullAWSAccess'
+---------------+-----------------+-----------+--------------------------------------------------------------------------+------------------------+-------------+----------------------------------+------------------------------------------------------------------------->
| name          | id              | target_id | arn                                                                      | type                   | aws_managed | description                      | content                                                                 >
+---------------+-----------------+-----------+------------------------------------ …
```
> Add table aws_organizations_policy_target Closes #1761

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.107.0

- aws/plugin.go
- aws/table_aws_identitystore_group_membership.go
- docs/tables/aws_identitystore_group_membership.md
<details>
```
N/A
```
</details>
<details>
```
> select
m.membership_id,
m.group_id,
m.identity_store_id,
u.name as user_name
from
aws_sso_billing.aws_identitystore_group_membership as m,
aws_sso_billing.aws_identitystore_user as u
where
m.identity_store_id = 'd-23243214113'
and
u.identity_store_id = m.identity_store_id
and
u.id = m.member_id;
+--------------------------------------+--------------------------------------+-------------------+-------------------+
| membership_id                        | group_id                             | identity_store_id | user_name         |
+--------------------------------------+--------------------------------------+-------------------+-------------------+
| 317b5530-f081-7005-8582-45148f0071dc | …
```
> Add table aws_identitystore_group_membership Closes #1778

- docs/index.md
Added documentation on how to use Steampipe in ECS and config it to use cross account IAM roles
<details>
```
```
</details>
<details>
```
```
</details>
> Added documentation for ECS

- config/aws.spc
- docs/index.md
- docs/tables/aws_appautoscaling_policy.md
<details>
```
```
</details>
<details>
```
```
</details>
> Fix typos in the docs and add better documentation for `ignore_error_codes` config argument closes #1793

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.108.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.109.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.109.1

- docs/tables/aws_vpc_nat_gateway.md
<details>
```
```
</details>
<details>
```
```
</details>
> Typo: aws_nat_gateway => aws_vpc_nat_gateway

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.112.0

- aws/table_aws_api_gatewayv2_api.go
<details>
```
```
</details>
<details>
```
```
</details>
> feat: add description column to aws_api_gatewayv2_api table

- aws/table_aws_sqs_queue.go
<details>
```
```
</details>
<details>
```
```
</details>
> feat: add fifo_throughput_limit and deduplication_scope columns to aws_sqs_queue table

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.114.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.115.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.116.0

- docs/tables/aws_cognito_identity_pool.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add example queries for `aws_cognito_identity_pool` table

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.117.0

- aws/multi_region.go
<details>
```
```
</details>
<details>
```
```
</details>
> Typo: avaialble => available

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.118.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.118.1

- aws/table_aws_elastic_beanstalk_environment.go
- docs/tables/aws_elastic_beanstalk_environment.md
<details>
```
```
</details>
<details>
```sql
> select arn, application_name, environment_id, configuration_settings from aws_elastic_beanstalk_environment
[
{
"application_name": "app-test-1",
"arn": null,
"configuration_settings": [
{
"ApplicationName": "app-test-1",
"DateCreated": "2023-09-26T06:28:46Z",
"DateUpdated": "2023-09-26T06:28:46Z",
"DeploymentStatus": "deployed",
"Description": null,
"EnvironmentName": "App-test-1-env",
"OptionSettings": [
{
"Namespace": "aws:autoscaling:asg",
"OptionName": "Availability Zones",
"ResourceName": "AWSEBAutoScalingGroup",
"Value": "Any"
},
{
"Namespace": "aws:autoscaling:asg",
"OptionName": "Cooldown",
"ResourceName": "AWSEBAutoScalingGroup",
"Value": …
```
> Add column configuration_settings to aws_elastic_beanstalk_environment table closes #1906

- aws/service.go
<details>
```
```
</details>
<details>
```
```
</details>
> Update service.go file to use Info level logging instead of Trace

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update CHANGELOG v0.119.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.120.1

- aws/service.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix lint error in service.go file

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.121.1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.122.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update CHANGELOG v0.122.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.123.0

- .gitignore
- .goreleaser.yml
- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update the goreleaser file to build netgo package for Darwin systems

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.125.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.126.0

- aws/table_aws_lambda_function.go
- go.sum
<details>
```
```
</details>
<details>
```
> select layers from aws_lambda_function limit 1
+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| layers                                                                                                                                                  |
+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| [{"Arn":"arn:aws:lambda:me-central-1:464622532012:layer:Datadog-Extension:31","CodeSize":9563908,"SigningJobArn":null,"SigningProfileVersionArn":nul …
```
> Add layers column to aws_lambda_functions

- aws/table_aws_rds_db_instance.go
<details>
```
```
</details>
<details>
```
```
</details>
> Add RDS DB Instance Storage Throughput to query values

- aws/table_aws_rds_db_instance.go
<details>
```
```
</details>
<details>
```
```
</details>
> Add RDS DB Instance Storage Throughput to query values (#2010)

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.127.0

- aws/plugin.go
- aws/table_aws_cloudtrail_lookup_event.go
- docs/tables/aws_cloudtrail_lookup_event.md
<details>
```
N/A
```
</details>
<details>
```
> select * from aws_cloudtrail_lookup_event where username = 'SSM' limit 4
+--------------------------------------+----------------------+----------------------+-----------+---------------------------+----------+------------+---------------+---------------+----------+-----------+------------------------------------------------------------------>
| event_id                             | event_name           | event_source         | read_only | event_time                | end_time | start_time | resource_name | resource_type | username | resources | cloud_trail_event                                                >
+--------------------------------------+----------------------+------------------ …
```
> Add table aws_cloudtrail_lookup_event Closes #1902

- .github/workflows/steampipe-anywhere.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Add a dispatch workflow trigger to the steampipe anywhere workflow

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.131.0

- CHANGELOG.md
- aws/table_aws_rds_db_instance.go
- docs/tables/aws_rds_db_instance.md
<details>
```
N/A
```
</details>
<details>
```
Before fix:
> select processor_features from aws_rds_db_instance
Error: aws: operation error RDS: DescribeOrderableDBInstanceOptions, https response error StatusCode: 400, RequestID: f519c2a9-b3cf-4521-86d7-83adef2c41e8, api error InvalidParameterCombination: Cannot find version 13.7 for postgres (SQLSTATE HV000)
+--------------------+
| processor_features |
+--------------------+
After fix:
> select db_instance_identifier,engine, engine_version, processor_features from aws_rds_db_instance
+------------------------+---------------------+-------------------------------+--------------------+
| db_instance_identifier | engine              | engine_version                | processor_features | …
```
> Fixed the InvalidParameterCombination for the table aws_rds_db_instance

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.132.0

- .github/workflows/steampipe-anywhere.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Update jobs in Release Steampipe Anywhere Components workflow to run on main instead of self-hosted branch

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.133.0

- aws/table_aws_backup_job.go
- docs/tables/aws_backup_job.md
<details>
```
```
</details>
<details>
```
```
</details>
> Remove the 'akas' column and tidy up the documents for aws_backup_job table

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add the Enhancements section to v0.134.0 CHANGELOG entry

- .github/workflows/registry-publish-ghcr.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Add Build and Deploy OCI Image - GHCR workflow

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.135.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.136.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.136.1

- aws/plugin.go
- aws/table_aws_kms_key_rotation.go
- docs/tables/aws_kms_key_rotation.md
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
> select
akr.key_id,
ak.title,
akr.rotation_date,
akr.rotation_type,
ak.key_manager
from
aws_kms_key_rotation akr
join
aws_kms_key ak
on
akr.key_id = ak.id;
+--------------------------------------+-----------------------------+---------------------------+---------------+-------------+
| key_id                               | title                       | rotation_date             | rotation_type | key_manager |
+--------------------------------------+-----------------------------+---------------------------+---------------+-------------+
| 7fcee4ac-1feb-41c3-872b-bcdc8b815798 | alias/aws/elasticfilesystem | 2023-05-10T11:33:56+05:30 | AUTOMATIC     | AWS         |
| …
```
> Add table aws_kms_key_rotation Closes #2169

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.137.0

- aws-test/tint.js
<details>
```
```
</details>
<details>
```
```
</details>
> Fixed the integration test script as per the latest Steampipe CLI result

- .goreleaser.yml
- Makefile
<details>
```
```
</details>
<details>
```
```
</details>
> Add support for netgo package build for Linux operating system

- aws/service.go
<details>
```
N/A
```
</details>
<details>
```
```
</details>
> Enhanced API Gateway V2 Service Supported Regions by Excluding il-central-1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.139.0

- .github/workflows/registry-publish-ghcr.yml
- .github/workflows/registry-publish.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Update registry-publish.yml and registry-publish-ghcr.yml to use the latest version of goreleaser commands

- aws/plugin.go
- aws/service.go
- aws/table_aws_codestar_notification_rule.go
- docs/tables/aws_codestar_notification_rule.md
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Add aws_codestar_notificaton_rule table (#2198)

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.141.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.144.0

- docs/tables/aws_appautoscaling_policy.md
- docs/tables/aws_appautoscaling_target.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update table docs for aws_appautoscaling_policy and aws_appautoscaling_target to add info on required quals Closes #2246

- aws/table_aws_kms_key_rotation.go
<details>
```
N/A
```
</details>
<details>
```
Before Fix:
> select * from aws_kms_key_rotation
Error: aws: operation error KMS: ListKeyRotations, https response error StatusCode: 400, RequestID: 37bc3fea-c73f-42a2-b02a-5b1d3928a49c, api error AccessDeniedException: User: arn:aws:iam::xxxxxxxxxxxx:user/partha is not authorized to perform: kms:ListKeyRotations on resource: arn:aws:kms:ap-south-1:xxxxxxxxxxxx:key/98d92245-f66d-428b-a520-7c754efcf83f because no resource-based policy allows the kms:ListKeyRotations action (SQLSTATE HV000)
+--------------------------------------+------------------------------------------------------------------------------+---------------+---------------------------+--------------------------------------+------ …
```
> Fixed the table aws_kms_key_rotation throws AccessDeniedException despite the ignore_error_codes configuration in the connection config Closes #2252

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.145.0

- aws/plugin.go
- aws/table_aws_securityhub_enabled_product_subscription.go
- docs/tables/aws_securityhub_enabled_product_subscription.md
<details>
```
N/A
```
</details>
<details>
```
> select
distinct s.arn as subscription_arn,
p.product_arn,
p.name as product_name,
p.company_name as product_company_name,
p.marketplace_url,
p.integration_types
from
aws_securityhub_enabled_product_subscription as s,
aws_securityhub_product as p,
jsonb_array_elements(p.product_subscription_resource_policy -> 'Statement') as m
where
(m ->> 'Resource') = s.arn;
+----------------------------------------------------------------------------------------+---------------------------------------------------------------+-------------------------------+----------------------+--------------------------------------------------------------+---------------------------------------+
| subscription_arn …
```
> Add table aws_securityhub_enabled_product_subscription Closes #2256

- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
```
</details>
> Recompile plugin with steampipe-plugin-sdk v5.10.4

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.146.0

- aws/table_aws_health_event.go
<details>
```
```
</details>
<details>
```
```
</details>
> Added column event_region to the table aws_health_event Closes #2287

- aws/table_aws_codebuild_source_credential.go
- aws/table_aws_ec2_ssl_policy.go
<details>
```
```
</details>
<details>
```
```
</details>
> Placed the log statement in correct place for the table aws_codebuild_source_credential and aws_ec2_ssl_policy

- aws/table_aws_msk_cluster.go
<details>
```
```
</details>
<details>
```
```
</details>
> Add column BootstrapBrokers(bootstrap_broker_string, bootstrap_broker_string_tls) in table aws_msk_cluster (#2390)

- aws/table_aws_rds_db_instance.go
<details>
```
```
</details>
<details>
```
> select db_instance_identifier, jsonb_pretty(pending_modified_values) from aws_rds_db_instance; 
+------------------------+----------------------------------------------+
| db_instance_identifier | jsonb_pretty                                 |
+------------------------+----------------------------------------------+
| turbottest70130        | {                                            |
|                        |     "Iops": null,                            |
|                        |     "Port": null,                            |
|                        |     "Engine": null,                          |
|                        |     "MultiAZ": null, …
```
> Added column pending_modified_values to the table aws_rds_db_instance Closes #2379

- aws/table_aws_waf_rule_group.go
- aws/table_aws_waf_web_acl.go
- aws/table_aws_wafregional_rule_group.go
- aws/table_aws_wafregional_web_acl.go
- aws/table_aws_wafv2_ip_set.go
- aws/table_aws_wafv2_regex_pattern_set.go
- aws/table_aws_wafv2_rule_group.go
- aws/table_aws_wafv2_web_acl.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix lint failure for the plugin

- aws/table_aws_lambda_function.go
<details>
```
```
</details>
<details>
```
> select name, logging_config from aws_lambda_function
+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| name                                                      | logging_config                                                                                                                                       |
+-----------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------- …
```
> Add column logging_config in the table aws_lambda_function Closes #2422

- docs/tables/aws_region.md
> Update list of enabled aws regions query title in docs

- aws/plugin.go
- aws/table_aws_rds_db_cluster.go
- aws/table_aws_rds_db_instance.go
- aws/table_aws_rds_pending_maintenance_action.go
- docs/tables/aws_rds_db_cluster.md
- docs/tables/aws_rds_db_instance.md
- docs/tables/aws_rds_pending_maintenance_action.md
<details>
```
```
</details>
<details>
```
```
</details>
> feat(table): add aws_rds_pending_maintenance_action (#2430)

- aws/plugin.go
- aws/table_aws_elasticache_update_action.go
- docs/tables/aws_elasticache_cluster.md
- docs/tables/aws_elasticache_replication_group.md
- docs/tables/aws_elasticache_update_action.md
<details>
```
```
</details>
<details>
```
```
</details>
> feat(table): add aws_elasticache_update_action (#2431)

- aws/plugin.go
- aws/table_aws_s3_multipart_upload.go
- docs/tables/aws_s3_multipart_upload.md
<details>
```
N/A
```
</details>
<details>
```
> select
u.bucket_name,
u.key,
u.upload_id,
u.initiated,
u.storage_class,
b.versioning_enabled,
b.region
from
aws_s3_multipart_upload as u
join aws_s3_bucket as b on u.bucket_name = b.name;
+---------------------------------------------------------+----------------+----------------------------------------------------------------------------------------------------------------------------------+---------------------------+---------------+------------------>
| bucket_name                                             | key            | upload_id                                                                                                                        | initiated                 | …
```
> Add table aws_s3_multipart_upload Closes #2448

- aws/service.go
<details>
```
```
</details>
<details>
```
> > select region from aws_ec2_ami limit 1
+-----------+
| region    |
+-----------+
| eu-west-3 |
+-----------+
> select count(*) from aws_health_event
+-------+
| count |
+-------+
| 24    |
+-------+
```
</details>
> fix: AWS Health is only available in us-east-1, us-east-2 and us-gov-west-1

- aws/canonical_policy.go
- aws/service.go
- aws/table_aws_cloudwatch_log_metric_filter.go
- aws/table_aws_cost_usage.go
- aws/table_aws_ec2_launch_template_version.go
- aws/table_aws_iam_credential_report.go
- aws/table_aws_organizations_account.go
- aws/table_aws_organizations_organizational_unit.go
- aws/table_aws_resource_explorer_search.go
- aws/table_aws_servicecatalog_provisioned_product.go
- aws/table_aws_ssm_inventory.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fixed the lint failure errors across the tables

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v1.14.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v1.15.0

- aws/multi_region.go
- aws/table_aws_s3_bucket.go
- aws/table_aws_s3_bucket_intelligent_tiering_configuration.go
- aws/table_aws_s3_object_version.go
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
> select * from aws_s3_bucket;
+-----------------------------------------------------------------+------------------------------------------------------------------------------+---------------------------+-------------------------+--------------------+-----------------------+-------------------+---------------------+-------------->
| name                                                            | arn                                                                          | creation_date             | bucket_policy_is_public | versioning_enabled | versioning_mfa_delete | block_public_acls | block_public_policy | ignore_public> …
```
> Update aws_s3_bucket table to use region from list tables API Closes #2461

- aws/plugin.go
- aws/table_aws_api_gateway_account.go
- docs/tables/aws_api_gateway_account.md
<details>
```
N/A
```
</details>
<details>
```
> select
cloudwatch_role_arn,
api_key_version,
throttle_burst_limit,
throttle_rate_limit,
features,
region,
account_id
from
aws_api_gateway_account;
+-------------------------------------------------------------+-----------------+----------------------+---------------------+----------------+----------------+--------------+
| cloudwatch_role_arn                                         | api_key_version | throttle_burst_limit | throttle_rate_limit | features       | region         | account_id   |
+-------------------------------------------------------------+-----------------+----------------------+---------------------+----------------+----------------+--------------+
| …
```
> Add table aws_api_gateway_account

- .github/ISSUE_TEMPLATE/feature-request---new-table.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update issue templates to add new labels

- aws/plugin.go
- aws/service.go
- aws/table_aws_bedrock_agent.go
- aws/table_aws_bedrock_knowledge_base.go
- docs/tables/aws_bedrock_agent.md
- docs/tables/aws_bedrock_knowledge_base.md
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
select * from aws_charizard_ved.aws_bedrock_agent
+------------+-------------------------+--------------+---------------------------+-------------------------+----------------------+-------------------------+---------------------------------------------------------+-------------------------+---------------+----------->
| agent_id   | agent_name              | agent_status | updated_at                | description             | latest_agent_version | guardrail_configuration | arn                                                     | agent_resource_role_arn | agent_version | created_at>
+------------+-------------------------+--------------+-------------------- …
```
> Add aws_bedrock_agent and aws_bedrock_knowledge_base tables closes #2575 #2574

- aws/plugin.go
- aws/table_aws_vpc_security_group_vpc_association.go
- docs/tables/aws_vpc_security_group_vpc_association.md
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
> select * from aws_vpc_security_group_vpc_association where vpc_id = 'vpc-06ece4462331fec08'
+----------------------+-----------------------+--------------+------------+----------------------------------------------+-----------+-----------+--------------+--------------------+------------------->
| group_id             | vpc_id                | vpc_owner_id | state      | title                                        | partition | region    | account_id   | sp_connection_name | sp_ctx            >
+----------------------+-----------------------+--------------+------------+----------------------------------------------+-----------+-----------+--------------+--- …
```
> Add table aws_vpc_security_group_vpc_association Closes #issue-2596

- aws/plugin.go
- aws/table_aws_ec2_spot_fleet_request.go
- docs/tables/aws_ec2_spot_fleet_request.md
<details>
```
```
</details>
<details>
```
> select * from aws_ec2_spot_fleet_request
+------------------------------------------+--------------------------+-----------------+---------------------------+---------+-----------------+---------------------------+------------------------+---->
| spot_fleet_request_id                    | spot_fleet_request_state | activity_status | create_time               | type    | target_capacity | target_capacity_unit_type | allocation_strategy    | iam>
+------------------------------------------+--------------------------+-----------------+---------------------------+---------+-----------------+---------------------------+------------------------+---->
| …
```
> Add table aws_ec2_spot_fleet_request Closes #2594

- aws/plugin.go
- aws/table_aws_transfer_connector.go
- docs/tables/aws_transfer_connector.md
<details>
```
```
</details>
<details>
```
> select * from aws_transfer_connector where connector_id = 'c-40cf12840abe45f7a'
+---------------------+-----------------------------------------------------------------------+-----------------+----------------------------------------------------------------------------------------+----------->
| connector_id        | arn                                                                   | url             | access_role                                                                            | logging_ro>
+---------------------+-----------------------------------------------------------------------+-----------------+------------------------------------------ …
```
> Add table aws_transfer_connector Closes #2602

- aws/plugin.go
- aws/table_aws_servicecatalog_portfolio_share.go
- docs/tables/aws_servicecatalog_portfolio_share.md
<details>
```
```
</details>
<details>
```
> select * from aws_servicecatalog_portfolio_share where type = 'ACCOUNT'
+--------------------+---------------------------------------------------------------------+------------------------+---------+--------------+----------+------------------+-------------------+--------------------->
| portfolio_id       | portfolio_arn                                                       | portfolio_display_name | type    | principal_id | accepted | share_principals | share_tag_options | title               >
+--------------------+---------------------------------------------------------------------+------------------------+---------+--------------+----------+---------- …
```
> Add table aws_servicecatalog_portfolio_share Closes #2609

- aws/plugin.go
- aws/table_aws_inspector2_organization_configuration.go
- docs/tables/aws_inspector2_organization_configuration.md
<details>
```
```
</details>
<details>
```
N/A
```
</details>
> Add table aws_inspector2_organization_configuration Closes #2604

- aws/table_aws_ec2_load_balancer_listener_rule.go
<details>
```
```
</details>
<details>
```
> select arn, tags_src, tags from aws_ec2_load_balancer_listener_rule where listener_arn = 'arn:aws:elasticloadbalancing:us-east-1:************:listener/app/test-app-lb/37f8a55e673a3e5e/48a489d49c82089a'
+--------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+-----------------------------+
| arn                                                                                                                                  | tags_src                                                    | tags                        | …
```
> Added tags_src, and tags column to the table aws_ec2_load_balancer_listener_rule Closes #2623
